### ISSUE TITLE
Не раскручивать стол отвёрткой

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#102]

**Comment by cuddleandtea** [comment]
Отец, я согрешил. Сотворил то же, что и Адам с Евой в Эдеме. Открутил и у стального и у деревянного стола укрепление. Но грехопадения не произошло. И далее все манипуляции с отвёрткой и гаечным ни к каким багам не привели. Спасибо

**Comment by LordNest** [comment]
@SuhEugene это вообще что за The Who?

**Comment by SuhEugene** [comment]
> @SuhEugene это вообще что за The Who?

@LordNest чтобы я не забыл стол переделать
