### ISSUE TITLE
Баг: Жучки странно мигают

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1027]
**Ckey**:
`Zagadka`

**Шаги:**
1. Купить "Набор жучков" в аплинке
2. Привязать пару жучков, начать смотреть
3. Увидеть баг

**Реальное поведение:**
Экран постоянно переключается на камеру и обратно(видео в ветке)

**Ожидаемое поведение:**
Экран не переключается, можно спокойно наблюдать
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152323316204437634)

**Comment by LordNest** [comment]
Окончательно и бесповоротно нарекаю фичей, которая призвана избегать застревания в интерфейсе жучков и поимки СБухами
