### ISSUE TITLE
Запрос: Пропало несколько триторских предметов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1031]
**Название:**
`Триторские предметы`

**Дополнительная информация:**
Список пропавших предметов: 
 - [x] Инструмент для блэкаута,
 - [x] Сумка с С-4 (несколькими), 
 - [x] ключ для всех каналов, 
 - [x] Блюспейс-телепорт, 
 - [x] Набор юного отравителя, 
 - [x] Плата законов, 
 - [x] Коробка голобомб, 
 - [x] Котелок с лезвием, 
 - [x] ПСИ шлем, 
 - [x] радиактивный микролазер, 
 - [x] стимпак
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152326734146977964)

**Comment by LordNest** [comment]
Частично пофикшенно мной, но не до конца. 
Нужно ещё фиксы накатить.

**Comment by LordNest** [comment]
Телепорт - чек
Шляпа - чек (в коде)
Пси-амп - чек
Сумка - чек
Плата - чек (в коде)
Голобомбы - чек
