### ISSUE TITLE
Запрос: Изменить "цены" на скиллы в лодауте, как на обычном Сыре

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1032]
**Название:**
`Лодаут, Characters Setup`

**Дополнительная информация:**
Изменить "цены" на скиллы в лодауте, как на обычном Сыре, а конкретно ближний бой, атлетику. (скрины в ветке)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152327428392366200)

**Comment by SuhEugene** [comment]
Нест говорит, что всё норм, но раз уж пошла такая движуха с духотой, можно и мастера атлетики ограничить, подняв до 4х.

На инфинити 10 стоит мастер. На оффах 6. У нас, получается, выйдет 8.

Не думаю, что игроки обидятся, если внезапно атлетика окажется на 2 очка дешевле

**Comment by SuhEugene** [comment]
КУДА

**Comment by LordNest** [comment]
Короче за год ничего видимо не поменялось, или поменялось но отдельно
