### ISSUE TITLE
Запрос: У триторского hacking tool нет прогресс бара

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1033]
**Название:**
`hacking tool, Устройства взлома шлюзов`

**Дополнительная информация:**
У триторского hacking tool (Устройства взлома шлюзов) (выглядит как мультитул) нет прогресс бара (видео в ветке)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152327914046640178)

**Comment by LordNest** [comment]
Так как прогресс бар виден не только тому, кто делает действие, то это будет де маскировать тритора
Кроме того там сразу вылетает окно, так что не нужен он там.
