### ISSUE TITLE
Звук: Звук ЕМАГа

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1039]
**Название:**
`ЕМАГ`

**Дополнительная информация:**
Звук пропал, его нет. Шкафы, створки, шлюзы взламываются почти беззвучно (видео в ветке)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152338120637939772)

**Comment by cuddleandtea** [comment]
Не баг, а фича. Звук взлома был крайне громким и на большую зону. Оффбей убрал его, как и звук закрытых дверей.
