### ISSUE TITLE
Объект: Мультитул

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#104]
**Объект:**
Мультитул

**Название:**
`multitool`

**Дополнительная информация:**
Да, там переносить большое количество механа, но очень важно про него не забыть
<hr>

*Это сообщение сгенерировано автоматически*
*Автор оригинального репорта: `SuhEugene#4680`*

**Comment by LordNest** [comment]
Может таки Combitool?
И оно используется считай в... патрульке, потому что мало места в планшетах, которые я поменял?

**Comment by SuhEugene** [comment]
Я про жёлтую дичь из инженерки

**Comment by LordNest** [comment]
#327 является более корректной вещью, так как мультиметр та самая "жёлтая дичь"
Закрываем.
