### ISSUE TITLE
Звук: Пропал звук ботинок-перевертышей

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1040]
**Название:**
`ботинки-перевертыши`

**Дополнительная информация:**
Пропал звук ботинок-перевертышей, ты ходишь беззвучно (может это фича? Тем не менее видео в ветке)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1152338463677481111)

**Comment by LordNest** [comment]
`	item_flags = ITEM_FLAG_SILENT`
Фича
