### ISSUE TITLE
Музыка Jukebox'а и Лобби

### ISSUE THREAD

**Issue by LordNest** [SierraBay/SierraBay12#105]
## Jukebox
- Caravan Palace - Lone Digger

## Лобби
*Пока что здесь пусто*

**Comment by SuhEugene** [comment]
Давай уж тогда отдельным issue - жукбокс, отдельным - лобби
Ну или поделить... Сча отредачу

**Comment by LordNest** [comment]
Задача совсем не приоритетная, если что

**Comment by LordNest** [comment]
Часть добавили, част не добавили, в целом иссуй не нужен как таковой
