### ISSUE TITLE
Карта: Лампы в баре не светят

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1074]
**Название:**
`small neon tube`

**Дополнительная информация:**
Лампочки в баре светят ОЧЕНЬ тускло
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157339380566986864)

**Comment by YegorKandziuba** [comment]
Исправлено
