### ISSUE TITLE
Запрос: У панелей солнечных появились десятые и сотые

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1076]
**Название:**
`Солнечные панели`

**Дополнительная информация:**
У панелей солнечных появились десятые и сотые (Зачем? Почему?). Вручную стало неудобно настраивать.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157343307765125170)

**Comment by LordNest** [comment]
А кто-то пользуется ручным режимом?
