### ISSUE TITLE
Старый спрайт: heavy exploration HCM

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1077]
**Объект:**
heavy exploration HCM

**Название:**
`heavy exploration HCM`

**Дополнительная информация:**
Спрайта просто нету
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157345749189795931)

**Comment by LordNest** [comment]
Я же тебя закрыл, ЧОРТ
Исправлено мной.
