### ISSUE TITLE
Запрос: ИКСы "Из" Дедспейса

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1078]
**Название:**
`HCM, ИКСы, РИГи, ну вы поняли`

**Дополнительная информация:**
Инвалидная механика что нельзя снимать части ИКСа в активной форме, а при деактивации нужно срывать его со спины вместе с броней на тебе. Отговорка что Как в Дедспейте не катит, потому что там он разложится на 1 секунду, у нас же это долгий процесс АФК, с ограниченной видимостью и ограничение движения, + кто толкнул и все по новой.

Вариант решения прост. Либо запилить как было, и не умничать. Либо в активированном режиме позволить сложить его в спину, а потом в нужный момент разложить за 1 секунду
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157347569777791107)

**Comment by LordNest** [comment]
Этот закрываем и берём в работу #1421
