### ISSUE TITLE
Механ: Взлом шкафа

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1080]
**Название:**
`Шкаф`

**Дополнительная информация:**
Раньше можно было взломать шкаф мультиметром, его вырезали, теперь как дураки ломаем шкафы.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157349860731797635)

**Comment by SuhEugene** [comment]
Емаг момент

**Comment by LordNest** [comment]
closed by #1847
