### ISSUE TITLE
Старый спрайт: Темный прогресс бар

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1082]
**Объект:**
Темный прогресс бар

**Название:**
`прогресс бар`

**Дополнительная информация:**
Темный прогресс бар, это неудобно. На обычном Сыре он светлее и сильно лучше виднее.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157350438887243869)

**Comment by LordNest** [comment]
Так как прогресс бары видно всем, то это фича
