### ISSUE TITLE
Баг: Спрайт мусорки ломается, когда она включена

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1083]
**Ckey**:
`Zagadka`

**Шаги:**
1. найти мусорку, например в баре
2. потыкать в ней кнопки
3. наблюдать странный спрайт

**Реальное поведение:**
Появляется невнятный кусок спрайта

**Ожидаемое поведение:**
Не появляется невнятный кусок спрайта
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157350928572231781)

**Comment by cuddleandtea** [comment]
Оверлеи стандартных мусорок накладываются. Самое простое решение - отключить их для настенных мусорок
