### ISSUE TITLE
Запрос: Не нужное подписывание предметов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1085]
**Название:**
`Tooltip`

**Дополнительная информация:**
Не нужное подписывание предметов снизу, так как уже есть подписывание сверху экрана. Зачем два раза подписывать предмет?
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1157368914032988340)

**Comment by SuhEugene** [comment]
Добавить настройку: Всё/статусбар/скринтип/выключить
