### ISSUE TITLE
Механ: Потеряные культуры и планеты обитания

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1094]
**Название:**
`Утеряные диалекты культур и сила экономик`

**Дополнительная информация:**
Утеряные культуры: лорриман, никс, авалон+авалон нобл., лордания, мириания, Лордания вверхняя и нижняя а вместе с ним их силы экономики, которые влияли на бюджет игрока +можно было внутри клиента почитать кратко о своём обиталище. Помимо этого пропали диалекты, такие как: Лиррис, Алиан, Мириан, которые выдавались при выборе соответствующего места обитания.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SuhEugene** [comment]
Короче это уже сделали, а #1504 не дубликат
