### ISSUE TITLE
Баг: Шкафы из картона

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1095]
**Ckey**:
`Daviii22`

**Шаги:**
1. Подойти к любому шкафу в оружейке, шкафу глав и другие.
2. Взять любой предмет, например тулбокс.
3. Ломать шкаф этим предметом.

**Реальное поведение:**
Картонные шкафы ломаются быстрее, чем тритор ищет емаг в аплинке. А потом шкаф просто изчезает.

**Ожидаемое поведение:**
Шкаф не ломается тулбоксом, а если и ломается, что не изчезает бесследно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by LordNest** [comment]
Механ оригинальный, с Бея. Не думаю что какая-то проблема. Можно просто увеличить количество ХП/добавить именно слом замка.

**Comment by LordNest** [comment]
Там короче ещё ПР со стандартизацией идёт ХП
И вот короче этот ПР как выйдет
С панчами
Будем смотреть

**Comment by LordNest** [comment]
Это никто не взял с прошлого года, так что видимо намана
