### ISSUE TITLE
Звук: Звук отсутствия доступа к шлюзу

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1157]
**Название:**
`airlock`

**Дополнительная информация:**
Так как на бее его отключили из-за мерзотности, а [ишью о починке](https://github.com/SierraBay/SierraBay12/issues/319) был закрыт, наверное, стоит просто взять кайфовый звук с парадиза
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1164235713143902248)

**Comment by LordNest** [comment]
@SuhEugene когда звук возьмёшь?

**Comment by UEDCommander** [comment]
Решено на оффах
