### ISSUE TITLE
Баг: Ошибка спрайта кейса для сигарет

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1168]
**Ckey**:
`Kkfssjgadgh`

**Шаги:**
1. Взять в руки сигаретный кейс
2. Распаковать сигаретный кейс (Использовать в руке)

**Реальное поведение:**
Пропадает спрайт при открытии сигаретного кейса

**Ожидаемое поведение:**
Должен был появиться спрайт открытого сигаретного кейса
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kekei9470` / `714874058654613545`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1166768180455293071)

**Comment by LordNest** [comment]
Не воспроизводится. Тесты на голом Бее.
