### ISSUE TITLE
Баг: Зависают окошки Say у персонажей

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1188]
**Ckey**:
`CuddleAndTea`

**Шаги:**
1. Начать что-то писать
2. Заметить, что у всех окружающих окошко say в зависшем состоянни. Даже у рыб в баре

**Реальное поведение:**
Say окошко виснет

**Ожидаемое поведение:**
Say должно быстро пропадать
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167442990067884095)

**Comment by cuddleandtea** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/b3545eb9-64d6-42e2-add9-271a33d0cafb)

**Comment by LordNest** [comment]
Решили с теми лагами основными
