### ISSUE TITLE
Карта: Неверный пожарный ящик

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1189]
**Название:**
`fire-safety closet`

**Дополнительная информация:**
![image](https://imgur.com/bpc4Gz0.png)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167446178472927284)

**Comment by YegorKandziuba** [comment]
Исправлен
