### ISSUE TITLE
Карта: Две двери в меде

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1191]
**Название:**
`airlock/multi_tile_medical`

**Дополнительная информация:**
Диры сломаны
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167446731374465186)

**Comment by cuddleandtea** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/15452fdb-103e-4fe2-bb47-cc5240c37a0a)

**Comment by YegorKandziuba** [comment]
Исправлено
