### ISSUE TITLE
Карта: Лишняя кнопка

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1193]
**Название:**
`/obj/machinery/button/blast_door`

**Дополнительная информация:**
x = 34
y = 111
z = 4

Спряталась под бластдором
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167448694874984537)

**Comment by YegorKandziuba** [comment]
Исправлено
