### ISSUE TITLE
Звук: Музыка проходит через баршелтеры

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1194]
**Название:**
`Bar Shutters space jukebox`

**Дополнительная информация:**
Звук проходит сквозь шелтеры, когда они закрыты
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167451240884613210)

**Comment by LordNest** [comment]
ЗАКРЫВАЙТЕ ИШШУИ
