### ISSUE TITLE
Запрос: Добавить старый диван в техи

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1195]
**Название:**
`Ну тупа диван старый`

**Дополнительная информация:**
Перед выходом/входом в техи возле кают адъютантов и АВД добавить старый диван.
Это старый и порванный диван и на него забили хер, так как было лень спускать его по лестнице, а лифт был сломан. Поэтому его тупа оставили в техах.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `semonic` / `361140847682781186`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167451362737537124)

**Comment by SuhEugene** [comment]
Запрос, а не репорт по карте. Тег сменен.

**Comment by YegorKandziuba** [comment]
Добавлен
