### ISSUE TITLE
Карта: Шлюз не назван

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1197]
**Название:**
`airlock`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167452640301551728)

**Comment by LordNest** [comment]
Однажды одного маппера заколдовала ведьма. Он мог закрывать только по одному иссую в год. Долго терпел маппер...
А конец у анека будет потом.
