### ISSUE TITLE
Карта: Джукбокс бьет по ушам

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1198]
**Название:**
`space jukebox`

**Дополнительная информация:**
Джукбокс стоит ПРЯМО В ЛЕВОМ УХЕ, из за чего вся громкость звука очень сильно бьет в него, а в правом ничего нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167452802642096240)

**Comment by YegorKandziuba** [comment]
Исправлено
