### ISSUE TITLE
Карта: ненужная дверь в баре что ведет в теха

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1199]
**Название:**
`Maintenance Access`

**Дополнительная информация:**
Дверь которая ведет прямо из бара в теха, когда в 5 тайлах есть вторая, да и доступа туда нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167453663355224155)

**Comment by YegorKandziuba** [comment]
Исправлено
