### ISSUE TITLE
Запрос: Нет set-ghost-alpha

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1200]
**Название:**
`Прок во вкладке Ghost`

**Дополнительная информация:**
Нужно запилить на оффы, скопировав код с лайва <3
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167454116306493471)

**Comment by LordNest** [comment]
https://github.com/Baystation12/Baystation12/pull/34327
