### ISSUE TITLE
Карта: Не подключена мусорка

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1202]
**Название:**
`Мусорные трубы, мусорка`

**Дополнительная информация:**
Не подключена трубами мусорка в медбее
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167458509777010738)

**Comment by YegorKandziuba** [comment]
Исправлено
