### ISSUE TITLE
Карта: Отстуствует необходимый доступ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1203]
**Название:**
`Шлюзы`

**Дополнительная информация:**
Отстуствует необходимый доступ во многих отсеках, больше в ветке
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167458722679902268)

**Comment by YegorKandziuba** [comment]
Исправлено
