### ISSUE TITLE
Карта: Пять дверей к одной кнопки в офисе АВД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1204]
**Название:**
`Office Door control и Internal Affairs Agent`

**Дополнительная информация:**
Id_tag двери у пяти дверей одинаковый. По нажатию на кнопку тупа открываются все эти двери: Вход в правую приёмную, Переходная дверь в закрытую рабочую зону, Дверь в рабочую зону со стороны коридора, Дверь в каюту АВД со стороны рабочей зоны, дверь в каюту АВД.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `semonic` / `361140847682781186`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167459126834626641)

**Comment by YegorKandziuba** [comment]
Исправлено
