### ISSUE TITLE
Карта: Темнота в крио

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1205]
**Название:**
`Темень?...`

**Дополнительная информация:**
Темно в комнате криокамер, что выглядит очень странно, скрин в ветке
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167459455512891432)

**Comment by YegorKandziuba** [comment]
Исправлено
