### ISSUE TITLE
Карта: Автомат поставлен криво

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1206]
**Название:**
`Торговый автомат`

**Дополнительная информация:**
Автомат поставлен криво в крио на верхних палубах
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167459719191990375)

**Comment by YegorKandziuba** [comment]
Исправление найдено, но нужно дождаться мержа на оффах.
