### ISSUE TITLE
Карта: Лестница не имеет под собой catwalk

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1207]
**Название:**
`catwalk`

**Дополнительная информация:**
Лестница не имеет под собой catwalk (решетку напольную) и её можно обузить, спускаясь очень быстро
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167462236932018206)

**Comment by YegorKandziuba** [comment]
Исправлено
