### ISSUE TITLE
Карта: Нужен шлюз со стеклом

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1209]
**Название:**
`Шлюз`

**Дополнительная информация:**
Нужен шлюз со стеклом, чтобы можно было смотреть сквозь него, иначе смотрится некрасиво
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167465989861023847)

**Comment by YegorKandziuba** [comment]
Исправлен
