### ISSUE TITLE
Карта: Лампочка в дормах не в том месте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1210]
**Название:**
`Лампочка`

**Дополнительная информация:**
Лампочка в дормах не в том месте
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167474338086260736)

**Comment by YegorKandziuba** [comment]
Исправлено
