### ISSUE TITLE
Механ: Set Ghost Alpha

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1212]
**Название:**
`Режим Ghost`

**Дополнительная информация:**
Set Ghost Alpha - можно было стать невидимым в гостах, что было удобно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167484448984543333)

**Comment by SuhEugene** [comment]
Дубликат:
- #1200
