### ISSUE TITLE
Карта: Контроллер находится не там

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1213]
**Название:**
`Controlls`

**Дополнительная информация:**
Контроллер атмосферного находится не там, выглядит криво, скрин в ветке
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167493506495959070)

**Comment by YegorKandziuba** [comment]
Исправлено
