### ISSUE TITLE
Карта: Ненужные кнопки в ангаре.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1216]
**Название:**
`Storage Door Control`

**Дополнительная информация:**
Кнопки там, где их не должно быть: от Харона - справа около створок на полу и слева на стене.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167500949116424233)

**Comment by YegorKandziuba** [comment]
Исправлено
