### ISSUE TITLE
Карта: Лишняя кнопка под створками, ведущие к ОФД.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1219]
**Название:**
`Obstruction Field Disperser Blast Door`

**Дополнительная информация:**
Лишняя кнопка на полу.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167503711640236032)

**Comment by YegorKandziuba** [comment]
Исправлено
