### ISSUE TITLE
Карта: Лампа развернутая не в ту сторону.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1220]
**Название:**
`spotlight`

**Дополнительная информация:**
Лампа, которую видно из коридора и которая светит В стену. Около шлюза (Bridge Wardroom) на мостике в капитанской.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167504351493881890)

**Comment by YegorKandziuba** [comment]
Исправлено
