### ISSUE TITLE
Карта: Совмещенные зоны коридора и отдельного помещения.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1221]
**Название:**
`light switch (Fourth Deck - Docking Bay).`

**Дополнительная информация:**
Из-за этого света на 5ой палубе у носа нету, пока не включишь этот переключатель.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167505079813812334)

**Comment by YegorKandziuba** [comment]
Исправлено
