### ISSUE TITLE
Карта: Лишний переключатель в капитанской.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1222]
**Название:**
`window tint control`

**Дополнительная информация:**
Просто лишний переключатель, висящий на стуле в капитанской.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167505517443289150)

**Comment by YegorKandziuba** [comment]
Исправлено
