### ISSUE TITLE
Карта: Неработающие лестницы, которые не лестницы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1223]
**Название:**
`wooden floor (лестница)`

**Дополнительная информация:**
Лестницы на третьей палубе, ведущие прямо в камеру РАСТ, но это не лестинцы, а тайл пола с текстурой лестницы. (Даже перилами ограждены).
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167506399702564946)

**Comment by YegorKandziuba** [comment]
Исправлено
