### ISSUE TITLE
Карта: Нету сейфа в офисе капитана

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1224]
**Название:**
`secure safe`

**Дополнительная информация:**
Капитану некуда складывать свои ОЧЕНЬ важные вещи, т.к. шкафы ломаются обычным тулбоксом.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167507019884929115)

**Comment by YegorKandziuba** [comment]
Исправлено
