### ISSUE TITLE
Баг: Убивающие лестницы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1225]
**Ckey**:
`daviii22`

**Шаги:**
1. Влететь в лестницу, ведущая на палубу ниже
2. Игра не просчитывает тик, когда находишься на лестнице.
3. Игра просчитывает тик, когда ты находишься в open space и кидает тебя на палубу ниже, ломая ноги и кидая в крит.

**Реальное поведение:**
Люди калечатся, если быстро спускаются с лестницы.

**Ожидаемое поведение:**
Люди спокойно ходят вертикально между палубами.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167507998462189618)

**Comment by LordNest** [comment]
Не воспроизводится (починили вместе с оптимизацией)
