### ISSUE TITLE
Карта: Радиация убивает арестантов в бриге.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1226]
**Название:**
`Не знаю`

**Дополнительная информация:**
В камерах нету зоны, защищающая от радиации, из-за чего могут покалечиться люди.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167511202985951343)

**Comment by YegorKandziuba** [comment]
Исправлено
