### ISSUE TITLE
Карта: Неправильно работующая лента(В КАРГО)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1229]
**Название:**
`conveyor switch,conveyor belt`

**Дополнительная информация:**
Неправильное направление мусорной ленты в отделе поставок(Смотреть Фото)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `XomckiyPenguin#6362` / `571614128800661506`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167518204395016235)

**Comment by YegorKandziuba** [comment]
Исправлено
