### ISSUE TITLE
Баг: Слетает выключение хоткеев при клике куда-либо на игровом экране.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#123]
**Ckey**:
`Wolfor by Kot`

**Шаги:**
1.Выключаешь хоткеи на таб
2. Кликаешь куда-то на игровом экране

**Реальное поведение:**
Слетает отключение хоткеев

**Ожидаемое поведение:**
Отлючение хоткеев не должно слетать
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Autodestructionem#1994` / `444155922533842944`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087729963794448474)

**Comment by SuhEugene** [comment]
`Tab` не выключает хоткеи, а лишь фокусит строку ввода команд.
Режим хоткеев включается только через настройки.
