### ISSUE TITLE
Карта: Душ в баре

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1230]
**Название:**
`shower curtains`

**Дополнительная информация:**
Прошу переименование видимо
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167521912570793984)

**Comment by YegorKandziuba** [comment]
Исправлено
