### ISSUE TITLE
Карта: Аир алярма офиса РД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1231]
**Название:**
`air alarm`

**Дополнительная информация:**
Расположена неверно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167523108333305856)

**Comment by YegorKandziuba** [comment]
Исправлено
