### ISSUE TITLE
Спрайт: Отсутствие текстур

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1234]
**Название:**
`Текстура консоли шатла карго, консоли энергии в НСВ Хорризон, отсутсвие текстуры ИКСа ЛЭКа`

**Дополнительная информация:**
Вместо тектстур объектов, таких как текстура консоли шатла карго(внутри дрона), консоли энергопитания на НСВ Хорризон(арктический планетойд) и ИКСа ЛЭКа, выдаётся лишь красный круг внутри с красным треугольником. Так же помимо этого текстуры камней имеющие внутри себя археологический объект или по неизвестной причине меняют свою текстуру на "нот сэйв зоне"
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167600571956613180)

**Comment by SuhEugene** [comment]
Вот бы кто на оффбэй зарепортил ммммммммммммм

**Comment by SuhEugene** [comment]
И вообще это /репорт спрайт

**Comment by LordNest** [comment]
Так я это уже пофиксил когда. Не всё, но отдельно на карты репорты остались.
