### ISSUE TITLE
Карта: Неправильно названы шлюзы в экспедиторской

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1241]
**Название:**
`Expedition Prep`

**Дополнительная информация:**
Шлюз ведет к шкафам карго. Выше расположенный шлюз, ведущий к шкафам ЭК, не назван вообще.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `imony.` / `425720135370801162`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1167833784171892796)

**Comment by YegorKandziuba** [comment]
Уже было исправлено ранее
