### ISSUE TITLE
Карта: Доступ АВД в медблок

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1250]
**Название:**
`Internal Affairs Agent'`

**Дополнительная информация:**
Добавить уже наконец-то доступ для АВД в медблок. Хоть в приёмную!
<hr>

*Репорт сгенерирован автоматически*
*Автор: `semonic` / `361140847682781186`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1168237567578218516)

**Comment by SuhEugene** [comment]
Отказ. АВД не нужен доступ в медблок и в его критическое крыло.
