### ISSUE TITLE
Карта: Дать доступ АВД в офис снабжения

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1251]
**Название:**
`Supply office`

**Дополнительная информация:**
Ну тупа доступ в эту зону. Не столь критичная вещь.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `semonic` / `361140847682781186`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1168239431266877460)

**Comment by SuhEugene** [comment]
Отказ. АВД не нужен доступ карго.
