### ISSUE TITLE
Старый спрайт: reagent sublimator

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1258]
**Объект:**
reagent sublimator

**Название:**
`reagent sublimator`

**Дополнительная информация:**
reagent sublimator в атмосферном не имеет спрайта, если он стоит где то еще то и соответственно там тоже
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lisikohoro` / `455436205740261376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1168429194485694495)

**Comment by LordNest** [comment]
Дубликат #935
