### ISSUE TITLE
Механ: Deepmaints Event

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#126]
**Название:**
`/datum/event/deepmaint`

**Дополнительная информация:**
Ивент отсутствует в ивент-панели, также данный ивент не запускается корректным образом: при его триггере через Debug Verbs происходит срабатывание его прекращения. Вероятнее всего требуется включить карты дипмеинтс в файл подгрузки Сьерры.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LordNest#5211` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087734996833423430)

**Comment by ImJustKisik** [comment]
Пофиксят на оффах

**Comment by LordNest** [comment]
КУДА
До тех пор, пока не пофикшенно, то не будет закрыто

**Comment by ImJustKisik** [comment]
Замерджились 
https://github.com/Baystation12/Baystation12/pull/33157

**Comment by LordNest** [comment]
А вот и ничего и не помогло. Ивента нет в ивент панели, а при попытке педально триггернуть он завершается сразу же с исходом "Всё закончилось". Переоткрываю ивент.

**Comment by SuhEugene** [comment]
Они же вроде это убили, да?

**Comment by ImJustKisik** [comment]
> Они же вроде это убили, да?

Да, всё убили. Теперь этого нет, потому что оно работает плохо

**Comment by SuhEugene** [comment]
Ивент убили. Неактуально.
