### ISSUE TITLE
Баг: Проблемы с прогревом топлива

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1266]
**Название:**
`Кнопки Nacelle Fuel Control, трубы в зонах Nacelle`

**Дополнительная информация:**
В камеры сгорания (в зонах Nacelle) не идёт водород и кислород, подача не управляется кнопками в инжерке. Скрины будут ниже
<hr>

*Репорт сгенерирован автоматически*
*Автор: `ppetros` / `334264197556731916`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1168878967651041340)

**Comment by YegorKandziuba** [comment]
Кнопки /obj/machinery/button/toggle/valve/nacelle и её наследующиеся не работают с вентилями в камерах сгорания топлива.

**Comment by LordNest** [comment]
Карта ишшуй. Закрыто
