### ISSUE TITLE
Объект: Некоторые нательные метки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#127]
**Объект:**
Некоторые нательные метки

**Название:**
`Bodyhair, Warpaint, Greatbrows`

**Дополнительная информация:**
Это не все пропавшие метки, так что список будет пополняться по ходу действия
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LoL, No Username#6444` / `508677373559046195`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087737093263994900)

**Comment by LordNest** [comment]
Пофикшено Сурвом
