### ISSUE TITLE
Старый спрайт: Кабинет ЛЭКа

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1274]
**Объект:**
Кабинет ЛЭКа

**Название:**
`heavy exploration HCM`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tetesnik` / `934486199492550776`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169523682989854721)

**Comment by LordNest** [comment]
Дубликат #1217
