### ISSUE TITLE
Механ: При спавне ИИ нет выбора озвучки анонса его появления

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#128]
**Название:**
`ИИ и спавн за него.`

**Дополнительная информация:**
Когда заходишь на ИИ на старосыре даёт выбор озвучки, ТГ или Торч, на новосыре такого нет, надо вернуть. 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Werewolfen#2941` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087737436995584031)

**Comment by SuhEugene** [comment]
Экстренным сбором экспертов было решено, что голос у анонсов непрятностей на корабле и голос объявления ИИ должны совпадать

Каутиночка: ![image](https://user-images.githubusercontent.com/32931701/229299186-682ce1d5-98cf-49e8-82f6-b6603f1d2f80.png)
