### ISSUE TITLE
Старый спрайт: Формальные брюки с рубашкой

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1280]
**Объект:**
Формальные брюки с рубашкой

**Название:**
`formal shirts with pants`

**Дополнительная информация:**
Вместо собственно комплекта из брюк и рубашки игра предлагает выбирать из полноценных костюмов, полностью идентичных тем, что предлагаются в clothes selection
<hr>

*Репорт сгенерирован автоматически*
*Автор: `uedcommander` / `200682967775969280`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169875806319820820)

**Comment by LordNest** [comment]
#Не_баг_а_фича
