### ISSUE TITLE
Баг: Отсутствует причёска под названием "Mancut"

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1288]
**Ckey**:
`Molbertich`

**Шаги:**
1. Пытаться найти причёску "Mancut" при создании персонажа
2. Не найти и разочароваться

**Реальное поведение:**
Причёска "Mancut" вовсе отсутствует и не может использоваться при создании персонажа.

**Ожидаемое поведение:**
Причёска должна была быть в списке доступных для выбора.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169899624870457416)

**Comment by LordNest** [comment]
Сурв починил
