### ISSUE TITLE
Баг: Сложности с лодаутом

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1291]
**Ckey**:
`GeroZer0`

**Шаги:**
1. покликать в лодауте 
2. словить миллион ошибок

**Реальное поведение:**
Кидает ошибки

**Ожидаемое поведение:**
Работает без скриптовых ошибок
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169941518304432198)

**Comment by LordNest** [comment]
Рантаймы закрывали, это я помню.
