### ISSUE TITLE
Баг: У электропака в рнд нет текстурки.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1292]
**Ckey**:
`Baneuus`

**Шаги:**
1. Залететь в рнд.
2. Зайти в зону с канистрами
3. Увидеть

**Реальное поведение:**
Иконки нет

**Ожидаемое поведение:**
Должна быть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169942001265938533)

**Comment by SuhEugene** [comment]
Дубликат
