### ISSUE TITLE
Старый спрайт: Стол для блэкджека

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1305]
**Объект:**
Стол для блэкджека

**Название:**
`blackjack table, craps table`

**Дополнительная информация:**
Стол для блэкджека выглядит плохо, как будто простыня на обычном столе, craps table тоже. Скрин в ветке
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169971539807043618)

**Comment by LordNest** [comment]
Не в приоритете совсем. 
После релиза ждём дубля и с ним работаем
