### ISSUE TITLE
Карта: Во всех четырех двигательных отсеках сыра зеленые трубы идут в никуда.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1308]
**Название:**
`pipe (Scrubber to supply pipe)`

**Дополнительная информация:**
Трубы стоит либо удалить, либо подключить к чему-то. (скрин в ветке)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vvista` / `603154227447201802`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169974699472728166)

**Comment by YegorKandziuba** [comment]
Все в порядке, там трубы под полом идут
