### ISSUE TITLE
Механ: ППТ не показывает температуру.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1314]
**Название:**
`вкладка status`

**Дополнительная информация:**
На Сьерре при игре на ППТ можно было посмотреть температуру то ли ММИ, то ли мозга во вкладке status. Эта штука была удобной и полезной. Тут этой штуки нет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `геймер413#8620` / `829363002758266912`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1169998268839772194)

**Comment by LordNest** [comment]
Относится к ПРу [Сooling organ for IPCs #587](https://github.com/ss220-space/Baystation12/pull/587)
Ждём от авторов переноса на Бей12 или модуляризации

**Comment by Lexanx** [comment]
Уже неактуально

**Comment by LordNest** [comment]
Исправлено на Бее
