### ISSUE TITLE
Баг: Фото делают снимки ужасов.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#132]
**Ckey**:
`Werewolfen`

**Шаги:**
1. Взять фотик
2. Сделать снимок любого объекта или двери

**Реальное поведение:**
Все объекты вещей - чёрные. Двери - криво как в СДММ.

**Ожидаемое поведение:**
Нормальное отображение всех объектов на фото. (Скрины прилагаются)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Werewolfen#2941` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087741708990677153)

**Comment by ImJustKisik** [comment]
@SuhEugene 93f1af764d880b5a21fc3c22843f6fba79c31f9d 
Фотоаппарат использует getFlatIcon - который трогал последним ты вот в этом ПРе
