### ISSUE TITLE
Баг: Невозможно зайти за роли авейки (ICCG Pioneer Corps Recon Craft)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1320]
**Ckey**:
`Molbertich`

**Шаги:**
1. Создать необходимого по возрасту персонажа для авейки.
2. В меню "Join" выбрать соответствующую роль на авейке.

**Реальное поведение:**
Спавн за выбранную роль не происходит, в чат выдаётся сообщение "Your character's in-game age is too low for this job." независимо от возраста персонажа.

**Ожидаемое поведение:**
Спавн за выбранную роль.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170023284344107008)

**Comment by LordNest** [comment]
Так, а вот тут стоять, тут нужно проверить нашаманил ли Канджи с возрастом @YegorKandziuba работаем.

**Comment by LordNest** [comment]
Всё нормально в #1400 пофиксил
