### ISSUE TITLE
Баг: Отображение чужих персонажей в меню настройки персонажа в лобби до начала раунда

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1321]
**Ckey**:
`Alexander_Konrad`

**Шаги:**
1. Зайти до начала раунда в игру, с онлайном в 20+
2. Открыть настройщик персонажа
3. Часто понажимать кнопку Resize

**Реальное поведение:**
Вместо моего персонажа с моим снаряжением, я вижу чужих персонажей с их снаряжением.

**Ожидаемое поведение:**
Я должен видеть только своего персонажа.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gentelman` / `225563403102453760`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170035107021729882)

**Comment by LordNest** [comment]
Закрываем по причине полной переработки лодаута #1853
