### ISSUE TITLE
Объект: Вокс-перчатки, вокс-робы, вокс-одежда.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1324]
**Объект:**
Вокс-перчатки, вокс-робы, вокс-одежда.

**Название:**
`Alien clothes, alien robes`

**Дополнительная информация:**
Из лодаута пропали воксо-вещи, кроме маски.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170039993645940799)

**Comment by LordNest** [comment]
Воксы выпилены с Либерии, у прочих воксов эти вещи есть на карте
