### ISSUE TITLE
Баг: Баг На СьерраБей инструменты из инженерного импланта не крепятся к руке

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1329]
**Ckey**:
`Kradrex`

**Шаги:**
1. Встатавить себе протез инструментов
2. Нажать Q

**Реальное поведение:**
Инструменты в имплантах не крепятся к руке и их можно выкидывать или кидатся ими

**Ожидаемое поведение:**
Они должны оставатся в руке
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kradrex` / `378560237818478592`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170048892918841394)

**Comment by LordNest** [comment]
Бей отказался фиксить такой же ишшью с армблейдом НО тут инструменты не доступны отдельно. @Reishi42 думаю что вот это они таки пропустят, потому что тут идёт наследование. Предлагаю залить на Бей.

**Comment by Reishi42** [comment]
> Бей отказался фиксить такой же ишшью с армблейдом НО тут инструменты не доступны отдельно. @Reishi42 думаю что вот это они таки пропустят, потому что тут идёт наследование. Предлагаю залить на Бей.

Ты имеешь ввиду такой же фикс как я предлагал бэйцам, только для инженерного?

**Comment by Reishi42** [comment]
Закинул решение на офы:
https://github.com/Baystation12/Baystation12/pull/34312

**Comment by LordNest** [comment]
Fixed in #1447
