### ISSUE TITLE
Баг: ноутбук не поворачивается к персонажу, и при закрытии багуется экран.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1330]
**Ckey**:
`Albert Dromund`

**Шаги:**
1. открываешь ноут
2. ноут открывается и остается стоять к тебе боком
3.  закрываешь ноут
4. ноут закрывается а экран от ноута остается пока ты не положишь его в рюкзак, как багованный спрайт.

**Реальное поведение:**
описал выше

**Ожидаемое поведение:**
в теории ноут должен закрываться без задержек и багованых спрайто, а также поворачиваться к персонажу.в
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170054709495746721)

**Comment by LordNest** [comment]
Это нужно выдавать на Бей12 потому что проблема с отсутствием спрайта с их стороны, а финиковские дефолтные спрайты они забраковали. Нужен инициативный человек, который ещё раз зальёт спрайты на Бей12 и убедит их в том, что оно смотрится хорошо.
