### ISSUE TITLE
Баг: Не появляется панель аксессуаров при снятии

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1331]
**Ckey**:
`Albert Dromund`

**Шаги:**
1.  Надеваешь несколько аксессуаров на себя
2. Хочешь снять один
3. Кликаешь на кнопку ремув аксессуар, и она не работает
4. работает кнопка на снятие всех аксессуаров и все.

**Реальное поведение:**
ничего не снимается, только через снятие всех аксессуаров можно как то действовать, окно просто не появляется

**Ожидаемое поведение:**
появится окно с выбором аксессуара, который ты хочешь снять с куклы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170062525660934345)

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/cad7c061-bdff-410a-92af-35f65927b514)
На текущей версии оно не багуется. Закрыто возможно нами, возможно бургами.
