### ISSUE TITLE
Запрос: Неверные аптечки в шкафах ОЗА

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1333]
**Название:**
`стандартные аптечки`

**Дополнительная информация:**
У сотрудников ОЗА в шкафах на корабле лежат обычные аптечки с таблетками парацетамола, таблетками от простуды и бинтами с мазью от ожогов, вместо тактических со следующими инъекторами: 2 с бикардином, 2 с келотаном, 1 трамадол, 1 инапровалин, 1 анти-токсический, 1 анти-рад.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `l___blaze___l` / `227012028101820417`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170073093918703679)

**Comment by LordNest** [comment]
В теории можно выдать что-то со спрайтом Light аптечки как у ЭКшников. Старая аптечка не была введена из-за старого спрайта + отсутствия её как типа в билде. Обсуждаемо.
