### ISSUE TITLE
Старый спрайт: Стандартный шлюз

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1342]
**Объект:**
Стандартный шлюз

**Название:**
`airlock`

**Дополнительная информация:**
При открытии шлюза периодически ломается спрайт последнего фрейма анимации. Не совсем понял принцип, по которому это происходит, но больше всего проявлялось, если напрямую пытаться двигаться через шлюз
<hr>

*Репорт сгенерирован автоматически*
*Автор: `burger_time` / `306510240453492737`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170095052949823569)

**Comment by SuhEugene** [comment]
Пофикшено ровно в момент написания репорта
