### ISSUE TITLE
Старый спрайт: Еда

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1343]
**Объект:**
Еда

**Название:**
`Вся еда со Сьерры`

**Дополнительная информация:**
На Сьерре, спрайты еды выглядят лучше и интереснее, предлагаю, если есть возможность, заменить спрайты еды на Сьерровские, где это возможно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170103982660800614)

**Comment by LordNest** [comment]
Ладно, это будет риторический вопрос. 
Большинство спрайтов одинаковые, остальные или улучшены, или заменены нейтрально. 
Закрываю.
