### ISSUE TITLE
Старый спрайт: Атмосферный отсек

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1344]
**Объект:**
Атмосферный отсек

**Название:**
`reagent sublimator`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tetesnik` / `934486199492550776`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170263262089187329)

**Comment by LordNest** [comment]
Дубликат #935
