### ISSUE TITLE
Карта: Не рабочий СМ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1346]
**Название:**
`power storage unit`

**Дополнительная информация:**
Не работает СМЕС, он выглядит как спрайт с ним невозможно взаимодействовать.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tetesnik` / `934486199492550776`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170268714386608128)

**Comment by LordNest** [comment]
Смешное: нужно ждать пока Спукертон допилит свой ПР на прозрачный космос
Так что пока ин Раст ви траст
