### ISSUE TITLE
Карта: Летающие лампы.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1350]
**Название:**
`spotlight`

**Дополнительная информация:**
В ангаре на стенах установлены лампы. Но из-за опен спейса на палубе выше, эти лампы тоже отображаются, хотя по идее не должны.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170285738663886858)

**Comment by LordNest** [comment]
В ангаре - не ишшуй. В лифтах и на лестницах - ишшуй.
