### ISSUE TITLE
Баг: Нельзя прикрепить бумагу к стене скотчем

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1352]
**Ckey**:
`Vipo24`

**Шаги:**
1. Жмак скотчем по бумаге
2. Жмак бумагой со скотчем по стене

**Реальное поведение:**
Бумага падает на пол у стены со звуком приклеивания скотчем

**Ожидаемое поведение:**
Бумага на стене
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170287720367665282)

**Comment by LordNest** [comment]
Не воспроизводится. 
Пулл по стенкам - геймдизайн
