### ISSUE TITLE
Баг: Донат без доната ломает сервер

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1356]
**Ckey**:
`GeroZer0`

**Шаги:**
1. Зайти в лодаут, взять донат штуку
2. Зайти в раунд, сломать раунд

**Реальное поведение:**
Много эроров у админа, мы не можем ходить

**Ожидаемое поведение:**
Донат не берется и не ломатеся
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170313336622157884)

**Comment by LordNest** [comment]
Закрываем по причине полной переработки лодаута #1853
