### ISSUE TITLE
Баг: Медицинские сенсоры нееккоретно отображают положение персонажей на судне

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1357]
**Ckey**:
`LisikoHoro`

**Шаги:**
1. Включить планшет\консоль.
2. Скачать программу сенсоров.
3. Включить программу сенсоров.
4. Переключить в просмотр местоположения по карте.
5. Понять, что все точки отображающие персонажей съехали вниз и лево.

**Реальное поведение:**
Не там показываются точки блять

**Ожидаемое поведение:**
Точки на карте указывающие местоположения персонажей на судне показываются там где надо
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lisikohoro` / `455436205740261376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170314594812702790)

**Comment by LordNest** [comment]
Нужно нашаманить с размерами окна, займусь завтра

**Comment by LordNest** [comment]
SierraBay12\nano\images\sierra
Вот по этому пути лежат изображения, если кто-то кроме меня будет разгребать это всё.
