### ISSUE TITLE
Механ: Кнопка E не кидает вещи в сумку

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1359]
**Название:**
`grey satchel???`

**Дополнительная информация:**
На Сиерре можно было кидать вещи в инвентарь(сумку) через Е, сейчас оно раскидывается только в карманы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170319091496656906)

**Comment by LordNest** [comment]
Я же вас всех закрывал, сколько ещё вас таких тут раскидано?
