### ISSUE TITLE
Баг: Черная помада нельзя положить на стол или в сумку в закрытом виде

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1360]
**Ckey**:
`Distress`

**Шаги:**
1. Взял черную помаду из лодаута и нажать реди вначале раунда.
2. Заспавниться. 
3. Использовать помаду на себе. 
4. Закрыть колпачок помады и попытаться положить помаду в сумку или на стол

**Реальное поведение:**
Пишет, что нужно открыть колпачок помады

**Ожидаемое поведение:**
Закрытая помада должна была прекрасно лечь в сумочку или положиться на стол
<hr>

*Репорт сгенерирован автоматически*
*Автор: `distressik` / `705397125936054274`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170319268043292675)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/160ae0ce-33aa-4363-ac3d-6ef5c74744c9)

Пофикшено на апстриме когда-то в декабре
