### ISSUE TITLE
Баг: Не пускает ни на одну роль патруля по причине возраста.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1361]
**Ckey**:
`Kkfssjgadgh`

**Шаги:**
1. Настроить кукле любой возраст.
2. Попытаться зайти на патруль.
3. Разочароваться.

**Реальное поведение:**
При любом возрасте куклы пишет что Your character's in-game age is too low for this job.

**Ожидаемое поведение:**
Ты должен был зайти за роль патруля.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kekei9470` / `714874058654613545`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170320442196770959)

**Comment by LordNest** [comment]
я это правил в #1400
