### ISSUE TITLE
Баг: В баре гбс не падает на первый этаж и не получает урона

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1363]
**Ckey**:
`Albert Domund`

**Шаги:**
1. перелез через стойку второго этажа
2. не упал
3. поползал по воздуху вернулся

**Реальное поведение:**
не падает на пол первого этажа

**Ожидаемое поведение:**
Следом за мной улетел человек и он разбился, а гбс хоть бы хны, и он даже не провалился.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170324012874874960)

**Comment by LordNest** [comment]
Ксенком сказал что фича. Значит будет фича.
