### ISSUE TITLE
Объект: Многие штампы, логотипы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1368]
**Объект:**
Многие штампы, логотипы

**Название:**
`[sierralogo] [ccalogo] как примеры`

**Дополнительная информация:**
Для заполнения документов можно было использовать лого, лого больше нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170330267211276290)

**Comment by LordNest** [comment]
Это оверрайдить нужно, мне пока лень, там прок один буквально
