### ISSUE TITLE
Объект: Отслеживающий маяк

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1369]
**Объект:**
Отслеживающий маяк

**Название:**
`tracking beacon`

**Дополнительная информация:**
Его нет на корабле, его нельзя сделать в протолате.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `l___blaze___l` / `227012028101820417`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170330507616206880)

**Comment by LordNest** [comment]
В темноте не тот маяк потеряли
