### ISSUE TITLE
Карта: Декалей слишком много и они слишком навязчиво отвлекают на себя внимание

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1374]
**Название:**
`deck?`

**Дополнительная информация:**
Декалей на карте слишком много, из-за чего визуально воспринимать информацию с экрана неудобно.

Обычно фон делается либо однотонным, либо с повторяющимся узором (шахматы, в ромбик - как угодно), декали в отсеках же имеют разную толщину и не имеют паттерна, как такового - они просто рандомно обтекают объекты в отсеке и перед глазами создаётся мешанина.

Я бы заменил декали на менее броские (как в коридорах, например), либо полы на более однотонные (плитка, плитка в шахматы, что угодно)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `ratatet` / `186559014581043202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170337473293996152)

**Comment by YegorKandziuba** [comment]
Отмена запроса. Это новый дизайн к которому просто стоит привыкнуть.
