### ISSUE TITLE
Баг: Если прикрутить вентиляцию на пол с проводом, то спрайт пропадёт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1375]
**Ckey**:
`DeadGame`

**Шаги:**
1. Напечатать вентиляцию
2. Прикрутить его на пол с проводом
3. Смотреть на трубу без вентиляции

**Реальное поведение:**
Спрайт пропадает при прикручивании вентиляции

**Ожидаемое поведение:**
Он должен остаться не смотря на провода
<hr>

*Репорт сгенерирован автоматически*
*Автор: `deadgameofficial` / `314788151627612160`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170338609828737024)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/83f2b7ac-fe90-4db2-885a-5fa4701ca58c)
Не воспроизводится.
