### ISSUE TITLE
Карта: Спавн дронов в крио отсеке у бара

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1376]
**Название:**
`???`

**Дополнительная информация:**
В зоне спавна игроков, так же спавнятся дроны
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170339515873902593)

**Comment by LordNest** [comment]
НЕ
ДОЛЖНО
ВОСПРОИЗВОДИТЬСЯ
