### ISSUE TITLE
Баг: Не могу удалить консоль использую Билд мод и кнопку Delete

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1379]
**Ckey**:
`KandJX`

**Шаги:**
1. Заспавнить консоль /obj/machinery/computer/ship/disperser/military 
2. Нажать ПКМ
3. Нажать Delete

...
2. Нажать Тогл Билд мод
3. Нажать ПКМ по консоле

**Реальное поведение:**
Не удаляется

**Ожидаемое поведение:**
Должно удалиться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kandjx` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170343879258669066)

**Comment by LordNest** [comment]
педаль ишшуй. 
не воспроизводится на локальном тесте.
