### ISSUE TITLE
Старый спрайт: Раковина

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#138]
**Объект:**
Раковина

**Название:**
`sink`

**Дополнительная информация:**
Спрайт раковины неправильный, если она повернута на север, то отображается в центре тайла. В обсуждении скрины.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087746006482964531)

**Comment by cuddleandtea** [comment]
На новой карте от Канжда стейты исправлены и данная ошибка отсутствует

**Comment by cuddleandtea** [comment]
На новой карте от Канжда стейты исправлены и данная ошибка отсутствует
