### ISSUE TITLE
Объект: /obj/item/sealgen_case

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1381]
**Объект:**
/obj/item/sealgen_case

**Название:**
`/obj/item/sealgen_case`

**Дополнительная информация:**
Его нет, он должен быть. Без него игру игроки уже не могут представить.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kandjx` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170346582944776223)

**Comment by LordNest** [comment]
Who are you? Casual? 
What rings you got?
