### ISSUE TITLE
Старый спрайт: Facial hair и нательные метки для ящеров

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1382]
**Объект:**
Facial hair и нательные метки для ящеров

**Название:**
`Spine Spikes, Bands на руки, Tiger Head и прочее из двух разделов.`

**Дополнительная информация:**
Лицевой растительности на сырбее у ящеров вообще нету, хотя на нашем бее есть доп. рога и ирокез. Насчет меток - некоторые отображаются криво, но например Bands на руках и Tiger Head выглядят очень неплохо. Хотелось бы этот минимум вернуть, который не требует переделки спрайта, а лишь переноса.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170347283565531246)

**Comment by LordNest** [comment]
А нормально закрывать будет Александр Сергеевич Пушкин, ага.
