### ISSUE TITLE
Баг: Ходьба зигзагом куда быстрее прямой ходьбы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1383]
**Ckey**:
`Failu`

**Шаги:**
1. Попробовать пройтись/пробежать по прямой только на север/юг/запад/восток
2. попробовать пройтись уже наискосок — на северо-запад/юго-восток/северо-восток/юго-запад
3. убедиться, что вторым способом идти быстрее.

**Реальное поведение:**
Идти по прямой медленно, что неудобно

**Ожидаемое поведение:**
ходьба/бег по прямой и наискосок должны быть одинаковы по скорости
<hr>

*Репорт сгенерирован автоматически*
*Автор: `karcodd` / `923184606415568957`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170348067560620034)

**Comment by LordNest** [comment]
Исправлено в #1566
