### ISSUE TITLE
Объект: Шкафчик пожарника

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1385]
**Объект:**
Шкафчик пожарника

**Название:**
`firefighting locker`

**Дополнительная информация:**
В шкафчике находятся дуфельбаг, огнетушители, поясок пожарника, маски, костюмы, баллоны и паучи от ожогов
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170356135052714024)

**Comment by LordNest** [comment]
Уже отрабатыаали, оно есть
