### ISSUE TITLE
Баг: Вылезает название аир алярмы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#139]
**Ckey**:
`furior`

**Шаги:**
1. Проснуться в крио
2. Выйти из комнаты
3. Посмотреть на алярму

**Реальное поведение:**
Название алярмы в ее меню очень большое и вылезает за пределы места, отделенного под него

**Ожидаемое поведение:**
Текст должен быть мельче по шрифту, либо место под название должно быть шире(имхо и то и то надо)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Furior#9776` / `346586265602228226`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087747263624904775)

**Comment by Atufancheg** [comment]
исправлено в https://github.com/Atufancheg/SierraBay12/commit/91a283c7a521282ac438e0260169f6c603528166

**Comment by SuhEugene** [comment]
Здесь речь про воздушную алярму. Не исправлено.
