### ISSUE TITLE
Старый спрайт: Supply Drone Virtual Intelligence

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1390]
**Объект:**
Supply Drone Virtual Intelligence

**Название:**
`Supply Drone Virtual Intelligence`

**Дополнительная информация:**
Не имеет спрайта, а лишь знак ошибки
<hr>

*Репорт сгенерирован автоматически*
*Автор: `deadgameofficial` / `314788151627612160`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170363035261616239)

**Comment by LordNest** [comment]
Я же тебя закрыл, штука
