### ISSUE TITLE
Механ: Не работает радио

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1391]
**Название:**
`shorwave radio`

**Дополнительная информация:**
радио не работает вообще, ни в каких режимах и ни на каких частотах, ни на приём, ни на отправку
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vuradu.` / `287836634211155968`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170366195187335200)

**Comment by LordNest** [comment]
Проверить, если воспроизводится то какая-то нездоровая хуйня

**Comment by SuhEugene** [comment]
Я починил, но не отметил как завершённое
