### ISSUE TITLE
Баг: Неправильная иконка scanning module в контекстном меню

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1394]
**Ckey**:
`Mad Cat-Lon`

**Шаги:**
1. Найти scanning module (можно в НИО, на столе в РНД).
2. Нажать ПКМ, вызвав контекстное меню

**Реальное поведение:**
Вместо иконки scanning module показывается иконка circuit debugger

**Ожидаемое поведение:**
В контекстном меню должна быть иконка scanning module, а не circuit debugger
<hr>

*Репорт сгенерирован автоматически*
*Автор: `madcatlon` / `366704953999360000`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170383524684111932)

**Comment by LordNest** [comment]
Обращайтесь этому, как его... забыл короче. 
Мы на движке которому больше 20 лет, это норма.
