### ISSUE TITLE
Баг: Энергомачете скреллов не может пилить болты.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1396]
**Ckey**:
`Baneuus`

**Шаги:**
1. Зайти за скреллов.
2. Взять энергомачете.
3. Попытаться раздолбить шлюз на болтах.

**Реальное поведение:**
Болты не пилятся.

**Ожидаемое поведение:**
Должны пилиться, как от есворда.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170404109808058408)

**Comment by LordNest** [comment]
Не баг, а фича
