### ISSUE TITLE
Карта: У обычного учёного нет доступ на петров плюс нет контроллера шлюзов пред петровым

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1397]
**Название:**
`дверь петрова и скорее всего остальные тоже, а так же контроллер между шлюзами, он находится вне.`

**Дополнительная информация:**
ну я в целом описал. контроллер надо переместить дабы не сдохнуть, плюс дверям петрова дать доступы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170405047906078853)

**Comment by LordNest** [comment]
Да починил я ваш Петров. Откуда вообще берутся эти иссуи?
