### ISSUE TITLE
Баг: Невозможно поставить самому себе имплант (Arm Blade)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1398]
**Ckey**:
`Reishi42`

**Шаги:**
1. Купить имплант
2. Принять парацетамол (2 таб)
3. Начать ставить имплант сидя на стуле
4. Увидеть что происходит провал

**Реальное поведение:**
Невозможно без серьёзно медицинской подготовки поставить имплант

**Ожидаемое поведение:**
До перехода было достаточно двух таблеток парацетамола для установки себе трейторского импланта без тяжёлых последствий
<hr>

*Репорт сгенерирован автоматически*
*Автор: `reishi.` / `194213487843475457`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170413691112538122)

**Comment by LordNest** [comment]
Закрываю ишшуй, поясняю почему:
* Фейл операции идёт если держать автодок в руке, которую оперируют, что ведёт к кровопотери и гостчату
* Крик во время операции есть, но, как говорится "капу в рот", у тебя есть буквально tape roll чтобы делать mmm вместо крика или muzzle если мсье знает толк в извращениях. 
* Безопасная операция = игра на доверие с доктором. Играйте в социалочку как никак. 
 
 Итого: ждём начала полноценных отыгрышей раундов с активным использованием предмета. Если будет совсем невмоготу, то будем менять циферки
 Если потерпят, то потерпят.
