### ISSUE TITLE
Запрос: Протезы на ящерах.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1402]
**Название:**
`Adjust Limbs`

**Дополнительная информация:**
Ящеры могут ставить протезы в сетапе. На сыре такую функцию вырезали. Надо ли ее вырезать с сырбея? Можно ли ставить протез в самом раунде не знаю.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170465852328517772)

**Comment by LordNest** [comment]
Голосование решило что фича
