### ISSUE TITLE
Механ: Взлом пода

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1403]
**Название:**
`neznayou`

**Дополнительная информация:**
На сьерре можно было кликнуть емагом на под и улететь на нём, а тут он просто открывается, но возможности улететь нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `_killer2010_sniper_assasin_1337_` / `326741969319624704`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170476574781472918)

**Comment by LordNest** [comment]
Дубликат #1355
