### ISSUE TITLE
Карта: Не работает шаттл на скреллшипе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1404]
**Название:**
`SSV Shuttle`

**Дополнительная информация:**
Шаттл скреллшипа не может вылететь на овермапу.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `helsog` / `168599447452778496`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170486351129489448)

**Comment by SuhEugene** [comment]
На оффах та же беда:
- #34308
