### ISSUE TITLE
Карта: На КПП ОЗА возле НИО старый шкаф СБ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1406]
**Название:**
`security officer's locker`

**Дополнительная информация:**
Старый шкаф имеет в себе устарелые вещи как для СБ. И по факту он не нужен.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `honkemo` / `598615241185689661`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170553926538514482)

**Comment by LordNest** [comment]
Не ишшуй, а фича. Он имеет в себе наушник для координации с научкой и эквип чтобы триторы/рева выносили.
