### ISSUE TITLE
Механ: Батарея ППТ имеет всего-то 1000 заряда.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1408]
**Название:**
`Батарея ППТ`

**Дополнительная информация:**
На билде инфинити, батарейка у ППТ держала 3000, сейчас же у них батарейка 1000, так и должно быть? Если да - то жутко неудобно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `honkemo` / `598615241185689661`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170562539545968651)

**Comment by LordNest** [comment]
Да, так и должно быть. Нерфим аниме киберпсихов. Расход батареи в целом стал меньше. Правки механа требуют обсуждения в теме форума с ВЛом ППТ (доступен миньонам). Пока что без ВЛа - только 1к батарейка.
