### ISSUE TITLE
Карта: Трава вылезла.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1410]
**Название:**
`За грани дозволеного!`

**Дополнительная информация:**
У вас тайлы травы вылезли за пределы тайла. Выглядит не эстетично.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `honkemo` / `598615241185689661`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170566021392912486)

**Comment by cuddleandtea** [comment]
https://github.com/Baystation12/Baystation12/pull/34329
