### ISSUE TITLE
Старый спрайт: блок руды

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1413]
**Объект:**
блок руды

**Название:**
`фиг знает могу скрин лать`

**Дополнительная информация:**
на орбитальной станции в месте копание руды массово отсутствуют спрайтики видно через мезонки
<hr>

*Репорт сгенерирован автоматически*
*Автор: `funnyalpha` / `464853362148638720`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170633623620300801)

**Comment by LordNest** [comment]
Так как возможно есть корреляция с подтипами руды, то берём #1670 в работу. Этот закрываем.
