### ISSUE TITLE
Старый спрайт: оверлей космоса

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1414]
**Объект:**
оверлей космоса

**Название:**
`ай Донт кнов`

**Дополнительная информация:**
оверлей темного космоса затемняет Шатл с лампочками
<hr>

*Репорт сгенерирован автоматически*
*Автор: `funnyalpha` / `464853362148638720`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170637911817986138)

**Comment by LordNest** [comment]
Не удаётся установить точно суть проблемы. Если это касается опен спейса снаружи Сьерры, то здесь стоит подождать ПРа Спукертона. Пока что это закрывается.
