### ISSUE TITLE
Объект: Инопланетный артефакт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1416]
**Объект:**
Инопланетный артефакт

**Название:**
`alien artifact`

**Дополнительная информация:**
На Петрове, как было на прошлой Сьерре, с начала раунда появлялось 2 (!) alien artifact'а, каждый находящийся в anomaly container. На Петрове СБэя, как я понял, этих артефактов нет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `madcatlon` / `366704953999360000`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170653626591612929)

**Comment by LordNest** [comment]
Сделал я это
