### ISSUE TITLE
Механ: Нет Доступа на Петров у РД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1418]
**Название:**
`Нет Доступа на Петров у РД`

**Дополнительная информация:**
Нет Доступа на Петров у РД так же и к шлюзам Visitors
<hr>

*Репорт сгенерирован автоматически*
*Автор: `.bord` / `194199285083013120`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170669073521201233)

**Comment by LordNest** [comment]
Проблема со стыковкой самого Петрова, а не с доступами на нём.
