### ISSUE TITLE
Баг: Кнопки от бластдурс ИИ Аплоад и Киборг Аплоад напутаны

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1419]
**Ckey**:
`Lexanx`

**Шаги:**
Нажать на кнопку у ИИ аплоада, откроется бластдур у Киборг Аплоада.
Бонусом там нет камер, почему то

**Реальное поведение:**
Кнопки для ИИ аплоад нет. 2 Кнопки для открытия бластдур к Киборг аплоаду

**Ожидаемое поведение:**
Аплоад ИИ должен иметь нормально настроенную кнопку
<hr>

*Репорт сгенерирован автоматически*
*Автор: `.bord` / `194199285083013120`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170673100963197050)

**Comment by LordNest** [comment]
У Е Б А Т Ь за репорт по карте без тега карты
ЫЫЫА

**Comment by LordNest** [comment]
@YegorKandziuba ты гей

**Comment by YegorKandziuba** [comment]
@LordNest от гея слышу
