### ISSUE TITLE
Карта: Спрайт БСД с НовоСыра слишком толстый, перекрывает венты.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#142]
**Название:**
`Отсек БСД`

**Дополнительная информация:**
На скрине видно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Werewolfen#2941` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087751040796991508)

**Comment by cuddleandtea** [comment]
Реми готовит пак машинерии респрайтов, так что Баг не Баг
