### ISSUE TITLE
Механ: Отсуствуют кнопки переключения перчаток/сапог/груди при одевании ИКС.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1421]
**Название:**
`ИКС`

**Дополнительная информация:**
https://i.gyazo.com/acc72e58f4865a31343f06afa349b2f6.png
Только 1 кнопка, для шлема, и всё.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `.bord` / `194199285083013120`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170674179331330049)

**Comment by LordNest** [comment]
@SuhEugene напомни, эту фичу мы решили оставить во избежание абуза ИКСа с армором и прочей ереси?

**Comment by SuhEugene** [comment]
> @SuhEugene напомни, эту фичу мы решили оставить во избежание абуза ИКСа с армором и прочей ереси? 

Если оффы сделали ток для шлема, значит есть причина. Я лично не помню обсуждения этой темы, как абуза. Я точно помню что надо кодить привязку определённых приколов на определённые части тела, а это надо опять же или оффам впарить, или в кор код посрать, так ещё и в принципе накодить по-умному.

**Comment by LordNest** [comment]
Если оффы сделали, значит есть причина. 
В целом, фича, проблема ИКСа сейчас в том, что ты  просто складываешь его и носишь с ним броню ту же самую, пользуясь преимуществами ИКСа. 
Закрыто. 
Дальнейшие исправления ИКСа через предложку.
