### ISSUE TITLE
Баг: Face Direction без замедления

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#143]
**Ckey**:
`Reevie Core`

**Шаги:**
1. Встаём так, как нам удобно
2. Переходим в IC и нажимаем Face Direction
3. Двигаемся в стороны

**Реальное поведение:**
Персонаж двигается без замедления

**Ожидаемое поведение:**
Персонаж должен двигаться со скоростью Creep
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LoL, No Username#6444` / `508677373559046195`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087751173257310248)

**Comment by cuddleandtea** [comment]
Попытался пофиксить, но не понимаю как в mob.dm поставить ограничение мобу на "бег". Недостаточно опыта
