### ISSUE TITLE
Баг: Проблема со спрайтами штанов (casual pants selection)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1435]
**Ckey**:
`Molbertich`

**Шаги:**
1. Взять любой вид штанов в лодауте casual pants selection (я делал это лишь на хумане).

**Реальное поведение:**
Спрайты любых штанов сломаны, сверху парит красная надпись сообщающая об этом.

**Ожидаемое поведение:**
Никаких проблем со спрайтами.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170757909685223457)

**Comment by LordNest** [comment]
Аналогичная проблема вызванная ониксовским лодаутом
See you, lodout issue...
