### ISSUE TITLE
Баг: Нет анимации работы у мехфабрикатора

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1437]
**Ckey**:
`Shegar`

**Шаги:**
1. Начать печать
2. Не увидеть анимации
3. Поплакать в репорт

**Реальное поведение:**
Нет блять анимации, нахуя дважды спрашивать

**Ожидаемое поведение:**
Должна быть анимации
<hr>

*Репорт сгенерирован автоматически*
*Автор: `am.shegar.` / `1120912972013899786`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1170779738831327382)

**Comment by LordNest** [comment]
Дубликат #1422
