### ISSUE TITLE
Баг: Отсутствует ВЛ на ППТ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#144]
**Ckey**:
`Reevie Core`

**Шаги:**
1. Открываем персонажа
2. Делаем его ППТ
3. Заходим в раунд

**Реальное поведение:**
Мы заходим в раунд

**Ожидаемое поведение:**
Мы не заходим в раунд
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LoL, No Username#6444` / `508677373559046195`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087752701892378665)

**Comment by LordNest** [comment]
Искать **SPECIES_FBP** в коде Инфинити. Это ОЧЕНЬ костыльная вещь, но она работает. Кодить я это конечно же не хочу

**Comment by LordNest** [comment]
Решением старшего ксеномодератора, а также совета поехавших кибердедов, набухавшихся в "Посмертии" Джонни Сильверхендом решено что мы не будем костылить ВЛ на ППТ. 
Имбамехана должно быть меньше, поэтому ВЛ не так актуален.
Всем спасибо, все свободны.
