### ISSUE TITLE
Баг: Спавнпоинт воксов и скреллов не гибкий

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1444]
**Ckey**:
`CuddleAndTea`

**Шаги:**
1. Зайти в игру воксом или скреллом, когда корабль сдвинулся из начальной точки
2. Оказаться в космосе из-за того, что точка спавна не двигается вместе с улетевшим кораблём
У оффов оригинально эта проблема существует, решение нужно посмотреть на лайве, у нас такой ошибки не было.

**Реальное поведение:**
Спавн скрелла или вокса в космосе

**Ожидаемое поведение:**
Спавн на корабле
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1171058882056040448)

**Comment by LordNest** [comment]
Макером всё пофикшено в последнем ПРе.
