### ISSUE TITLE
Запрос: Звук когда вставляешь лампу плохой

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#146]
**Название:**
`light fixture`

**Дополнительная информация:**
Звук когда вставляешь лампу плохой и не подходит, когда вытаскиваешь лампу совершенно нету звуков.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087754033323843735)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
