### ISSUE TITLE
Запрос: Команда рации не понимает кириллицу 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#147]
**Название:**
`Любая рация`

**Дополнительная информация:**
:s рация распознает команду
:ы рация не распознает команду 
На Сыре данная функция была
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087754553283330059)

**Comment by SuhEugene** [comment]
На ребейзе актуально

**Comment by SuhEugene** [comment]
А хотя надо переоткрыть
