### ISSUE TITLE
Запрос: Мерки выглядят слабыми

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#149]
**Название:**
`Аплинк`

**Дополнительная информация:**
Сейчас у мерков на базе из оружия есть: Пистолеты, мех. Из снаряги: Два обычных кримзон ИКСа и два тяжелых. На закусочку четыре ещита. Звучит неплохо для раундстарта, и так и есть. Но с одной оговоркой, это *все* что есть. Аплинка нет. Совсем. Вот ни в каком виде. Это как то совсем слабо, ИМХО, с учетом того что у сб есть слаги и автолат с пушками, не игрушечными.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Shap04ka#9929` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087758237027278948)

**Comment by LordNest** [comment]
Не воспроизводится. При спавне выдаётся радио аплинк. Который выглядит как обычная рация, ага.
