### ISSUE TITLE
Объект: Пропала причёска.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1497]
**Объект:**
Пропала причёска.

**Название:**
`Oxton`

**Дополнительная информация:**
Пропала причёска.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bioplan` / `466070004480081921`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177208324601692210)

**Comment by LordNest** [comment]
Сурв починил
