### ISSUE TITLE
Старый спрайт: Глаза скреллов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1499]
**Объект:**
Глаза скреллов

**Название:**
`Понятия не имею. Это часть куклы.`

**Дополнительная информация:**
Не помню, сообщал ли я раньше, потому напишу. На сбэе и на оффбэе соответственно глаза скреллов по какой-то причине синие. На инфинитибэе это пофиксили и глаза скреллов чёрные, то бишь такие, какими и должны быть. Было бы круто с этим разобраться.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `aventrus` / `186161532311175168`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177276648974983188)

**Comment by LordNest** [comment]
icons\mob\human_races\species\skrell\body.dmi вооот тут нужно поменять на
https://youtu.be/XPNNWHU6Io4?si=uuvTIT41PhjQzU3c
