### ISSUE TITLE
Баг: Некоторых животных всё ещё можно поместить в кобуру

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#150]
**Ckey**:
`The_Hero13`

**Шаги:**
1. Взять животное по типу нимфы дионы/опоссума
2. Нажать на пояс с кобурой/использовать хоткей

**Реальное поведение:**
Животное оказывается в кобуре

**Ожидаемое поведение:**
Очевидно, что такого быть не должно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Aventrus#0855` / `186161532311175168`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087759653754118144)

**Comment by ImJustKisik** [comment]
Я считаю это забавным, даже если кто-то захолстерит TINY_SIZE моба - особого преимущества он не получит.

**Comment by SuhEugene** [comment]
@ImJustKisik ГАЙД ЧИТАЙ БЛЯЯЯЯЯЯЯЯ
