### ISSUE TITLE
Запрос: Отсутствие части мест жительства при выборе происхождения

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1504]
**Название:**
`Часть планет от культурного селектора.`

**Дополнительная информация:**
Отсутствие пунктов места жительства, которые не синхронны с выбором культуры. Так, отсутствует Лорриман, Лордания и прочие.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177548506752360608)

**Comment by LordNest** [comment]
Дубликат #1094

**Comment by SuhEugene** [comment]
#1094 уже сделали, а это не дубликат

**Comment by LordNest** [comment]
Закрыто модом на расширенные культуры
