### ISSUE TITLE
Объект: Шарфы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1505]
**Название:**
`scaf selection`

**Дополнительная информация:**
Пропали два пункта выбора шкафов из пункта Аксесуаров. На лайве: шарфы в полоску и шарфы обычные. Шли двумя пунктами шарфов. На **Сыробее** их нет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177548762286145537)

**Comment by LordNest** [comment]
Шарфы в полоску с фиников добавил как fancy
