### ISSUE TITLE
Объект: Вещи из набора косметики

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1507]
**Объект:**
Вещи из набора косметики

**Название:**
`Почти весь селектор данного пункта`

**Дополнительная информация:**
Пропали вещи из селектора косметики, сейчас там лишь зеркало. На Лайв-сыре набор побольше и включает в себя больше вещей косметического характера.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177549567550570538)

**Comment by LordNest** [comment]
закрыл в #1683
