### ISSUE TITLE
Старый спрайт: Наручные компьютера с пунктами более одного цвета

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1508]
**Объект:**
Наручные компьютера с пунктами более одного цвета

**Название:**
`Wrist computer`

**Дополнительная информация:**
Спрайты в лодауте отображаются не корректно к их названиям и не отображают доп цвета, которые указаны в названиях. К примеру: у СМО белый с голубой полоской - в лодауте просто белый.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177552213544009789)

**Comment by LordNest** [comment]
Оно не фиксится
На самом деле решение проблемы - переспрайтить полностью wrist computer сделав его фиксированных цветов, а не автозаливку спрайта. 
Воооот. 
Кто этим будет заниматься? Загадка. 
Won't Fix
