### ISSUE TITLE
Объект: Целый сборник отсутствующих причёсок причёсок (TM)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1510]
**Объект:**
Целый сборник отсутствующих причёсок причёсок (TM)

**Название:**
`Список в дополнительной информации в связи с количеством.`

**Дополнительная информация:**
80s
80s ponytail
80s ponytail alt
Alien
Amicia
Angel
Antenna Hair
Bangs
Baum
Beyfong
Birdnest
Birdnest 2
Blades hair
Blunt Bangs alt
Blunt bangs Curls
Business hair 4
Chop
Combed hair
Combed hair alt
Cossack
Cossack 2
Cotton hair
Curls twin
Cut hair 2
Dreadtail 1
Dreadtail 2
Elize
Encoder
From Mars
Geisha
Half Shaved alt
Hipstery
Jaden
Ladylike
Ladylike 2
Left sidecut
Leon
Long hair 3
Long hair 4 
Long side part straight
Long sidepart
Long sideparts 
Long straight ponytail
Long wide fringe
Longcover
Longer fringe
Maid tail
Mancut
Mercenary
Messy bun
Messy hair
Messy right side cut
Ming dynasty
Mist
Odango bun
Odango bun 2
Odango bun 3
Odango bun 4
One shoulder braid 
Overeye very short
Overeye very short 2
Oxton
Pais
Pigtails Twintail_Ombre
Pigtails Twintail_Ombre alt
Pixie
Ponytail 4 (TG)
Ponytail 7 (alt)
Ponytail widow
Ponytail widow alt
Ponytail widow short
Protagonist
Roxy
Sick
Side tail 3
Sidepart hair
Slightly messy
Spiky ponytail
Square
Terezi
Undercut female
Undercut swept right
Unkept
Updo
Very long bedhead
Very long bedhead (alt)
Viking
Viking 2
Vriska
Wolven mane
Wong
Ziegler
Zone
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177554040150831125)

**Comment by LordNest** [comment]
Закрыто Сурвом, а ещё мне влом это тестить.
