### ISSUE TITLE
Объект: БС-маяк

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1511]
**Объект:**
БС-маяк

**Название:**
`Bluespace flayer`

**Дополнительная информация:**
Пропал  БС-флаер, который очень полезный под спасение и прочие действия. На него так же можно сесть. При использовании координаты идут на анонс Сьерре
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177559551084597249)

**Comment by LordNest** [comment]
Оно всё и так есть
