### ISSUE TITLE
Объект: Блюспейс-флаер

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1512]
**Объект:**
Блюспейс-флаер

**Название:**
`bluespace flare`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177560244520501359)

**Comment by LordNest** [comment]
Дубликат
