### ISSUE TITLE
Карта: Нету кнопки на blast door в комнатке шахтеров.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1514]
**Название:**
`blast door`

**Дополнительная информация:**
Ангар, комната отдыха шахтеров. Если они как то и открываются, то это очень не интуитивно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177563208953901088)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/eb8ebd76-5169-44f7-a402-7d97133e4007)
Канджи видимо пофиксил, но забыл указать, хз
