### ISSUE TITLE
Карта: Баг лампы в лифте?

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1516]
**Название:**
`light fixture`

**Дополнительная информация:**
Если спустить лифт на 5ю палубу, то с первой будет вид на кучу ламп в одном тайле. Баг?
<hr>

*Репорт сгенерирован автоматически*
*Автор: `divegen` / `277454156661391360`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177570369746505843)

**Comment by LordNest** [comment]
Won't fix
Лифт работает так, он использует шаблоны стенок шахты, чтобы по ней каталась платформа
А на стенках он спавнит лампы
