### ISSUE TITLE
Старый спрайт: Спрайт консоли карго-дрона.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1517]
**Объект:**
Спрайт консоли карго-дрона.

**Название:**
`Supply Drone Virtual Intelligence`

**Дополнительная информация:**
Спрайт отображается красным треугольником.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177579316318584843)

**Comment by LordNest** [comment]
Дубликат
