### ISSUE TITLE
Баг: Можно заспавниться дважды, пока затухает экран лобби-скрина

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#153]
**Ckey**:
`MaekoGreenfield`

**Шаги:**
1. Тыкнуть реди. Заспавниться.
2. Когда происходит затухание экрана - тыкаем ещё раз join. 
3. Вы великолепны

**Реальное поведение:**
Спавнятся две куклы с двойным набором вещей

**Ожидаемое поведение:**
не даёт заспавниться второй кукле
<hr>

*Репорт сгенерирован автоматически*
*Автор: `greenfield#1363` / `258962443441537024`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087760725457506405)

**Comment by SuhEugene** [comment]
Мой баг, я фикшу, хуле
