### ISSUE TITLE
Механ: Пропали краски и огоньки для разных моделей ИПС

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1530]
**Название:**
`IPC body markings`

**Дополнительная информация:**
Раньше у ИПС было много "татуировок" которые накладывались поверх спрайта и позволяли изменять цвет текущих деталей корпуса. Пример в картинках под постом. ВЕРНИТЕ!
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gentelman` / `225563403102453760`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177624717973266513)

**Comment by LordNest** [comment]
Идёт активное портирование на Бей
