### ISSUE TITLE
Объект: Прическа Oxton

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1531]
**Объект:**
Прическа Oxton

**Название:**
`Oxton`

**Дополнительная информация:**
Эта прическа имеется как на Сьерре, так и на Парадизе.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `l___blaze___l` / `227012028101820417`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177629169622986773)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/5e7e46ff-87d7-4af5-98d0-45f989213173)
Пофикшено Сурвом
