### ISSUE TITLE
Старый спрайт: tacticool turtleneck

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1532]
**Объект:**
tacticool turtleneck

**Название:**
`tacticool turtleneck`

**Дополнительная информация:**
На инфинити при попытке закатать рукава (roll up sleeves)  у этой формы все хорошо, пытаясь закатать рукава на СьерраБее форма просто пропадает с куклы 
P.S. слот остается занятым, но форма просто перестаёт отображаться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `truly.vali` / `402524661784510475`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177646815898771466)

**Comment by LordNest** [comment]
`icons\mob\onmob\onmob_under.dmi`

дубликаты состояний со свёрнутыми рукавами
