### ISSUE TITLE
Старый спрайт: Усиленная стена из песчанника

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1534]
**Объект:**
Усиленная стена из песчанника

**Название:**
`reinforced sandstone wall`

**Дополнительная информация:**
Вместо спрайта - заглушка No sprite
<hr>

*Репорт сгенерирован автоматически*
*Автор: `uedcommander` / `200682967775969280`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177653598100918312)

**Comment by LordNest** [comment]
Починил с новыми руинами
