### ISSUE TITLE
Объект: прическа messy bun

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1538]
**Объект:**
прическа messy bun

**Название:**
`messy bun`

**Дополнительная информация:**
она есть на БейСьерре, но на Сыробее — нет. а красивая ведь…
<hr>

*Репорт сгенерирован автоматически*
*Автор: `karcodd` / `923184606415568957`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177661842395516969)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/5149af7a-d381-4e6a-bfce-b5946f588f07)
Пофикшено Сурвом
