### ISSUE TITLE
Баг: Нельзя выбрать протез у таяра

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1541]
**Ckey**:
`Tackcard`

**Шаги:**
1. Войти в редактор персонажа
2. Выбрать куклу-таяран
3. Выбрать Adjust Limbs и нужную конечность

**Реальное поведение:**
Не предлагает марку протезов, а просто закрывается, не меняя ничего

**Ожидаемое поведение:**
Должно предлагать выбрать марку протеза, а после выбора протез должен появиться у куклы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tenebriscattus` / `430069039918743573`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177685812335362112)

**Comment by LordNest** [comment]
Дубликат 
Ну кого просил в закрепе смотреть
