### ISSUE TITLE
Объект: Опция "Shaved" в выборе Facial Hair у Таяра

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1542]
**Объект:**
Опция "Shaved" в выборе Facial Hair у Таяра

**Название:**
`Shaved (Настройка персонажа - Facial Hair)`

**Дополнительная информация:**
Нет возможности побрить таяру...
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tenebriscattus` / `430069039918743573`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177686936224280667)

**Comment by LordNest** [comment]
Дубликат #1433
