### ISSUE TITLE
Объект: Атмосферный щит

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1547]
**Объект:**
Атмосферный щит

**Название:**
`atmosferic crate или что то там`

**Дополнительная информация:**
Отсутствует атмосферный щит.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177690476992802987)

**Comment by LordNest** [comment]
Дубликат
