### ISSUE TITLE
Объект: Причёска: slightly messy

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1549]
**Объект:**
Причёска: slightly messy

**Название:**
`slightly messy`

**Дополнительная информация:**
Есть на Инфините Сыре, на СырБее же её увы нет, а хорошая
<hr>

*Репорт сгенерирован автоматически*
*Автор: `truly.vali` / `402524661784510475`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177696033971650630)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/05e3ae97-0385-4528-8aec-f8348d2c0cf3)
Закрыто Сурвом
