### ISSUE TITLE
Баг: Предметы на консолях находятся под слоем картинки консоли

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#155]
**Ckey**:
`furior`

**Шаги:**
1. Распечатать какую нибудь бумажку на консоли в РнД

**Реальное поведение:**
Бумажка будет находится под экраном консоли

**Ожидаемое поведение:**
Бумажка должна быть над экраном консоли
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Furior#9776` / `346586265602228226`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087764786185510963)

**Comment by cuddleandtea** [comment]
https://github.com/Baystation12/Baystation12/pull/33054 Вот, возможно их (наш) фикс проблемы

**Comment by SuhEugene** [comment]
> [Baystation12#33054](https://github.com/Baystation12/Baystation12/pull/33054) Вот, возможно их (наш) фикс проблемы

Нет, это наоборот именно то, что и сломало

**Comment by Atufancheg** [comment]
![image](https://user-images.githubusercontent.com/44374097/227892024-ddc831ea-30aa-4af6-9e71-3f4aa9b5d4f1.png)
не воспроизводится

**Comment by SuhEugene** [comment]
> ![image](https://user-images.githubusercontent.com/44374097/227892024-ddc831ea-30aa-4af6-9e71-3f4aa9b5d4f1.png)
> не воспроизводится

Проверять нужно на консоли со включенным экраном
Плюс возможно гист пофиксил, но не факт

**Comment by Atufancheg** [comment]
![image](https://user-images.githubusercontent.com/44374097/228447088-f286e29a-d042-4b44-8bc7-24c640f3fbe8.png)
вот со включеным

**Comment by ImJustKisik** [comment]
Судя по комментариям в иссуе не баг. Закрываю. Если снова появится - открою снова
