### ISSUE TITLE
Объект: Андеркат направо и женский

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1552]
**Объект:**
Андеркат направо и женский

**Название:**
`undercut swept right енд undercut female (вроде так)`

**Дополнительная информация:**
Вроде бы ещё андеркат был утерян, но точно не помню, а дальше нытьё, читать стоит. Есть андеркат направо, а налево нет, думаю, стоит исправить несправедливость; так же думаю что женский андеркат во внимание брать не стоит :жокерге:
<hr>

*Репорт сгенерирован автоматически*
*Автор: `mrfloppus` / `652566768623157275`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177702036624650280)

**Comment by LordNest** [comment]
Добавлено Сурвом портом с Оникса. 
На оригинальных инфинити это тоже порт с Оникса
