### ISSUE TITLE
Карта: Нет ящиков с ураном

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1557]
**Название:**
`Uranium Sheets`

**Дополнительная информация:**
Короче. У торгашей, рядом с комнатой для ядерного реактора, нету ящиков с ураном. А должен быть. Есть тупа два пустых места.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `semonic` / `361140847682781186`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177929591382351902)

**Comment by LordNest** [comment]
Не воспроизводится
