### ISSUE TITLE
Баг: Зарядник для синтетиков выкидывает ИПСов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1558]
**Ckey**:
`KOJIECO`

**Шаги:**
1. Подойти к любому заряднику.
2. Попытаться в него зайти.
3. Вас выкинет.

**Реальное поведение:**
Зарядник для синтетиков выкидывает ИПСов из себя (с другими синтетиками не чекал). Только на четвертый раз можно успешно залезть внутрь.

**Ожидаемое поведение:**
ИПСа не должно выкидывать из зарядника, а он должен зарядиться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `superkojieco` / `233629146981335041`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1177957021769805836)

**Comment by LordNest** [comment]
Дубликат #1092
