### ISSUE TITLE
Баг: У таяра нету татуировок

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1561]
**Ckey**:
`GQ0k`

**Шаги:**
в сетапе у таяра нельзя выбрать татуировки

**Реальное поведение:**
их нет, совсем

**Ожидаемое поведение:**
но они должны быть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1178000357461344348)

**Comment by LordNest** [comment]
Беспределом ксеномодерации закрываю ишшуй и говорю что не баг
