### ISSUE TITLE
Механ: Уникальный цвет Миранийского языка в чате

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1563]
**Название:**
`miranian`

**Дополнительная информация:**
На лайве Миранийский имел свой уникальный зеленоватый цвет в чате, на Сьеррабее такого нет, надо-бы вернуть.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1178054720103915562)

**Comment by LordNest** [comment]
Требует изменения файлов оутпута браузера.
Сейчас подумаем...
