### ISSUE TITLE
Запрос: ИКС ЛЭКа не защищает так как должен

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1571]
**Название:**
`HCM`

**Дополнительная информация:**
ИКС ЛЭКа защищает очень хорошо от входящего физического урона от ближнего боя (дальний бой наоборот) помимо этого слабо пробивает радиация и так далее, однако в хоте теста появилось ощущение что он защищает хуже (фауна на планете а именно гусь, поставил перелом и кровотечение за 2 удара, хотя ранее хотя на инфинити ИКС держит спокойно удары малых и средних хорроров)так же находясь в радиоактивном облаке тоже пробивает икс, хотя не должен. если есть возможность подсмотреть и как то поднять цифры будет хорошо, ибо сейчас ИКС ЛЭКа хуже чем обычный войдсьют, так как мне пробили внутряги, поставили просто кровотечение, и кости сломали, и ладно бы мощный моб, но гусь...Его тоже надо посмотреть, может там пробитие сильное стоит.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1178298985245589524)

**Comment by LordNest** [comment]
Проблема не в ИКСе, его показатели брони не изменились. 
Вероятно проблема в боёвке Торча, потому что нужно будет ещё твиков накатить на это дело. 
Но потом.
