### ISSUE TITLE
Звук: Звуки некоторых эмоутоув (вздох, смех и так далее), звуки открывания дверей, звуки гиба, и перелома.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1616]
**Название:**
`слишком много.`

**Дополнительная информация:**
Скорее всего было описано, поэтому еще добавлю. Помимо вышеперечисленных звуков. Добавить звуки для унатхов с парадиза (удары хвостом, раскрывание пасти, шипение, рык и.т.д). С описаными выше звуками проблема простая их нет. А с эмоутами и звукими унатхов будет углубление ролевой игры этой расы, плюс красивое звуковое сопровождение.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `colonelhaynes` / `347088512757006336`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183366110624632872)

**Comment by LordNest** [comment]
Частично сделано, частично требует атомизации/дубли
