### ISSUE TITLE
Баг: Панелька интерфейса сломана

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#162]
**Ckey**:
`Reevie Core`

**Шаги:**
1. Заходим за ППТ в раунд
2. Смотрим в левый угол

**Реальное поведение:**
Видим остатки прошлого интерфейса, на который залез заряд аккумулятора

**Ожидаемое поведение:**
Нормальный интерфейс без налезаний друг на друга
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LoL, No Username#6444` / `508677373559046195`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087772066343829554)

**Comment by ImJustKisik** [comment]
#161 linked
