### ISSUE TITLE
Старый спрайт: poster - Sunrise on S'Randjiir

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1620]
**Объект:**
poster - Sunrise on S'Randjiir

**Название:**
`poster - Sunrise on S'Randjiir`

**Дополнительная информация:**
У данного постера отсутствует спрайт
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lisikohoro` / `455436205740261376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183428395502162041)

**Comment by SuhEugene** [comment]
Баг со всеми постерами таяр. Дубликат #1614
