### ISSUE TITLE
Запрос: Введение для грызунов-модов, живущих в технических тоннелях, возможности грызть провода.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1621]
**Название:**
`mouse, opossum, cable,`

**Дополнительная информация:**
Хорошим вариантом для расширения иммерсивности игры стало бы введение возможности для грызунов грызть провода и нарушать систему электро-снабжения.

Зачем? Ну, это позволит добавить для таких профессий как уборщики и инженеры дополнительные малые активности.
- Инженеры должны будут искать места, где мышка таки прогрызла кабель и заменить его в два клика.
- Уборщики должны будут вести неустанную борьбу с грызунами, которым в пределах наших огромных техов есть где разгуляться. 

Поведение обслуживающих дронов уже было изменено на более агрессивное. Почему бы не добавить мышам и опоссумам больше мозгов?

На ФФе довольно адекватно реализована данная механика, которая добавила инженерам эту малую активность в виде устранения прогалов в энергосети. Не думаю, что подобное нововведение будет каким-то образом радикально изменять механ или баланс игры. Зато для скучающих жителей судна будет чуть больше возможностей разбавить рутину.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `necronomicat` / `323123170024357888`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183428633897992286)

**Comment by SuhEugene** [comment]
Идея просто отличная.
Но до выхода SierraBay мы возвращаем старое, не вводя почти ничего нового.
А после выхода SierraBay данная идея должна быть с помощью предложки воплощена в жизнь.

`/репорт запрос` он для всего, что нельзя назвать багом, но поправить надо

![Описание команды репорт запрос в дискорде](https://github.com/SierraBay/SierraBay12/assets/32931701/774e40f0-96c9-4805-b1e2-358b5b3507dc)
