### ISSUE TITLE
Старый спрайт: poster - First mech poster

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1626]
**Объект:**
poster - First mech poster

**Название:**
`poster - First mech poster`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183455058063532174)

**Comment by LordNest** [comment]
Дубликат #1614
