### ISSUE TITLE
Механ: Спички не зажигаются об коробок

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1627]
**Название:**
`matchbox, matchbook`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `pocket_medic` / `300660518295961601`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183462571840380958)

**Comment by SuhEugene** [comment]
Ждём https://github.com/Baystation12/Baystation12/pull/34478

**Comment by LordNest** [comment]
Предположим что оно всё-таки было пофикшено Раяном. Просто предположим, он же фиксил аттакбаи.
