### ISSUE TITLE
Механ: нельзя греть напитки в стакане

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1628]
**Название:**
`lighter и любой стакан???`

**Дополнительная информация:**
На сиерре можно было греть напиток и шел прикольный дымок, добавляло шарма в работу бармена, тут же просто нет и это убого
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1183465735570329670)

**Comment by LordNest** [comment]
Дубликат #1551
