### ISSUE TITLE
Запрос: Медленная анимация движение персонажа в госте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#163]
**Название:**
`---`

**Дополнительная информация:**
Нужен ресет скорости анимации при выходе в госты, чтоб двигались с одинаковой скоростью или анимации вообще не было
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087772348301705256)

**Comment by LordNest** [comment]
Так как проблема в инпуте, то перекрываем вот этим вот иссуем
#1358
