### ISSUE TITLE
Баг: Спички НЕПОДЖИГАЕМЫ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1662]
**Ckey**:
`NyoRRkish`

**Шаги:**
1. Купить спичечный коробок, либо, спичечную книжку
2. разорвать ленту, и открыть спичечный коробок или книжку.
3. Достать спичку, закрыть, либо, не закрыть коробок
4. попытаться зажечь

**Реальное поведение:**
В независимости от айтемстейта, спичка засовывается в коробок обратно

**Ожидаемое поведение:**
При айтемстейте закрытого спичечного коробка|книжки, спичка должна зажечься
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188675082416037979)

**Comment by LordNest** [comment]
Дубликат #1627
