### ISSUE TITLE
Лодаут: Special scarfs selection

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1663]
**Объект:**
Special scarfs selection

**Название:**
`christmas scarf, blue striped scarf, green striped scarf, red striped scarf, zebra scarf`

**Дополнительная информация:**
Предметы отсутствуют для выбора в лодауте и это плохо! В конце концов, вот-вот уже будет Новый Год, а украшений к нему и нет! Кстати, с наступающим! :)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188783285640364062)

**Comment by SuhEugene** [comment]
Репорт лодаута
