### ISSUE TITLE
Лодаут: Все сбшные худы в лодауте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1664]
**Объект:**
Все сбшные худы в лодауте

**Название:**
`HUDpatch Sec, Security HUD, Security HUD goggles, Security HUD Sunglasses, Security HUD prescription`

**Дополнительная информация:**
Отсутствуют все худы для СБ, даже вкладки в glasses в лодауте нет! Непорядок, один рекрут из 10 сбшников негодует!
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188785129229922414)

**Comment by SuhEugene** [comment]
Репорт лодаута
