### ISSUE TITLE
Карта: Отсутствуют наколенники для плитников в арсенале брига

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1665]
**Объект:**
Отсутствуют наколенники для плитников в арсенале брига

**Название:**
`leg guards`

**Дополнительная информация:**
На лайве у нас таковые в наличии. Здесь же их нет. Не знаю, может их просто нет в билде но это всё равно непорядок! Раз добавили налокотники, вводите и наколенники! Хе-хе-хе!
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188793328150523905)

**Comment by SuhEugene** [comment]
Репорт лодаута
