### ISSUE TITLE
Механ: Удар головой об стол

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#167]
**Название:**
`grab`

**Дополнительная информация:**
раньше при клике в красном интенте на стол грабом можно было ударить человека головой об стол. Сейчас же такой возможности почему то нет, вместо этого игра просто кладет цель на стол 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Shap04ka#9929` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087780295325007903)

**Comment by SuhEugene** [comment]
Оказывается это был баг. Оффы пофиксили
