### ISSUE TITLE
Баг: Мобьё живо в abandoned escape pod

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1671]
**Ckey**:
`Baneuus`

**Шаги:**
1. Найти эту планетарную структуру
2. Посмотреть на мобов.
3. Они живы и афк, с низким процентом мозга.

**Реальное поведение:**
Они живые.

**Ожидаемое поведение:**
Они должны быть мертвы.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188837270321635337)

**Comment by LordNest** [comment]
Фича
