### ISSUE TITLE
Лодаут: Слишком много всего, чтобы писать в это поле

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1676]
**Название:**
`Слишком много всего, чтобы писать в это поле`

**Дополнительная информация:**
Сначала я хотел сделать запрос по каждой категории отдельно, но понял, что легче будет создать один общий запрос, а потом накидать скринов в ветку дискорда.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `aventrus` / `186161532311175168`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188863969289588809)

**Comment by LordNest** [comment]
В общем и целом иссуй был закрыт. Возможно осталась пара-тройка предметов, но их добавление опционально/про это будут другие иссуи.
