### ISSUE TITLE
Старый спрайт: Все канистры воздушных пакостей

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1678]
**Объект:**
Все канистры воздушных пакостей

**Название:**
`portable_atmospherics/canister/`

**Дополнительная информация:**
Канистры имеют заоблачные показания для смены цвета лампочки заполненности:

CANISTER_PRESSURE_EMPTY = 101.325
CANISTER_PRESSURE_HIGH = 15198.8
CANISTER_PRESSURE_LOW = 5066.25
CANISTER_PRESSURE_MID = 10132.5
<hr>

*Репорт сгенерирован автоматически*
*Автор: `pocket_medic` / `300660518295961601`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188874938594099211)

**Comment by SuhEugene** [comment]
Уже миллион раз решили, что это не баг а фича.
Да, канистры спавнятся с красной лампочкой, но это правильно, потому что они действительно практически пустые.
