### ISSUE TITLE
Баг: Нельзя прикрепить оружие в suit storage когда одет плитник

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1679]
**Ckey**:
`NyoRRkish`

**Шаги:**
1. Одеть плитник
2. Взять оружие, и попытаться прикрепить в suit storage

**Реальное поведение:**
Оружие не прикрепляется к suit storage плитника

**Ожидаемое поведение:**
Оружие вставляется в suit storage при плитнике
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188876066849308762)

**Comment by LordNest** [comment]
НЕ
ВОСПРОИЗВОДИТСЯ
