### ISSUE TITLE
Баг: При попытке двигаться наискосок в трубе, тебя выкидывает

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1680]
**Ckey**:
`LordNest`

**Шаги:**
1. Быть мышью/иной сущностью, которая двигается в трубе
2. Ползти в трубе, зажав W и D/S и A и т.п.

**Реальное поведение:**
Мышь вываливается из трубы при попытке переместиться по-диагонали

**Ожидаемое поведение:**
Мышь продолжает движение в трубе.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lordnest` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188876969769697421)

**Comment by LordNest** [comment]
https://github.com/ss220-space/Baystation12/pull/95

Вот этот накатить
