### ISSUE TITLE
Баг: Шанс робо операции

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1686]
**Ckey**:
`RogueOtrok`

**Шаги:**
Стадартное робо оперирование.
Берёшь отвёртку откручиваешь... откручиваешь? А почему не получилось???
Пытаешься ещё 3 раза хотя нормальные скиллы стоят.
И так же по всем другим стадиям. Шансы на инструменты слишком заниженны.

**Реальное поведение:**
Слишком высокие шансы на провал с правильными скиллами.

**Ожидаемое поведение:**
Шанс должен быть хотя бы выше 50 с навыками сложных устройств и науки на Trained и на медицине с анатомией на опытном.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `kiro6882` / `553348903056179231`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188923134645112852)

**Comment by LordNest** [comment]
* наука и не должна влиять на шансы для робо
* Берите опытного девайсов, это профильный навык робототехника. Не брать его - не логично. 
* вам хватает навыка для того чтобы брать анатомию+мёд+девайсы + констракт. 
* если хотите быть именно техником, то просите медиков оперировать "на живое". Если биотехом, то живите без навыков боя и атлетики
