### ISSUE TITLE
Механ: Циферки точности проджектайлов при выстреле

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1687]
**Название:**
`Любые проджектайлы (Чаще всего оружейные)`

**Дополнительная информация:**
Пиу пиу, паф паф, мисс, мисс жопа горит.

Точность у выстрелов сильно упала, вернуть или циферки инфинити, или среднее между ними/дать скиллам больший бафф на точность/Я хуй знает.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188923367928107138)

**Comment by SuhEugene** [comment]
#1685 (<#1188922650924421283>) дубликат
