### ISSUE TITLE
Запрос: Любой может вырваться с опытного ББ со второго раза

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1688]
**Название:**
`Ближний Бой`

**Дополнительная информация:**
Как я правильно понял, абсолютно любой может выйти с усиленного захвата если протыкать B (сопротивление) два раза, или больше
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188924166875906098)

**Comment by LordNest** [comment]
Не воспроизводится согласно комментарию тестовой команды
