### ISSUE TITLE
Баг: Станбатон не станит :Rofl_Cat:

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1689]
**Ckey**:
`NyoRRkish`

**Шаги:**
1. Взять станбатон
2. Защиткурить какого-то олуха при помощи станбатона на хелп интенте

**Реальное поведение:**
чел хуярится станбатоном, и ничего не происходит

**Ожидаемое поведение:**
После нескольких ударов, человек должен повалится на землю
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188926287058837695)

**Comment by LordNest** [comment]
Не воспроизводится
