### ISSUE TITLE
Баг: Полоска чата перекрывается строкой ниже

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#169]
**Ckey**:
`The_Hero13`

**Шаги:**
1. Просто зайти на сервер
2. Посмотреть на полоску чата

**Реальное поведение:**
Полоска чата перекрывается строкой ниже

**Ожидаемое поведение:**
Полоска чата не должна быть обрезана
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Aventrus#0855` / `186161532311175168`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087794267197546556)

**Comment by Atufancheg** [comment]
![image](https://user-images.githubusercontent.com/44374097/227892462-5cf9c485-77eb-4d1c-98a9-68d7a8e2967c.png)
не воспроизводится

**Comment by SuhEugene** [comment]
Пофикшено в #191
