### ISSUE TITLE
Баг: Не детонируют гранаты

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1690]
**Ckey**:
`r3dok`

**Шаги:**
1. Получить Large Chem Grenade, 2 банки с химикатами, игнайтер, таймер.
2. Банки вставляются, но игнайтер и таймер не вставляются.

**Реальное поведение:**
Не вставляется таймер/игнайтер

**Ожидаемое поведение:**
Должен вставляться и гранаты собственно собираться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `r3dok` / `291958406460473344`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188926774281764904)

**Comment by SuhEugene** [comment]
На оффах помню фиксили чота такое. Надо не забыть проверить правильность того как миррор с этим ПР сработал.

**Comment by LordNest** [comment]
Воот это учесть

В B2 запихать Sulfur и Aluminium. 10ю каждого должно хватить, может даже если меньше, 5ю, то сработает, но не проверял.
Potassium уже есть в B1

**Comment by LordNest** [comment]
Сам иссуй не про это, но короче оставим как есть с гранатами
