### ISSUE TITLE
Баг: Помада не красит губы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1691]
**Ckey**:
`r3dok`

**Шаги:**
1. Получить помаду
2. Открыть
3. Покрасить губы кликнув на персонажа с помадой в руке открытой.

**Реальное поведение:**
Губы не красятся, ничего не происходит

**Ожидаемое поведение:**
Губы покрасятся.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `r3dok` / `291958406460473344`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188927155091034292)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/2a7f6f16-1e29-43c4-b215-113e9036f9a0)

Пофикшено апстримом
