### ISSUE TITLE
Объект: Худ-очки охраны

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1694]
**Объект:**
Худ-очки охраны

**Название:**
`HUD Visor|Security HUD`

**Дополнительная информация:**
В Лодауте нету как очков охраны, так самого ХУДа охраны
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1188995519184375878)

**Comment by SuhEugene** [comment]
Дубликат.

(Плюс уже есть ПР с фиксом)
