### ISSUE TITLE
Баг: Спрайт ломается при very tall росте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#170]
**Ckey**:
`The_Hero13`

**Шаги:**
1. Выставить рост very tall
2. Зайти в игру
3. Раздеться (опционально) (см. прикреплённый скрин)

**Реальное поведение:**
Спрайт ломается

**Ожидаемое поведение:**
Спрайт не должен ломаться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Aventrus#0855` / `186161532311175168`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087795741289889912)

**Comment by ImJustKisik** [comment]
Не баг, особенность скейлинга куклы

**Comment by SuhEugene** [comment]
@ImJustKisik тут вда вида закрытия. Один - закрыть как решено, второй - закрыть как won't fix.
Есть won't fix, то ты won't fix и выбирай

**Comment by SuhEugene** [comment]
![image](https://user-images.githubusercontent.com/32931701/229297927-28824ce7-feda-43df-8707-4219505a24b9.png)
