### ISSUE TITLE
Механ: Портировать с сс220 статы оружейки воксов и скрап-шлем

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1702]
**Название:**
`scrap helmet, flux cannon, sound cannon, spikethrower, slug sling`

**Дополнительная информация:**
Балансные штуки для воксов, которые качественно развивают и улучшают геймплей всех сторон, но которые без моего длительного разбора в модовой системе нового билда рискуют кануть в лету.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189297931333935225)

**Comment by SuhEugene** [comment]
Если это предложение, то это должно быть в книге предложений и ишью нужно закрыть
Если это баг, то тег стоит сменить на `Механ`, и переименовать на `Механ:`

@LordNest
