### ISSUE TITLE
Механ: Set Ghost Alpha

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#171]
**Название:**
`Ghost alpha for self`

**Дополнительная информация:**
Вкладка ghost, там отсутствует кнопка отключения альфа канала
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087827697947918366)

**Comment by cuddleandtea** [comment]
https://github.com/Baystation12/Baystation12/pull/34327

**Comment by LordNest** [comment]
А закрыть? И какого лешего у нас ещё дубликаты
