### ISSUE TITLE
Звук: Звук тыканья в шлюз.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1711]
**Название:**
`It opens and closes.`

**Дополнительная информация:**
Нет звука тыканья в шлюз без доступа. Просто мигает лампочка.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189572996390731848)

**Comment by LordNest** [comment]
А, и да, дубликат #1157
