### ISSUE TITLE
Запрос: У стажёров-инжей нет доступа к автомату Engi-Vend

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1712]
**Название:**
`Engi-Vend`

**Дополнительная информация:**
Доступа нет, а там лежат важные штуки. Хотелось бы, чтоб был.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189574143474159768)

**Comment by LordNest** [comment]
req_access = list(list(access_atmospherics, access_engine_equip))

Так вот, у трейни вот такое
	access = list(		access_engine, access_maint_tunnels, access_external_airlocks, access_emergency_storage,
			            access_eva, access_janitor, access_construction,
			            access_hangar)

На Инфинити оно одинаковое. 
Собственно вот и ответ. Отклонено.
