### ISSUE TITLE
Баг: Экран управления компактором не работает

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1715]
**Ckey**:
`LisikoHoro`

**Шаги:**
1. Открыть экран управления компактором мусора.

**Реальное поведение:**
Окошко открывается, но не имеет интерфейса, возможно проблема в с UI, но хер его знает ибо не работает оно у всех

**Ожидаемое поведение:**
Окошко открывается и имеет интерфейс управления давилкой и шлюзами.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lisikohoro` / `455436205740261376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189594717176987739)

**Comment by LordNest** [comment]
Отвалился темплейт. Пофиксим в ПРе.
