### ISSUE TITLE
Объект: Кнопка подачи сигнала бедствия

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1716]
**Объект:**
Кнопка подачи сигнала бедствия

**Название:**
`Emergency beacon button?`

**Дополнительная информация:**
Вроде название такое, кнопок для подачи сигнала бедствия нету на обоих шаттлах ИКН Сьерры, в случае пиздеца, позвонить по голопаду на сьерру может представляться невозможным
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189653495587029126)

**Comment by LordNest** [comment]
Заменено radio beacon
