### ISSUE TITLE
Механ: Госты могут голосовать за окончание раунда при воуте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#172]
**Название:**
`Воут об окончании раунда`

**Дополнительная информация:**
По логике голосовать должны только те игроки, которые непосредственно играют в раунде, а не наблюдают за игрой
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087828289613213747)

**Comment by SuhEugene** [comment]
Настраивается в конфиге
