### ISSUE TITLE
Баг: Позиции камер в карте камер улетели за свои точки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1720]
**Ckey**:
`NyoRRkish`

**Шаги:**
1. открыть камеры
2. выбрать режим отображения как карту
3. выбрать любой раздел

**Реальное поведение:**
точки камер находятся за своей нужной позицией

**Ожидаемое поведение:**
точки камер находятся точно на закреплённой позиции
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189677601892073492)

**Comment by LordNest** [comment]
Дубликат #1357
