### ISSUE TITLE
Баг: Предметы в лодауте не сохраняют спрайт и тип предмета.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1721]
**Ckey**:
`LisikoHoro`

**Шаги:**
1. Выбрать любой элемент одежды в лодауте у которого можно изменять цвет.
2. Выбрать предмету понравившийся цвет и переключится на другую категорию
3. Взглянуть на окошко персонажа и понять, что цвет сменился на самый черный

**Реальное поведение:**
Вместо того, что бы сохранять цвет выбранный игроком, предмет меняет цвет на самый черный который может.

**Ожидаемое поведение:**
Предмет должен сохранять выбранный игроком цвет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lisikohoro` / `455436205740261376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189681176143724655)

**Comment by LordNest** [comment]
Это #1762 тоже сюда складываем

**Comment by LordNest** [comment]
Закрываем по причине полной переработки лодаута #1853
