### ISSUE TITLE
Запрос: На воксшипе при щитспавне ломается атмосфера.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1728]
**Название:**
`shoal ship, vox`

**Дополнительная информация:**
На воксшипе при щитспавна атмос из камер вылезает в общее помещение. Нужно применить маппинг актуального сервера, где атмос заключён в множество канистр.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189942489768013844)

**Comment by LordNest** [comment]
На скреллшипе тоже, несмотря на баки, лол
