### ISSUE TITLE
Старый спрайт: hand-mounted powerfists

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1729]
**Объект:**
hand-mounted powerfists

**Название:**
`/obj/item/rig_module/mounted/power_fist`

**Дополнительная информация:**
У нового модуля паверфиста нет спрайта, только красный треугольник
<hr>

*Репорт сгенерирован автоматически*
*Автор: `shap04ka` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189942957789425735)

**Comment by LordNest** [comment]
оно что? Пральна, одинаковое с #1736
