### ISSUE TITLE
Звук: Flux cannon, звук focused режима.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1730]
**Название:**
`flux cannon`

**Дополнительная информация:**
У флюксы звук хрей пушки. Для такой убойной мощи он слишком высокий. На основном сервере он гораздо более низкий и грубый.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189943649371439114)

**Comment by LordNest** [comment]
Флюкса использует обычный звук лазера. Ничего необычного.
