### ISSUE TITLE
Карта: Скреллшип сломался

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1731]
**Название:**
`SSV, scout ship, skrell, SDTF`

**Дополнительная информация:**
На скреллшипе консоли управления основного корабля не законтачены к самому кораблю и не могут быть переконтачены.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1189946560985960589)

**Comment by LordNest** [comment]
Воспроизвести после мерджа #1814

**Comment by LordNest** [comment]
Пофикшено ПРом Макера
