### ISSUE TITLE
Механ: Удержание аугмента на/в руке

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1735]
**Название:**
`Все с функцией  извлечения  engineering toolset,  surgical toolset, embedded blade, power fist`

**Дополнительная информация:**
Все аугменты из этого списка могут быть "уронены" на пол при нажатии кнопки или если владельца аугмента возьмут в захват или иными методами создающие ситуацию выпадение вещей из рук
<hr>

*Репорт сгенерирован автоматически*
*Автор: `darkman24rus` / `244108882199183361`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190167417683464232)

**Comment by LordNest** [comment]
Дубликат #1029
