### ISSUE TITLE
Карта: Нет монстров на эвейке

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1739]
**Название:**
`Orbital Mining Station`

**Дополнительная информация:**
An orbital Mining Station bearing authentication codes from Grayson Mining Industries, sensors show inconsistant lifesigns aboard the station. It is emitting a weak signal on a public frequency, with no other discernible radio traffic.

- На этой эвейки должны были быть монстры-ксеноморфы местные
<hr>

*Репорт сгенерирован автоматически*
*Автор: `darkman24rus` / `244108882199183361`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190183068997255178)

**Comment by LordNest** [comment]
Не баг
