### ISSUE TITLE
Баг: Нельзя надеть ИКС ЭК за ксенорасу, нет ксеноспрайтов скафандров

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1741]
**Ckey**:
`gq0k`

**Шаги:**
1. Надеть ИКС ЭК на таярана (проверял на таяра)
2. Нажать кнопку "включить хардсьют"
3. Получить в лицо надпись, что части ИКС не подходят вашей расе анатомически

**Реальное поведение:**
ИКС не разворачивается

**Ожидаемое поведение:**
ИКС должен развернутся
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190244958632947722)

**Comment by LordNest** [comment]
Закрыто #1717
