### ISSUE TITLE
Баг: При нажатии на альт+клик на тайле, где стоит персонаж сломано отображение

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1743]
**Ckey**:
`gq0k`

**Шаги:**
1. Нажать альт+клик (открыть вкладку turf)
2. Увидеть, что персонаж в окне турфа отображён без настроек (Пример: Белый персонаж таяран в чёрных штанах (как и любой другой) в турфе будет выглядеть как чёрный в белых штанах.

**Реальное поведение:**
Персонаж выглядит несоотвествующе действительному

**Ожидаемое поведение:**
Персонаж должен отображаться корректно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190246607720042536)

**Comment by SuhEugene** [comment]
Увы, это беда самого бьёнда и я не думаю, что мы можем что-то с этим сделать :c

Та же проблема случается и с контекстным меню на ПКМ
