### ISSUE TITLE
Баг: под рисунком мелками (в частности - рунами) остаётся красный треугольныек

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1744]
**Ckey**:
`gq0k`

**Шаги:**
1. Нарисовать руну мелками
2. На долю секунды появляется красный треугольник, который тут же прячется появившейся руной

**Реальное поведение:**
Появляется треугольник под руной

**Ожидаемое поведение:**
Треугольника быть не должно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190251052868579480)

**Comment by LordNest** [comment]
Воспроизводится. Пусть муриканцы фиксят.
