### ISSUE TITLE
Карта: В бриге отсутствует скафандр сапёра.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1749]
**Название:**
`sapper voidsuit (примерно оно, т.к. лайв щас спит и узнать не могу)`

**Дополнительная информация:**
На месте скафандра сапёра находится просто костюм сапёра. Непорядок, стоит вернуть как было.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190296604536741979)

**Comment by LordNest** [comment]
И это я тоже добавил
