### ISSUE TITLE
Баг: Нет звука включения и выключения сварки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#175]
**Ckey**:
`GusevDuhast`

**Шаги:**
1. Берем сварку 
2. Включаем сварку
3. Выключаем сварку

**Реальное поведение:**
Звук включения и выключения не воспроизводится

**Ожидаемое поведение:**
Должен воспроизводиться звук
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Скавен-крыс#1932` / `275692473295044608`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087834171063423036)

**Comment by SuhEugene** [comment]
Пофикшено в #263
