### ISSUE TITLE
Механ: Кнопка Send to lobby

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1750]
**Название:**
`Player Panel`

**Дополнительная информация:**
В player panel сбей нет ни кнопки отсыла в лобби, ни кнопки обнуления времени ожидания. Пожалуйста, верните
<hr>

*Репорт сгенерирован автоматически*
*Автор: `imony.` / `425720135370801162`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190302815701176451)

**Comment by LordNest** [comment]
Дубликат #1201
