### ISSUE TITLE
Лодаут: Модули сканера для ПДА/Планшетов/Ноутбуков

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1758]
**Название:**
`Scanner module (любые)`

**Дополнительная информация:**
Медицинские, реагенты, сканеры бумаги, атмос сканеры.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190398418879782963)

**Comment by LordNest** [comment]
Было исправлено в одном из больших паков фиксов
