### ISSUE TITLE
Лодаут: Возможность перекрасить ожоги.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1759]
**Название:**
`Burnface (любые)`

**Дополнительная информация:**
Цвет всегда один - чёрный.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190398837488099369)

**Comment by LordNest** [comment]
Механизм кода берёт цвет кожи и делает его темнее, как и подобает шраму, а не HEX блин, который будет всех цветов радуги
Фича.
