### ISSUE TITLE
Баг: Освещение травы работает странно

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#176]
**Ckey**:
`furior`

**Шаги:**
1. Прийти в визиторскую
2. Посмотреть на траву в комнате над статуей через окно

**Реальное поведение:**
Освещение травы выглядит очень странно

**Ожидаемое поведение:**
В темноте травы не видно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Furior#9776` / `346586265602228226`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1087844965331238992)

**Comment by ImJustKisik** [comment]
Невозможно исправить без переписывания системы освещения
