### ISSUE TITLE
Баг: Сбрасывается выбранная кобура в лодауте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1762]
**Ckey**:
`Molbertich`

**Шаги:**
1. Выбрать вид кобуры в лодауте
2. Зайти в раунд
3. Окончить раунд, попасть в лобби и проверить выбранную кобуру

**Реальное поведение:**
Кобура сбрасывается с любого другого вида (я проверял на thigh holster) до armpit holster

**Ожидаемое поведение:**
Кобура должна была остаться той, тип которой выбрал игрок в лодауте.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190558997804220539)

**Comment by LordNest** [comment]
Дубликат #1721 так как проблема видимо в БД
