### ISSUE TITLE
Баг: Сбрасывается спрайт у монетки ГКК в лодауте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1763]
**Ckey**:
`Molbertich`

**Шаги:**
1. Выбрать монетку ГКК в лодауте (trinkets, confederation challenge coin select)
2. Зайти в раунд с ней
3. Окончить раунд и попасть в лобби, после чего проверить монетку

**Реальное поведение:**
Спрайт сбрасывается до [ERROR BAD ITEM]

**Ожидаемое поведение:**
Монетка должна остаться с выбранным игроком типом и соответствующим спрайтом
<hr>

*Репорт сгенерирован автоматически*
*Автор: `molbert789💣#9597` / `737872078287536129`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190560023869411390)

**Comment by LordNest** [comment]
Так, это у нас дубликат #1721 ибо проблемы с БД
