### ISSUE TITLE
Баг: Таяра разучились носить ИКСы.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1767]
**Ckey**:
`Kemp_Ace`

**Шаги:**
1. Надеваешь на таяру ИКС вместо сумки. 
2. Включаешь ИКС.

**Реальное поведение:**
You are unable to deploy the helmet as it is not compatible with the anatomy of your species. You are unable to deploy the gauntlets as they are not compatible with the anatomy of your species. You ar

**Ожидаемое поведение:**
ИКС начинает застёгиваться на владельце, ведь раньше он был совместим со всеми расами.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Kemp#5457` / `441261625165479936`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190580587522703420)

**Comment by LordNest** [comment]
Закрыто #1717

**Comment by LordNest** [comment]
Как минимум для исследовательского
