### ISSUE TITLE
Баг: Не правильное  отображение скафандров не ксеносах.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1768]
**Ckey**:
`Kemp_Ace`

**Шаги:**
1. Модифицируем скафандр с отличным телом от человеческого. 
2. Надеваем.

**Реальное поведение:**
Не правильные спрайты скафандра, как на кукле так и в виде вещи. НО при этом не модифицированные надеваются свободно и отображаются на кукле правильно.

**Ожидаемое поведение:**
Не модифицированный скафандр надеть нельзя, Модифицированный надевается и правильно отображается.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Kemp#5457` / `441261625165479936`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1190587833560338582)

**Comment by LordNest** [comment]
Закрыто #1717
