### ISSUE TITLE
Баг: Быстрое движение по диагонали

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#177]
**Ckey**:
`Reevie Core`

**Шаги:**
1. Появляемся в раунде.
2. Встаём в любое обширное пространство
3. Двигаемся по диагонали

**Реальное поведение:**
Движения по диагонали быстрее, чем движение по другим осям

**Ожидаемое поведение:**
Скорость движения должна быть одинаковой
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LoL, No Username#6444` / `508677373559046195`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088027504943583302)

**Comment by SuhEugene** [comment]
Хитрыми способами было измерено, что скорость движения по диагонали не отличается от движения по прямой.
На лайв сервере возможно немного иные настройки скорости ходьбы и бега, а потому ощущается иначе.

Настраивается конфигом. Won't fix.
