### ISSUE TITLE
Карта: Отличие цветов дивана в привате

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#178]
**Название:**
`lime sofa(на тесте) leather sofa(на свервере)`

**Дополнительная информация:**
В приватной комнате стоят не правильные диваны
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088079889174908928)

**Comment by cuddleandtea** [comment]
Не баг. Красивый зеленый цвет так и задуман <3 🍏

**Comment by SuhEugene** [comment]
Нада красиво закрыть, чтоб и в дискордике закрылосб...
