### ISSUE TITLE
Карта: Из доков можно спокойно пробраться в основную часть судна

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#182]
**Название:**
`shutters`

**Дополнительная информация:**
При закрытии всех створок - остаётся непокрытая часть, через которую можно без проблем зайти, если просто захотеть..
<hr>

*Репорт сгенерирован автоматически*
*Автор: `greenfield#1363` / `258962443441537024`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088093821889429564)

**Comment by ImJustKisik** [comment]
Если нест или чай не решат что-то совместно является ли это проблемой или нет. То я к пятнице этот ишуй закрою
