### ISSUE TITLE
Баг: красная надпись над персонажем

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1826]
**Ckey**:
`gq0k`

**Шаги:**
1. Выбрать куртку ЕМП в лодауте.
2. Пощёлкать виды куртки.

**Реальное поведение:**
надпись над персонажем

**Ожидаемое поведение:**
её не должно быть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1200480333565530183)

**Comment by LordNest** [comment]
Очередная итерация бага с лодаутом.
