### ISSUE TITLE
Механ: Возможность класть шприцы/инъекторы в кошелёк

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1829]
**Название:**
`autoinjector`

**Дополнительная информация:**
Раньше можно было класть шприцы и инъекторы в кошелёк, теперь нельзя, хочется, чтобы можно было.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1200493522562846861)

**Comment by LordNest** [comment]
Вольфор сказал закрывать
