### ISSUE TITLE
Баг: У ИИ не работает кнопка "Software interface", не работает возможность разложить

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1832]
**Ckey**:
`LisikoHoro(Передача)`

**Шаги:**
1.  Зайти за ПИИ
2. Нажать на кнопку "Software interface"

**Реальное поведение:**
Если кликать на кнопку ""Software interface" появляется кот Tracy( Изоброжение 1)

**Ожидаемое поведение:**
Появляться менюшка с интерфейсом ПИИ
<hr>

*Репорт сгенерирован автоматически*
*Автор: `XomckiyPenguin#6362` / `571614128800661506`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1200497962258808944)

**Comment by LordNest** [comment]
Дубликат #1393
