### ISSUE TITLE
Баг: Спички всё ещё неподжигаемы :Sadge:

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1840]
**Ckey**:
`NyoRRkish`

**Шаги:**
1.Всё те же шаги, как правильно зажечь спички
2.:Sadge:

**Реальное поведение:**
СПИЧКИ НЕ ЗАЖИГАЮТСЯ

**Ожидаемое поведение:**
Они могут зажечься!!!1111
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1200543487456706600)

**Comment by SuhEugene** [comment]
Дубликат #1627
