### ISSUE TITLE
Карта: Отсутсвие настенных шкафчиков для медикаментов по всей Сиерре

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#186]
**Название:**
` first-aid closet`

**Дополнительная информация:**
По всей Сиерре отсутствуют настенные шкафчики с лекарствами. У тайнике капитана из-за его отсутствия лекарства лежат на полу.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `TiranShot(Артём)#6232` / `235416985935151104`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088105560660000839)

**Comment by cuddleandtea** [comment]
Констебль сказал, что то был его первый ПР, и он займётся портированием иначе этих шкафчиков
