### ISSUE TITLE
Баг: Не работает смена цвета голограмм

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1872]
**Ckey**:
`Lemonloks`

**Шаги:**
1. Подойти к любому цветку (Например в баре)
2. Поменять цвет цветка

**Реальное поведение:**
При смене цвета, голограмма-цветка не меняет свой цвет.

**Ожидаемое поведение:**
Оттенок цветка меняется на выбранный цвет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lemonlox` / `634727799755636738`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1205179321774383115)

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/f7172998-3795-46df-b87a-18d2f47fe9d1)
![image](https://github.com/user-attachments/assets/1580ed33-a207-41c5-8a17-136ee00dd889)
На актуальном на 28.12.2024 билде смена цвета работает.
