### ISSUE TITLE
Механ: Анимация переливания цветов на спрайте ГБС, когда он прожимает кнопку THREAT в охотничьем стансе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1882]
**Название:**
`Switch-Stance/Hostile; Threat`

**Дополнительная информация:**
ГБС переходит в охотничий режим, пряча руки и доставая косы. В этом режиме игроку доступна кнопка Threat, которая по нажатию отправляет в чат лог, издаёт звук жужжания и спрайт серпентида при этом проигрывает анимацию переливающихся цветов. На Сьеррабее этого в данный момент нет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `ratatet` / `186559014581043202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1205221792680255508)

**Comment by UEDCommander** [comment]
Решено на оффах
