### ISSUE TITLE
Запрос: Перенос Recycler в `/packs/infinity/`

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#189]
**Название:**
`/obj/machinery/crusher_base`

**Дополнительная информация:**
Нужно перенести весь мод на recycler в `/packs/infinity/`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088193501856018463)

**Comment by SuhEugene** [comment]
# Внимание!
### Не брать до закрытия #201 !

**Comment by SuhEugene** [comment]
Тест
Раз два три
**Тест**
_раз два три_

**Comment by SuhEugene** [comment]
Раз два три
*Раз два три*
**Раз два три**
_Раз два три_
Тест
