### ISSUE TITLE
Запрос: Нужен рефактор карт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#190]
**Название:**
`icon_state`

**Дополнительная информация:**
Нужно убрать с карт все иконки и очень впечатлившую меня рандомную колоду карт

Сам возьму этот таск
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1088414258452254812)

**Comment by LordNest** [comment]
@SuhEugene сказал что возьмёт таск сам, а не взял по итогу.

**Comment by SuhEugene** [comment]
> @SuhEugene сказал что возьмёт таск сам, а не взял по итогу.

Возьму, когда заниматься им буду

**Comment by LordNest** [comment]
![image](https://user-images.githubusercontent.com/77477080/230099597-54c31d8f-d3ed-4acd-ba23-b2f22b3cdecf.png)

**Comment by LordNest** [comment]
@SuhEugene взял таск и трупанулся. В ВИПе причём.

**Comment by YegorKandziuba** [comment]
@SuhEugene ишуй не актуален?

**Comment by SuhEugene** [comment]
Я заколебался этим заниматься
Долго и муторно

Проще свою копию сдмм создать, удаляющую ненужные переменные
