### ISSUE TITLE
Баг: в лодауте нет меню "ксено"

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1933]
**Ckey**:
`gq0k`

**Шаги:**
1. зайти на сбей.
2. зайти в лодаут.
3. обнаружить, что в перечне вещей нет вкладки "ксено" и вещей из неё

**Реальное поведение:**
Нет вкладки "ксено" и её содержимого

**Ожидаемое поведение:**
Вкладка и/или её содержимое должно быть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216018363826962452)

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/13716708-a043-49bf-9bb9-ced4c53e0d31)
