### ISSUE TITLE
Карта: Не хватает лампочек в каморке уборщика

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1947]
**Название:**
`лампочка`

**Дополнительная информация:**
Не хватает лампочек в каморке уборщика. Пара коробок с запасными лампами - сойдет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216055130378600589)

**Comment by MGWhiskers** [comment]
ишшуй либо был когда то адресован, либо не имел смысла изначально.
в коморке уборщика два кустодиал клозета. в каждом по одному заменителю ламп, которые универсальны.

"пара коробок" не сойдет, потому что по сиерре минимум три типа ламп можно найти в работе.
можно было бы мапнуть листов стекла для заменителей но у уборщика есть доступ по техам, там спокойно можно найти стопки стекла, на крайний - иц спросить.
