### ISSUE TITLE
Баг: Неработают кнопки створок склада исследователей

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1951]
**Ckey**:
`gq0k`

**Шаги:**
1. Прийти в ангар
2. Нажать на кнопку
3. Ничего.

**Реальное поведение:**
Ничего не происходит

**Ожидаемое поведение:**
Створки должны открыться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216080038966071369)

**Comment by LordNest** [comment]
Пофикшено кем-то, когда-то
