### ISSUE TITLE
Баг: Отсуствует консоль переработки ресурсов у конвеерной ленты, в ангаре

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1952]
**Ckey**:
`Lexanx`

**Шаги:**
Собрать ресурсы.
Попытаться их обработать в ангаре

**Реальное поведение:**
Нет консоли

**Ожидаемое поведение:**
Есть консоль
<hr>

*Репорт сгенерирован автоматически*
*Автор: `.bord` / `194199285083013120`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216082447767437332)

**Comment by LordNest** [comment]
Решено кем-то, когда-то
