### ISSUE TITLE
Баг: Сломались Вайтлисты

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1954]
**Ckey**:
`Nicknam`

**Шаги:**
1. Зайти в сетап.
2. Не найти доступа к твоим расам.

**Реальное поведение:**
Не работают вайтлисты на ксеносов

**Ожидаемое поведение:**
Ксеносы должны были быть открыты!
<hr>

*Репорт сгенерирован автоматически*
*Автор: `helsog` / `168599447452778496`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216094805235339417)

**Comment by LordNest** [comment]
@UEDCommander выглядит как критичное, если пофиксили - закройте пж
