### ISSUE TITLE
Карта: Атмосферные датчики в баках с газами в атмосе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1956]
**Название:**
`gas analyzer (или как то так)`

**Дополнительная информация:**
Без сканеров не видно находящихся внутри газов. Это критично для атмосферного отсека.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `shap04ka` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216126445785714809)

**Comment by MGWhiskers** [comment]
ишшуй давно решен.
каждый танкер газа в атмосе имеет газовый сенсор и связан с соответствующей консолью
