### ISSUE TITLE
Карта: Нет трубы в баре

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1958]
**Название:**
`disposal pipe segment`

**Дополнительная информация:**
В баре нет мусорной трубы из за чего все вылетает в стену. Непорядок
<hr>

*Репорт сгенерирован автоматически*
*Автор: `shap04ka` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216143028482342973)

**Comment by MGWhiskers** [comment]
в зоне бара z2 и z3 не наблюдаю проблем, либо уже было адресовано, либо иц повреждения приняты за проблемы с мапой
