### ISSUE TITLE
Механ: Крайне медленная смерть

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#196]
**Название:**
`Мозг и урон по нему от различных состояний`

**Дополнительная информация:**
Сила урона по мозгу и скорость смерти чувствуется, что сместилась в более лёгкую сторону. Кукла умирает в разы медленнее. Причина: скорее всего не прописан урон мозгу от боли
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1089525633459159211)

**Comment by LordNest** [comment]
Закрываем по причине отсутствия точных данных. 
Это необходимо будет, как и проблему с аугментами смотреть с большей выборкой. 
В таком виде - нет смысла балансить.
