### ISSUE TITLE
Карта: Отсутствуют сенсоры газа внутри хранилищ газов в атмосферном отсеке

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1968]
**Название:**
`gas sensor`

**Дополнительная информация:**
Из-за отсутствия сенсоров консоли газовых хранилищ пишут, что газа внутри них нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `thermeng` / `394904046994980867`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216177120858865775)

**Comment by MGWhiskers** [comment]
этот ишшуй дублирует ишшуй #1956 
фактическая проблема мапы давно адресована
