### ISSUE TITLE
Запрос: Юнит тесты таяр и резоми

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#197]
**Название:**
`tajara, resomi`

**Дополнительная информация:**
Нужны юнит-тесты аналогично хумановским
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1089547521417809990)

**Comment by cuddleandtea** [comment]
Что такое юнит-тесты?

**Comment by SuhEugene** [comment]
> Что такое юнит-тесты?

Автоматические тесты различных модулей кода.
![image](https://user-images.githubusercontent.com/32931701/228541206-484cea01-6df5-45df-a1ab-6d22861a88d8.png)
Они проверяют то, что код работает правильно. Что он с различными входными данными выдаёт правильный выходные.

<hr />

![image](https://user-images.githubusercontent.com/32931701/228541486-d8140864-9a33-4bb7-8aaf-be4b6e7a63d1.png)
Это - тесты дамага по расам и среди этих тестов нет таяр и резоми. Нужно будет им добавить такие же.


На самом деле тестов там куча. Они проверяют правильно ли маппер разложил провода на карте, не забыл ли маппер использовать все существующие зоны (иначе зачем они нужны в коде?), правильно ли расположил эти зоны.
Юнит-тесты проверяют есть ли иконки у всех предметов лодаута и правильно ли настроены предметы лодаута. У всех ли постеров есть иконки, у всех ли роботов есть глаза
(даже такая проверка, кекв   ![image](https://user-images.githubusercontent.com/32931701/228542355-7dff191f-98fe-4a75-9ab1-fade9115de2d.png)).
Правильно ли атмос смешивает газы, правильно ли... ну, короче, наверное суть ты уловил. Все тесты, которые есть сейчас можно глянуть [в различных ПРах](https://github.com/SierraBay/SierraBay12/actions/runs/4534997622/jobs/7989920427)
Достаточно открыть тест и раскрыть список `Run Tests`.

<hr />

Короче говоря, юнит-тесты, которые помогают мапперам, спрайтерам и кодерам не совершить простейшие тупые ошибки ***и не только***.
