### ISSUE TITLE
Механ: Send back to lobby 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#198]
**Название:**
`Player Panel`

**Дополнительная информация:**
Очень удобная функция для админов в случае с невыставлением скиллов и прочего 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1089566602325930004)

**Comment by SuhEugene** [comment]
https://user-images.githubusercontent.com/32931701/227933241-35c031f7-cd99-4690-8701-4ce4b91e5edf.mp4
