### ISSUE TITLE
Карта: Отсутствует шлюз на входе в медблок со стороны каб. психолога

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1980]
**Название:**
`airlock`

**Дополнительная информация:**
:)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `herrjagerr` / `458567647357960202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216451765508116640)

**Comment by MGWhiskers** [comment]
Г-образный корридор в медблоке является проходным, в добавлении аирлока под мед доступом в один из его концов не вижу никакого смысла
