### ISSUE TITLE
Карта: В химии меда нет холодильника

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1983]
**Название:**
`smart fridge`

**Дополнительная информация:**
Вместо холодильника в меде находится стена
<hr>

*Репорт сгенерирован автоматически*
*Автор: `herrjagerr` / `458567647357960202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216453911758770291)

**Comment by MGWhiskers** [comment]
давно адресовано, холодильник был откопан из под стены и подпёрт стеклодверью
