### ISSUE TITLE
Баг: мелкобаг мапы - кресло в экспедиторской развёрнуто не в ту сторону

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#1997]
**Ckey**:
`gq0k`

**Шаги:**
1. зайти в экспедиторскую
2. кресло стоит не спиной к стеклу, а лицом

**Реальное поведение:**
кресло должно стоять нормально

**Ожидаемое поведение:**
кресло не стоит нормально
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gq0k` / `416527063642800149`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216774880582832199)

**Comment by LordNest** [comment]
Ну поверни ты кресло
![image](https://github.com/user-attachments/assets/2e05be2c-b874-4cc4-ba35-957ba7f4113c)
