### ISSUE TITLE
Карта: Миссклик мапера

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2000]
**Название:**
`paper bin`

**Дополнительная информация:**
Лежит тут уже не первый раунд, врядли кто-то нарошно выкатывает
<hr>

*Репорт сгенерирован автоматически*
*Автор: `honkemo` / `598615241185689661`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1216837048330092615)

**Comment by MGWhiskers** [comment]
адресовано в пр #2280
