### ISSUE TITLE
Карта: Отсутствие гравитации в шлюзе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2009]
**Название:**
`petrow acces`

**Дополнительная информация:**
Шлюз из ангара в техи к входу на Петров не имеет на своём тайле гравитации.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1217477998878654484)

**Comment by LordNest** [comment]
Не вижу криминала вообще. Над проверить, но вроде как закрыть бы

![image](https://github.com/user-attachments/assets/2f138443-e569-4dcc-9b35-f6d834b2e7a9)

**Comment by LordNest** [comment]
Не воспроизводится.
