### ISSUE TITLE
Баг: В заказах карго нету стазисных мешков

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2018]
**Название:**
`stasis bugs`

**Дополнительная информация:**
Через карго нельзя заказать стазис мешки по причине их полного отсутствия в списке доступных предметов. Теперь медики и ЭК могут только довольствоваться двумя мешками из склада.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `deadgameofficial` / `314788151627612160`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1218092576096387145)

**Comment by LordNest** [comment]
Выглядит закрытым
