### ISSUE TITLE
Баг: Нельзя зайти за ремонтного дрона (мелкого)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2026]
**Ckey**:
`IQ_Gamer`

**Шаги:**
1. Нажать кнопку "Join As Drone" будучи призраком
2. That verb is not currently permitted.

**Реальное поведение:**
Ничего не происходит

**Ожидаемое поведение:**
Игрок становится ремонтным дроном Сиерры
<hr>

*Репорт сгенерирован автоматически*
*Автор: `thermeng` / `394904046994980867`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1218436299585749002)

**Comment by LordNest** [comment]
Дубликат #1315
