### ISSUE TITLE
Баг: Не работают кнопки (Tajara) veil, science и (Tajara) visor, science

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2027]
**Ckey**:
`Vipo24`

**Шаги:**
1. Выбрать данные вещи в Loadout, имея у себя таярскую расу, во вкладке Glasses and Eyewear

**Реальное поведение:**
Кнопка не нажимается

**Ожидаемое поведение:**
Кнопка нажимается и выбирается предмет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1218562310600130643)

**Comment by LordNest** [comment]
Дубликат #2117 (да я беру то, что новее)
