### ISSUE TITLE
Баг: Не работают худ импланты.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2035]
**Ckey**:
`Klearch`

**Шаги:**
1. Нажать на кнопочку активации импланта.
2. Смотреть на мир вокруг
(Проверено на импланте мед худа)

**Реальное поведение:**
Имплант ничего не меняет

**Ожидаемое поведение:**
Должны показаться дополнительные данные
<hr>

*Репорт сгенерирован автоматически*
*Автор: `klearch` / `420556144960864276`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1219460106106966046)

**Comment by LordNest** [comment]
Ну видимо пофикшено. Не воспроизводится. 
![image](https://github.com/user-attachments/assets/b439d2c0-dcfb-4c8a-a198-3a1bd7ae3ef1)
![image](https://github.com/user-attachments/assets/e3ab7680-163d-4feb-9f9e-6309cbf0d8e9)
