### ISSUE TITLE
Баг: У формы адъютанта для резоми сломан спрайт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2061]
**Ckey**:
`Farwa87`

**Шаги:**
1. Зайти за резоми-адъюху
2. Офигеть от серого кривого спрайта

**Реальное поведение:**
Спрайт сломан

**Ожидаемое поведение:**
Спрайт должен быть нормальным
<hr>

*Репорт сгенерирован автоматически*
*Автор: `ratatet` / `186559014581043202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1222026634337456188)

**Comment by LordNest** [comment]
Говорят закрыто.
