### ISSUE TITLE
Запрос: Звук перекладывания предмета

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#208]
**Название:**
`---`

**Дополнительная информация:**
При перекладывании предмета из руки в руку никакого звука воспроизводиться не должно. Аналогично со снятием предмета.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1090970570079875143)

**Comment by cuddleandtea** [comment]
Я слишком слаб

**Comment by cuddleandtea** [comment]
Закрыли работу по звукам
