### ISSUE TITLE
Механ: работа контура аледн-сараспова на планетах

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2084]
**Название:**
`alden-saraspova counter`

**Дополнительная информация:**
Контур должен показывать растояние к крупным и малым объектам, именуя так же крупный объект по типу "сигма-222". Контур не работает на планетах, аномалии и артефакты приходится искать вручную.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `lobster7496` / `358545028106420224`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1224832609398554764)

**Comment by LordNest** [comment]
Дубликат #2011
