### ISSUE TITLE
Карта: У СМО нет кнопок

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2088]
**Название:**
`switch`

**Дополнительная информация:**
У СМО в кабинете нет ни ставней, ни возможности затемнить окна, ни кнопки для открытия двери в свой кабинет со стула.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `herrjagerr` / `458567647357960202`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1225514243051487294)

**Comment by MGWhiskers** [comment]
у смо теперь до жопы кнопок. адресовано в прах #2280 #2269 
кнопка открытия входа в свой кабинет будет в будущем пре
