### ISSUE TITLE
Карта: Отсутствует внешний охладитель для ИПС/ППТ в робототехнике.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2092]
**Название:**
`external cooling device`

**Дополнительная информация:**
На лайве был, на Сьеррабее его нет. Должен быть.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1225777842822844458)

**Comment by MGWhiskers** [comment]
пр #2280 добавил External Cooling Device по координатам х120 y090 z3
