### ISSUE TITLE
Карта: Нет утюга в прачечной

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2107]
**Название:**
`Iron`

**Дополнительная информация:**
В прачечной на судне не утюга. Как гладить теперь одежду?
<hr>

*Репорт сгенерирован автоматически*
*Автор: `darkman24rus` / `244108882199183361`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1227993816745906269)

**Comment by MGWhiskers** [comment]
зона "Second Deck - Laundry Room" содержит два утюга.
