### ISSUE TITLE
Старый спрайт: Хранилище скафандра

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#211]
**Объект:**
Хранилище скафандра

**Название:**
`Voidsuit Storage Unit`

**Дополнительная информация:**
На текущей Сиерре хранилища выглядят симпатичнее и новее, чем на бееСиерре.
Нужный красивый спрайт лежит вот тут: \infinity\icons\obj\suitstorage
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Remission#3553` / `226681284594892800`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1091407786002366494)

**Comment by LordNest** [comment]
Я иссуй вотчер, работаю три дня, без зарплаты. Я это уже пофиксил
