### ISSUE TITLE
Баг: пИИ умирает

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2143]
**Ckey**:
`Vipo24`

**Шаги:**
1. Засунуть пИИ в деструктор в РнД и короче там смешное

**Реальное поведение:**
Происходит то что ниже

**Ожидаемое поведение:**
То что ниже не должно происходить никогда
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1230949946203836447)

**Comment by LordNest** [comment]
пИИ внезапно умер после того, как его поместили в анализатор с автоматическим деструктом. ХММММ

![image](https://github.com/user-attachments/assets/5d5445aa-8788-4bb3-88bc-7c21ca85819a)
