### ISSUE TITLE
Карта: Обогреватели сауны настроены на 75 градусов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2147]
**Название:**
`stationary space heater`

**Дополнительная информация:**
Лучше оставить обогреватели выключенными и настраиваемыми посетителями - а то за тоеру зашёл и умер и сгорел и умер и сгорел и умер и взорвался и сгорел в пепел
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1230990727585206424)

**Comment by LordNest** [comment]
Зачем кошки ходят в баню. Они же утеплённые.

**Comment by LordNest** [comment]
Дубликат. Более актуальное - #2555
