### ISSUE TITLE
Карта: Створки суперматерии странно закрываются

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2167]
**Название:**
`Reactor Blast Door`

**Дополнительная информация:**
Проблема изложена на скрине. Коллекторам радиации не обязательно, чтобы окна были открыты, так что возникает странный момент - получается, камера ядра стеклянная способна треснуть в любом случае от температуры, щёлкай ты створки или нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1232397157835739268)

**Comment by MGWhiskers** [comment]
ишшуй не релевантен, бластдоры и их привязка по кнопкам абсолютно исправны
