### ISSUE TITLE
Объект: Металлодетекторы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2169]
**Объект:**
Металлодетекторы

**Название:**
`Security Scanner`

**Дополнительная информация:**
Отсутствуют на карте в привычных местах (доки, бриг, мостик)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1233021934892093520)

**Comment by LordNest** [comment]
Детекторы специально убирали с карты, закрывайте @AmShegars работай давай
