### ISSUE TITLE
Старый спрайт: Кожаные крафтящиеся карманы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2176]
**Объект:**
Кожаные крафтящиеся карманы

**Название:**
`pockets`

**Дополнительная информация:**
Спрайт отсутствует
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1233030175755735060)

**Comment by NeonNik2245** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/106491639/e252fa41-e619-485d-ae14-884600110fb4)
