### ISSUE TITLE
Карта: Шлюз прохода в камерную зону брига имеет ошибку в написании. LonT term checkpoint

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2259]
**Название:**
`Шлюз Lont Term Checkpoint`

**Дополнительная информация:**
Шлюз Lont Term Checkpoint с ошибкой, должно быть Long Term Checkpoint
<hr>

*Репорт сгенерирован автоматически*
*Автор: `4nt1flesh` / `368048094757257216`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1245083177127772205)

**Comment by NeonNik2245** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/106491639/ac4cc1e0-8013-40eb-809f-d18fa0e318dd)
Уже пофиксили
Закрывайте ишуй
