### ISSUE TITLE
Баг: Не работает выбор оперативника

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2297]
**Ckey**:
`KOJIECO`

**Шаги:**
1. Получить ниндзю.
2. Выбрать набор ниндзи.
3. Посмотреть в пустой ящик ниндзи.

**Реальное поведение:**
При попытке выбрать один из китов ниндзи, получаем пустой ящик в 5 случаях из 5.

**Ожидаемое поведение:**
Должен заспавниться ящик с необходимым оборудованием. Наборы оборудования можно посмотреть здесь: https://baystation.xyz/index.php?title=Operative
<hr>

*Репорт сгенерирован автоматически*
*Автор: `superkojieco` / `233629146981335041`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1247600102663651451)

**Comment by cuddleandtea** [comment]
Довольно простой ишью. Возьмите попрактиковаться. 
Предмет для поиска и сравнения с беем https://github.com/baystation12/baystation12
/obj/item/selection/ninja 
Надо посмотреть почему у нас не происходит спавн вещей и сделать фикс. Я думаю, что какой-то модуль мешает и перезаписывает состояние, так как на бее всё работает
