### ISSUE TITLE
Баг: Белый нотес у авейки

### ISSUE THREAD

**Issue by Vapiq** [SierraBay/SierraBay12#2334]
**/Ckey:**
`Pers`

**Шаги:**
1. Зайти за авей роль
2. Нажать на notes вкладке IC
3. Увидеть пустое, белое окно

**Реальное поведение:**
Показывает пустое окно

**Ожидаемое поведение:**
Должно быть информация о пароле и имя банковского аккаунта

**Comment by Vapiq** [comment]
[/репорт баг](url)

**Comment by LordNest** [comment]
Имеет дубликат
