### ISSUE TITLE
Баг: Бесплатные блюспейс кристаллы

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2385]
**Ckey**:
`Vipo24`

**Шаги:**
1. Разблокировать блюспейс кристаллы в НИО
2. Найти их в меню протолата

**Реальное поведение:**
Они ничего не расходуют

**Ожидаемое поведение:**
Они расходуют хоть что-то
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1254070884788867073)

**Comment by Teteshnik1** [comment]
ПР о исправлении бага отправил. Ожидайте
