### ISSUE TITLE
Баг: Guest Pass Terminal барахлит при возврате ID

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#241]
**Ckey**:
`Atufancheg`

**Шаги:**
1. Вставить в Guest Pass Terminal карту
2. Заполнить данные для гостя
3. Попытаться достать свой ID

**Реальное поведение:**
вылезает окошко ошибки

**Ожидаемое поведение:**
возврат ID
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Atufancheg#7790` / `260139717121540107`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1093083019855802401)

**Comment by cuddleandtea** [comment]
Не смог пофиксить, перенеся актуальный код с оверлеем guestpass с сьерры. 
![image](https://user-images.githubusercontent.com/105150564/230715736-e0535b52-77a3-4eab-a6f3-22b49a9de888.png)

**Comment by cuddleandtea** [comment]
Не смог пофиксить :с

**Comment by LordNest** [comment]
https://github.com/Baystation12/Baystation12/pull/33312
Исправлено на оффбее.
Наш миррор #425

**Comment by LordNest** [comment]
Или это не оно. Возможно не оно.

**Comment by SuhEugene** [comment]
Уже пофикшено кста, на оффах приняли ПР с фиксом
