### ISSUE TITLE
Запрос: У полевого инженера есть навык медицины

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2444]
**Название:**
`навык medicine у field engineer`

**Дополнительная информация:**
У полевого инженера ЭК теперь откуда-то появился базовый навык медицины, что априори ему не требуется в работе, в особенности когда он занят инженерным делом. И этот же самый навык стоит по умолчанию, и убрать его нельзя
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1260204176424570915)

**Comment by UEDCommander** [comment]
Не ишшуй, базовая медицина есть у всего состава ЭК вследствие их подготовки. Изменять через предложку.
