### ISSUE TITLE
Объект: Баллистический щит на меха

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2489]
**Объект:**
Баллистический щит на меха

**Название:**
`exosuit ballistic shield`

**Дополнительная информация:**
Отсутствует в ветки Робототехники
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1263529332983464012)

**Comment by Pivo24** [comment]
Ишшуй надо закрыц, моя вина не увидел
