### ISSUE TITLE
Объект: Отсутствует переработчик воды в водород+кислород

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2499]
**Объект:**
Отсутствует переработчик воды в водород+кислород

**Название:**
`molecular cracking unit`

**Дополнительная информация:**
Создавалось в РнД наравне с doppler array, машинка была прикольная
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1264185332484800573)

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/2bcb92a7-148e-4863-8146-f1ea0670224f)
