### ISSUE TITLE
Баг: Заказ "Liguid - Fuel tanks" привозит 4 бака водорода

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2505]
**Ckey**:
`Vipo24`

**Шаги:**
1. В разделе Atmospherics программы заказов смотрим в самый низ на заказ топливных баков
2. Жмак по Contents

**Реальное поведение:**
4 hydrogen tanks

**Ожидаемое поведение:**
обычно ничего не пишет из-за того, что топливные баки - не предметы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1264225930860298373)

**Comment by Baneuus** [comment]
![image](https://github.com/user-attachments/assets/e166ca91-faeb-46ea-85ec-2a804151b750)
Не баг, закрывай
