### ISSUE TITLE
Запрос: Слишком **горячая** сауна

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2555]
**Название:**
`stationary space heater, Second Deck - Living - Sauna Air Alarm`

**Дополнительная информация:**
Для некоторых рас температура по умолчанию в сауне слишком высокая. При этом уменьшать температуру довольно муторно, ведь можно это сделать только путём "проветривания", который постоянно прерывает закрывание дверей. Лучше отключить нагреватели по умолчанию и опустить температуру в помещении до 20 градусов, чтобы все те кто не хочет высокой температуры ничего не трогали бы, а те кто хочет - просто включили бы обогреватели
<hr>

*Репорт сгенерирован автоматически*
*Автор: `tenebriscattus` / `430069039918743573`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1266530088246181948)

**Comment by LordNest** [comment]
[КОММЕНТАРИЙ ИЗЪЯТ ПО ОБРАЩЕНИЮ КОМИССИИ ПО ЭТИКЕ]

Межвидовая кооперация и взаимное уважение - незыблемый столп корпоративной этики
