### ISSUE TITLE
Баг: Генераторы щита в РнД не прикручиваются

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2586]
**Ckey**:
`Vipo24`

**Шаги:**
1. Зайти в комнату РнД с газовой камерой
2. Попробовать прикрутить генераторы щита

**Реальное поведение:**
Ничего не происходит

**Ожидаемое поведение:**
Гаечный ключ фиксирует геники на полу, и ими можно оперировать
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1269211555577462836)

**Comment by LordNest** [comment]
Лейбл РнД потому что оно в РнД. Вероятно проблема конечно не в том, что отдел проклят.

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/ef07f858-a4d7-42b4-b2f7-ad7135b5964c)
Да нет, даже отдел не проклят
