### ISSUE TITLE
Проверить и исправить неприкрученный к стене... ??? у матери (см скрин)

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#26]
![Image](https://user-images.githubusercontent.com/32931701/218326388-bda137ae-db31-496b-a1b3-0a6bb911deae.png)

**Comment by LordNest** [comment]
Типа такого

![Image](https://user-images.githubusercontent.com/77477080/219716124-10bc8716-9829-4a77-a116-a36fdcf34282.png)

**Comment by LordNest** [comment]
#34 резолв
