### ISSUE TITLE
Баг: Не работает аугмент гасителей блика из лодаута

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2604]
**Ckey**:
`Bosch_Drill`

**Шаги:**
1.Выбрать аугмент гасителей блика
2.Зайти в раунд за полевого инженера ЭК

**Реальное поведение:**
Кнопки использования гасителя бликов нету

**Ожидаемое поведение:**
Кнопка гасителя бликов есть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1272550186031251457)

**Comment by LordNest** [comment]
Выглядит как очередные пендосские приколы

**Comment by LordNest** [comment]
Ну видимо пофикшено. Не воспроизводится. 
![image](https://github.com/user-attachments/assets/b439d2c0-dcfb-4c8a-a198-3a1bd7ae3ef1)
![image](https://github.com/user-attachments/assets/e3ab7680-163d-4feb-9f9e-6309cbf0d8e9)
