### ISSUE TITLE
Карта: Отсутствует устройство аутентификации в кабинете главврача.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2607]
**Название:**
`keycard authentication device`

**Дополнительная информация:**
Его буквально нет, а должно быть.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `veeqies` / `339720708496031746`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1272964692138135686)

**Comment by Teteshnik1** [comment]
Кнопку добавил в ПРе, ждем мержа...
