### ISSUE TITLE
Баг: VOID-shift phase projector: Emergency Leap ниндзи не работает

### ISSUE THREAD

**Issue by KOJIECO** [SierraBay/SierraBay12#2624]
### Description of issue

VOID-shift phase projector: Emergency Leap ниндзи не работает в лежачем положении.

### Difference between expected and actual behaviour

Реальное поведение:
VOID-shift phase projector: Emergency Leap требует нахождении в положении стоя, чтобы его использовать.

Ожидамое поведение:
VOID-shift phase projector: Emergency Leap телепортирует в случайное место при нажатии на него из любого положения.

### Steps to reproduce

1. Стать оперативником.
2. Надеть ominous suit control module
3. Разложить костюм.
4. Лечь.
5. Попытаться заюзать VOID-shift phase projector: Emergency Leap

### Specific information for locating

Item name: ominous suit control module (вроде obj/item/rig/ninja)

### Client version, server revision, & game ID

SierraBay

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Teteshnik1** [comment]
Ну ждите мержа.
![image](https://github.com/user-attachments/assets/f9b84ca3-9c87-47e6-8a97-b092eab556df)
