### ISSUE TITLE
Карта: Дверь в туалет на либерии стоит горизонтальная, вместо вертикальной

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2654]
**Название:**
`Toilet`

**Дополнительная информация:**
Крайне сильно выделяется, когда кто-то заходит в  ванную на либерии. Остальные двери стоят по своей горизонтали
<hr>

*Репорт сгенерирован автоматически*
*Автор: `bosch_drill` / `529369860996726785`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1281359893143486637)

**Comment by LordNest** [comment]
Hm... Hmmmm... Ну что сказать, ну на маппинге всё окей

![image](https://github.com/user-attachments/assets/6d12fd63-e264-44ae-a76c-05ec5760568a)
