### ISSUE TITLE
Вытащить алярму из-за бочек

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#27]
![Image](https://user-images.githubusercontent.com/32931701/218326403-61584365-f601-44be-9061-ca7eacd21159.png)

**Comment by LordNest** [comment]
Ну типа 

![Image](https://user-images.githubusercontent.com/77477080/219713241-d3897e14-0428-4f53-b5ce-292d88d61e7d.png)

**Comment by LordNest** [comment]
#34 резолв

**Comment by LordNest** [comment]
#34  резолв
