### ISSUE TITLE
Запрос: лодаута нема

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#270]
**Название:**
`Лодаут...`

**Дополнительная информация:**
Не хватает очков лодаута что бы нормально дать персонажу вещей, к примеру баланса. у нас 10 очков, 2 стоит крестик, 3 плащ, вот тебе и на декор половина очков
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094293132566347827)

**Comment by SuhEugene** [comment]
Настраивается в конфиге. Зарепортить азизу при релизе.
