### ISSUE TITLE
Звук: Звуки мелочёвки РНД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#274]
**Название:**
`micro-manipulator`, `capacitor`, `micro-laser`

**Дополнительная информация:**
Звуки вообще неподходящие и надо найти какой-то звук именно вот такой металлической мелочи
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094297935979741345)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
