### ISSUE TITLE
Запрос: see_invisible не фиксируется

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2744]
**Название:**
`see_invisible`

**Дополнительная информация:**
see_invisible в VV должно позволять задавать слои, которые видит челик, чтоб, соответственно, делать так, чтоб он мог видеть больше или меньше вещей с разными параметрами invisibility. Сейчас же си_инвизибле автоматически сбрасывается до дефолтных значений каждый тик, из-за чего приколы не получаются. Хотелось бы иметь возможность отключить постоянное обновление, как было на инфинитях...
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1299086673073668097)

**Comment by Builder-13** [comment]
А как его можно было отключить?

**Comment by Builder-13** [comment]
Нашел
