### ISSUE TITLE
Звук: Листы форона

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#276]
**Название:**
`phoron crystals`

**Дополнительная информация:**
Звук говно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094298466651484261)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
