### ISSUE TITLE
Запрос: У бармена нет Кассет

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#277]
**Название:**
`Dust tape`

**Дополнительная информация:**
Бармену при спавне дается контейнер с 2 кассетами и отверткой, тут их нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094298643076489351)

**Comment by cuddleandtea** [comment]
Ишью закрыт
