### ISSUE TITLE
Баг: Набор криминалиста не работает.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2799]
**Ckey**:
`Baneuus`

**Шаги:**
1. Взять fingerprint powder или fiber collection kit
2. Потыкать по предметам.

**Реальное поведение:**
Ничё не берётся, но любой предмет пихается в high powered electron microscope

**Ожидаемое поведение:**
Эти предметы должны собирать отпечатки и волокна с предметов соответственно, а в микроскоп должны пихаться только образцы.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1302371926013903011)

**Comment by AmShegars** [comment]
![image](https://github.com/user-attachments/assets/1aeefe77-fd5a-4515-ba8f-249b8d65d0f6)
