### ISSUE TITLE
Карта: На дереликте Mininghome слишком много инструментов.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#280]
**Название:**
`Diamond drill, Advanced mining drill`

**Дополнительная информация:**
На карте мало того, что присутствует готовый экзокостюм, который позволяет опустошать всю карту, которая спавнится автоматически в соседнем секторе от Сьерры, так ещё и присутствуют две версии улучшенных дрелей, которые позволяют не брать мех с конечной головкой дрели, а просто копать малмазным буром с бешеной скоростью. Считаю что это слишком упрощает шахте жизнь.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LordNest#5211` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094300607537479771)

**Comment by LordNest** [comment]
Оффы решили что это чилльная карта должна оставаться чилльной. So be it. Я обязательно доберусь до реворка шахты, но не сейчас.
