### ISSUE TITLE
Баг: Невозможность открыть аплинк

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#281]
**Ckey**:
`GeroZer0`

**Шаги:**
1. Получить трейтора
2. зайти в приложение Такс что то там
3. Ввести код
4. ничего не вышло, вы как всегда молодец

**Реальное поведение:**
Экран КПК краснеет, и то во время ввода, после исчезает

**Ожидаемое поведение:**
Аплинк, нелегал, наркотики и голые таяры
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094301367830581299)

**Comment by LordNest** [comment]
Не воспроизводится
