### ISSUE TITLE
Баг: Инфотехническая команда locate не работает

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2821]
**Ckey**:
`Baneuus`

**Шаги:**
1. Пикнуть инфотехника.
2. Открыть терминал с помощью проги
3. Вписать locate и айди любого устройства

**Реальное поведение:**
Пишет что команда не найдена или типа того, но при использовании man locate оно говорит, что такая команда есть и всё ок

**Ожидаемое поведение:**
должно указывать где находится устройство, которое пробивают
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1303488986571870214)

**Comment by Builder-13** [comment]
Работать команда должна только на мастере информационного
