### ISSUE TITLE
Звук: Звкук фруктов(я не знаю точно их количество)

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#283]
**Название:**
`Точно lemon, lime, apple, orange`

**Дополнительная информация:**
Звук поднятия травы у всех трех, АУДИО и фото прилагается 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094302746276008027)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
