### ISSUE TITLE
Звук: Звук поднятия сигареты

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#284]
**Название:**
`cigarette`

**Дополнительная информация:**
Звук не подходит, звучит, как будто трясу коробку печенья
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094303235789037638)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
