### ISSUE TITLE
Звук: Звук поднятия помады

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#285]
**Название:**
`Помада`

**Дополнительная информация:**
Звук звучит, будто я поднимаю тяжелый инструмент
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094303447978885261)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
