### ISSUE TITLE
Баг: У мулов нет латентной псионики

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2859]
**Ckey**:
`KOJIECO`

**Шаги:**
1. Создать персонажа человека-мула.
2. Зайти в раунд
3. Не обнаружить у персонажа латентной псионики

**Реальное поведение:**
У мула нет латентной псиониким

**Ожидаемое поведение:**
У персонажа человека-мула должен спавниться рандомный подвид псионики на уровне "latent".
<hr>

*Репорт сгенерирован автоматически*
*Автор: `superkojieco` / `233629146981335041`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1305574957723684915)

**Comment by LordNest** [comment]
А, и наверное оно пофикшено. Магия короче.
