### ISSUE TITLE
Баг: Не грузится содержимое инженерных книжек

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#287]
**Ckey**:
`Atufancheg`

**Шаги:**
в раздевалке инженеров содержимое книжек отображается только в учебнике по атмосу

**Реальное поведение:**
ошибка загрузки содержимого

**Ожидаемое поведение:**
открываться содержимое книги
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Atufancheg#7790` / `260139717121540107`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094304177573867592)

**Comment by ImJustKisik** [comment]
Не баг, просто конфиги не настроены и там нету ссылки на вики
