### ISSUE TITLE
Запрос: Невозможно зафиксировать "Угол" обзора

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#288]
**Название:**
`хз честно`

**Дополнительная информация:**
На сиерре нажав контрл лкм на панельку передвижения появляется глаз, в этом положении ты ходишь боком смотря только в 1 сторону, тут так нельзя
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094304249581670480)

**Comment by SuhEugene** [comment]
Тут можно это сделать, только я не знаю как

**Comment by cuddleandtea** [comment]
На оффбее случайные клики с альтом изменили на комбинацию alt+arrow keys. Это более правльный подход, так как он исключает случайную фиксацию зрения.
