### ISSUE TITLE
Запрос: хирург и СМО имеют скилл виро при химии на базисе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2895]
**Название:**
`всё свазянное с химией, всё связанное с вирусологией, хирург и СМО сразу из крио`

**Дополнительная информация:**
у них всего лишь базис на химии, но у них есть навык вирусологии, либо понизьте требование химии до базиса, либо дайте им химию trained
<hr>

*Репорт сгенерирован автоматически*
*Автор: `engineergaming6172` / `873267562035707936`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1308410196342734923)

**Comment by Teteshnik1** [comment]
Вот бы люди с кнопками отменили ишшуй.
