### ISSUE TITLE
Баг: Не работает Grant Full Access

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#2899]
**Ckey**:
`Baneuus`

**Шаги:**
1. Врубить дебаг вербы
2. Выбрать персонажа
3. ПКМ -> Grant Full Access

**Реальное поведение:**
ничё не происходит

**Ожидаемое поведение:**
должен даваться полный доступ к кораблю
<hr>

*Репорт сгенерирован автоматически*
*Автор: `baneuus` / `324205269901115392`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1308903467477237802)

**Comment by AmShegars** [comment]
![image](https://github.com/user-attachments/assets/775857ef-4bd8-4dc3-a42f-b68ff541a7d1)
