### ISSUE TITLE
Звук: Звук поднятия обуви

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#291]
**Название:**
`Обувь`

**Дополнительная информация:**
Звук звучит очень странно, не подходяще
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094306537985544262)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
