### ISSUE TITLE
Старый спрайт: Невидимый инженерный берет

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#292]
**Объект:**
Невидимый инженерный берет

**Название:**
`corporate engineering beret`

**Дополнительная информация:**
Он как бы есть, но его как бы нет. Спрайта не отображается ни для айтема, ни онмоб
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Remission#3553` / `226681284594892800`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094307471415312454)

**Comment by cuddleandtea** [comment]
На оффбее такого айтема нет. Смотрю по нашим файлам

**Comment by cuddleandtea** [comment]
Оффбей: /obj/item/clothing/head/beret/engineering 
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/dae6d342-6427-438f-8bee-450cc11b3572)

**Comment by cuddleandtea** [comment]
Сырбей: /obj/item/clothing/head/beret/engineering
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/a3d012c2-6306-4c96-82ca-78275fdbe77d)

**Comment by cuddleandtea** [comment]
проблемы нет, берет в шкафчике так же имеет спрайт
