### ISSUE TITLE
Объект: Автомат с улучшениями для ПИИ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#293]
**Объект:**
Автомат с улучшениями для ПИИ

**Название:**
`personal AI device.`

**Дополнительная информация:**
Автомат раньше стоял на складе инструментов, может и есть в коде, но на карте нету
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094307773732364460)

**Comment by LordNest** [comment]
Автомат и пИИ имеют очень ограниченный функционал, которым пользовались крайне редко. Этому автомату и функционалу пИИ, который с этим связан требуется более детальная переработка, нежели просто возвращение автомата. Закрываю иссуй.
