### ISSUE TITLE
Звук: Звук бумаги не подходит для многих предметов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#294]
**Название:**
`Папка, окурок, мешок для мусора, деньги`

**Дополнительная информация:**
Звук очень специфичный и не подходит предметам выше.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094308635770888293)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
