### ISSUE TITLE
Звук: Звук поднятия вилки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#295]
**Название:**
`Вилка`

**Дополнительная информация:**
Звук звучит, как будто я вытаскиваю клинок из ножен, а не поднял пластиковую вилочку со стола
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094309077007482960)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов
