### ISSUE TITLE
Звук: Звук постукивания по стеклу

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#296]
**Название:**
`Стекло`

**Дополнительная информация:**
Звук тихий, можно было бы сделать погромче.

<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094309245282963546)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками предметов

**Comment by SuhEugene** [comment]
Имеет смысл, не относится к той системе звуков

**Comment by cuddleandtea** [comment]
@SuhEugene Проверил. Звук нормальный и не требует доработки. Громкость абсолютно аналогична лайву и оффбею
