### ISSUE TITLE
Звук: Нехватка звуков для смирительной рубашки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#298]
**Название:**
`Смирительная рубашка`

**Дополнительная информация:**
Звука поднятия и опускания смирительной рубашки нету
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094309758384750682)

**Comment by cuddleandtea** [comment]
Закрыли работу над звуками
