### ISSUE TITLE
Запрос: Проблемы с передвижением 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#301]
**Название:**
`нет`

**Дополнительная информация:**
При передвижении иногда просто не хотят нажиматься кнопки, пример. Я на бармене постоянно жму S(вниз) что бы прислонится к стойке, и хожу с зажатой S по сторонам, на сиерре тебе хватает 1 клика для передвижения, тут же этот 1 клик игнорируется и нужно именно зажимать. Вообще эта проблема с диагональным хождением в целом
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094311196921974814)

**Comment by cuddleandtea** [comment]
Проблема из-за ненастроенного конфига. Решится как только встанем под Азизовский хост

**Comment by YegorKandziuba** [comment]
@SuhEugene ишуй не актуален?

**Comment by SuhEugene** [comment]
Я вообще не понял в чём проблема ишью, но скорее всего неактуален.

Если повторяется проблема - можно будет переоткрыть.

**Comment by SuhEugene** [comment]
Дубликатов репортов я не видел, хотя этому ишью 7 месяцев
