### ISSUE TITLE
Баг: Отсутствуют циркуляторы в ящике ТЭГа

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#3016]
**Ckey**:
`Vipo24`

**Шаги:**
1. Знать что в НИО такое не делают
2. Заказать ТЭГ в карго
3. Looks inside

**Реальное поведение:**
no circulators

**Ожидаемое поведение:**
2 circulator boards
<hr>

*Репорт сгенерирован автоматически*
*Автор: `vipo24` / `315564444321054721`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1319359239864582247)

**Comment by LordNest** [comment]
![image](https://github.com/user-attachments/assets/8a354249-42c8-430c-908b-cb399d773ba1)
