### ISSUE TITLE
Звук: Звук кнопки лифта

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#304]
**Название:**
`кнопка лифта`

**Дополнительная информация:**
Звука кнопки лифта нет, у меня всё.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094312677976850522)

**Comment by LordNest** [comment]
Воспроизводится

**Comment by YegorKandziuba** [comment]
@SuhEugene Ишуй не актуален?

**Comment by SuhEugene** [comment]
Скорее всего да. Иначе - переоткрыть можно.
