### ISSUE TITLE
Запрос: Не рассортированный АПЛИНК

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#305]
**Название:**
`Heavy Armor vest and helmet `

**Дополнительная информация:**
Броня находится в DEVICES & TOOLS. Думаю в аплинке все сейчас раскидано куда попало
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094312904901279744)

**Comment by LordNest** [comment]
Пересортирую аплинк и переработаю логику всего режима. Забираю иссуй себе.

**Comment by cuddleandtea** [comment]
Категории "Броня" нет 
Нест работает над введением иного типа режима предатель, так что ишью можно закрыть 
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/5386d613-119d-45fd-b6fa-f5838ee2d15b)

**Comment by cuddleandtea** [comment]
остальное всё рассортировано по стоимости ТК и находится где нужно. Ишью закрываю
