### ISSUE TITLE
Звук: falloff плеера и музыкальных инструментов требует баланс

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#306]
**Название:**
`музыкальные инструменты и tape_player`

**Дополнительная информация:**
У инструментов очень большой радиус и маленький falloff, а у плеера наоборот очень маленький радиус в 4-5 тайлов
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094312976242200627)

**Comment by cuddleandtea** [comment]
Музыкальный плеер - теперь всё окей. Остались только инструменты
