### ISSUE TITLE
Запрос: Прогресс бары не видно за крио

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#308]
**Название:**
`cryo cell`

**Дополнительная информация:**
Начинаешь залазить в крио и прогресс бар залазит за крио.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094315587167064138)

**Comment by cuddleandtea** [comment]
Новый спрайт крио от Ремишн и меня данную проблему не содержит. Проблема не воспроизводится
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/1cc75a8a-3eda-4547-b1eb-449e0ebd4cc6)
