### ISSUE TITLE
Баг: Boo атакует РД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#309]
**Ckey**:
`LordNest`

**Шаги:**
1. Задеклариться за РД
2. Зайти в комнату

**Реальное поведение:**
Boo says "Знаешь куда идёт двоечка дед? Тебе в бороду"

**Ожидаемое поведение:**
Boo мирно ходит по комнате как и должна делать одомашненная инопланетная барашка.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LordNest#5211` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094315882529959986)

**Comment by LordNest** [comment]
Этот баг - критичный, потому что Бу - буквально враждебный моб на месте спавна РД. И это делает невозможной игру за РД.

**Comment by LordNest** [comment]
Проблема во фракции Бу. Фракция "Нейтральный" не нейтральная нихрена
