### ISSUE TITLE
Запрос: microlathe не имеет бикеров

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#310]
**Название:**
`microlathe`

**Дополнительная информация:**
Проблема в том что он не умеет печатать бикеры и другую полезную штуку как на Сиерре, но многое есть
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094318864080326748)

**Comment by cuddleandtea** [comment]
Наши коллеги имеют вполне весомые аргументы против введения печати бикеров на микролате. Я с ними полностью согласен. 
![image](https://github.com/SierraBay/SierraBay12/assets/105150564/b18918a7-8bbf-4043-8a7a-54b977e1297a)

**Comment by cuddleandtea** [comment]
"They're just containers and everyone who needs one usually has st least 3"
