### ISSUE TITLE
Баг: в закладке IC действия для гостов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#316]
**Ckey**:
`atufancheg`

**Шаги:**
1.открыть вкладку IC
2.обнаружить Join Response Team и Join as actor

**Реальное поведение:**
Действия дублируются во вкладке IC

**Ожидаемое поведение:**
Лишних действий во вкладке IC нет
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Atufancheg#7790` / `260139717121540107`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094322940214005910)

**Comment by LordNest** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/77477080/9ecb7579-48c9-4831-b1bc-881c8f87b389)
Всё на месте, воспроизводится.

**Comment by Reishi42** [comment]
https://github.com/Baystation12/Baystation12/pull/34147
