### ISSUE TITLE
Звук: Звук шлюза, когда нету доступа и пытаются зайти

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#319]
**Название:**
`шлюзы`

**Дополнительная информация:**
Звук тиховат по сравнению с другими звуками. Я наушники перекладываю в два раза громче.

<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094324087456796732)

**Comment by cuddleandtea** [comment]
Звук убран на оффбее из-за его мерзотности и оставлен только световой сигнал. Звука нет = ишью нет

**Comment by cuddleandtea** [comment]
И теперь на сырбее звук есть. Но играется он с большой задержкой после первого раза
