### ISSUE TITLE
Запрос: Стальная катана(антага) новая мета

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#320]
**Название:**
`steel katana`

**Дополнительная информация:**
Стальная катана режет ВСЕ И ВСЯ. Деревянная стена - 1 удар. Стальная - 7. Бронировананя штук 30. Удары быстрые, урона много, СТАЛЬНАЯ КАТАНА напомню, стоит в аплинке копейки 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094325988571222116)

**Comment by SuhEugene** [comment]
В [PR#372](https://github.com/SierraBay/SierraBay12/pull/372) повышается резист у стен
Возможно решает проблему

**Comment by LordNest** [comment]
Текущий Item Cost - 24 TK
Всё наследуется от клеймора (базового меча)
Включая фиксы резистов стен - думаю, что проблема пока что решена. Если что, то иссуй переоткроется.
