### ISSUE TITLE
Объект: Мультиметр пропал

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#327]
**Объект:**
Мультиметр пропал

**Название:**
`multimeter`

**Дополнительная информация:**
Если не вернете мультиметр, то заставите страдать всех инженеров мира. К тому же он был на многих авейках и нехило влиял на игровые возможности. Верните.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094549231873831003)

**Comment by LordNest** [comment]
Судя по всему #104 ссылается на ту же самую проблему. Закрываем сто четвёртый
