### ISSUE TITLE
Запрос: Сейврумы в командной программе

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#329]
**Название:**
`/datum/computer_file/program/comm`

**Дополнительная информация:**
У нас в программе командования есть кнопки болтирования и разболтирования сейврумов, но нет сейврумов
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094551038146642010)

**Comment by LordNest** [comment]
Делали, буквально картой
