### ISSUE TITLE
Старый спрайт: Канистры светятся красным цветом по умолчанию

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#330]
**Объект:**
Канистры светятся красным цветом по умолчанию

**Название:**
`canister`

**Дополнительная информация:**
Раньше канистры по умолчанию горели с зеленой лампочкой, а сейчас красной, что не позволяет адекватно понимать их уровень наполненности на глаз.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094552967790723123)

**Comment by SuhEugene** [comment]
Это норма. Они и заполнены не настолько сильно.
