### ISSUE TITLE
Звук: Звук ПМок

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#331]
**Название:**
`ПКМ > PM`

**Дополнительная информация:**
Старый звук ПМок был жестче и внушительнее, от чего непривыкшие нарушители от одного только это звука сжимали свои анусы до размера микрочервоточины и более быстрее шли на контакт с администрацией. Новый звук слишком мягок и гладит уши, от чего нет чувства нависшей угрозы потерять свою нотес-девственность.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094553783142465566)

**Comment by cuddleandtea** [comment]
Обсуждается в миньонах.

**Comment by SuhEugene** [comment]
Обсуждается, значит открыт

**Comment by LordNest** [comment]
Понятия не имею что там наобсуждали до этого. У меня по результатам педальвоута 5/2 в пользу нового звука.
