### ISSUE TITLE
Запрос: Микропроцессор установленный в планшет Командования

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#332]
**Название:**
`/obj/item/modular_computer/tablet/lease/preset/command`

**Дополнительная информация:**
Этот планшет не выдерживает более чем 2 открытых программы одновременно, хотя в нынешней Лайв версии на нем спокойно открывается гораздо больше программ, все из-за возможно более хорошего процессора, или из-за того, что его стандартный процессор стал сам по себе слабее. Раз это командный планшет, то он должен работать достаточно хорошо, а дополнительный микро контроль открываемых приложений только вызывает желание не пользоваться им впринципе, особенно когда тебе надо постоянно из-за бюрократии переключаться между несколькими программами, который хотелось бы всегда иметь открытыми, что бы не сбрасывать то, что ты уже сделал в этой программе. 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094555467042279495)

**Comment by LordNest** [comment]
@YegorKandziuba процессоры идентичные. Или нужно закрыть иссуй или намутить свой проц. Думаю что просто закрыть
