### ISSUE TITLE
Механ: Работа ТЭГов в реакторной

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#333]
**Название:**
`thermoelectric generator`

**Дополнительная информация:**
Ранее порог когда ТЭГи начиани искриться составлял 3000 кВт на ТЭГ. Теперь они искряться при 2000 и выше. Однако на старых ТЭГах был порог максимальной выроботки энергии где-то чуть выше 3000 кВт, от чего они не могли выробатывать более 6000 кВт суммарно. ТЭГи на Сырбее же продолжают адекватно работать и на более высоких нагрузках. Я за буквально 10 лишних минут разогнал их до ~5000 кВт на штуку, от чего мог бы запитать судно напрямую на 10000 кВт, что слишком дохуй. Плюс это не принесло бы никаких плохих последствий. Стоило бы посмотреть детально как реализованы ТЭГи на ФиникСыре и перенести их переработки нам, иначе это сильно ударит по текущему балансу 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094556613102284861)

**Comment by YegorKandziuba** [comment]
Не актуально. СМ теперь работает по другому. Пусть игроки привыкают
