### ISSUE TITLE
Баг: Выроботка СО2 в камере СМ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#334]
**Ckey**:
`KandJX`

**Шаги:**
1. Запустить СМ на водороде, как всегда.
2. Дождаться когда она нагреется достаточно, что бы начались возгорания газа в камере.

**Реальное поведение:**
Когда происходит возгорания, то скорее всего образуется СО2.

**Ожидаемое поведение:**
В СМ мы используем настройку из водорода. СМ при работе выделяет форон и кислород. При возгорании у нас горят Кислород и Водород, от чего должно получаться H2O. Углероду в СМ появиться не может.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094557766154194974)

**Comment by cuddleandtea** [comment]
Офы ответили, что СО2 не должно быть. Сам СО2 создаёт огонь, как побочный продукт, у которого это прописано в коде. Это трабл, но никто не фиксил его

**Comment by ImJustKisik** [comment]
Не баг, а фича. Если поправят на апстриме - подтянем.
