### ISSUE TITLE
Механ: Нагрев водорода

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#335]
**Название:**
`Любая емкость для водорода`

**Дополнительная информация:**
Раньше при нагреве водорода давление в трубе или емкости было гораздо ниже, чем сейчас. Возможно таким образом на оффбее хотели нерфануть лимитки на водороде, что бы нельзя было сделать действительно сильных  лимиток ограничив количество молей в канистре под форон ещё больше, но я в этом сомневаюсь. Не знаю что хотели этим сделать разрабы, но подобное новое поведение водорода очень смущает при настройке СМки.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094559321343406171)

**Comment by YegorKandziuba** [comment]
Не актуально. Мы теперь будем использовать механ Бея. Пусть атмосфера там работает так же как есть
