### ISSUE TITLE
Запрос: Отсутствует ssay

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#337]
**Название:**
`ssay`

**Дополнительная информация:**
Администрация и модерация пользуется этим каналом при общении друг с другом внутри раунда. При отсутствии данной команды у нас теряется внутрираундовая коммуникация между модерацией. Администрация имеет свой ачат, но это тоже нужно, но недостаточно.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094561966984536064)

**Comment by SuhEugene** [comment]
Зато есть msay
