### ISSUE TITLE
Карта: Ноутбуки в комнате АВД

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#350]
**Название:**
`laptop`

**Дополнительная информация:**
Они повернуты почему-то сразу вниз, а не в стороны стульев. Это вызывает странный конфуз. 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1094896171635453962)

**Comment by LordNest** [comment]
Ноутбуки требуют чего? Правильно, респрайтов чтобы спрайты понравились на Бее.

**Comment by SuhEugene** [comment]
Бэй этого не добавляет. Никто этого не добавляет. Никто это и не наспрайтит.
