### ISSUE TITLE
Вернуть бармену свет

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#36]
- [x] Добавить в игру неоновые лампы
- [x] Развешать неоновые лампы там, где они были на оригинальной карте, включая бар и аквариум

**Comment by LordNest** [comment]
Требуется ассигн или от другого кодера, или же закрытие данного иссуя по причине "требуется отдельная переработка неоновых огней"

**Comment by SuhEugene** [comment]
Моя работа на этом сделана. Нужно чтобы @YegorKandziuba намаппил у себя в ветке, чтобы конфликтов лишних не возникло.
