### ISSUE TITLE
Запрос: Установить минимальный возраст по профессиям

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#368]
**Название:**
`minimal profession age `

**Дополнительная информация:**
18 летние капитанши Сьерры, АЦПСС, ГКК. Да, тяжело будет отслеживать невежд, которые не знают за возраста и требования. Но и админам станет полегче от ПМок по поводу "у этого хирурга минимальный возраст меньше на два года от допустимого"
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1095664689561731163)

**Comment by cuddleandtea** [comment]
Для ксенорас тоже необходимо будет установить свои минимальные возраста по должностям, так что беру эту долгосрочную фичу на себя.
