### ISSUE TITLE
Механ: Открытие шлюза при попытке взлома

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#398]
**Название:**
`airlock`

**Дополнительная информация:**
Если открыть отверткой панель шлюза, то его до сих пор можно открыть нажав на него повторно. Но куда проблемнее это когда он открывается при повторном нажатии на него держа в руках мультитул или кусачки. Это крайне опасно, ведь если за шлюзом который инженер старается починить или заблотировать он внезапно откроется, то может произойти всякое. К пример, инженер обнаружил, что шлюз камеры СМ незаболтирован. Он подходит, открывает панель в попытках заболтировать, что бы обезопасить СМ, а шлюз открывается при нажатии мультитулом по нему.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `KandJX#8769` / `185532218347749376`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1097123022156075038)

**Comment by LordNest** [comment]
В целом, механика открытия шлюза при вскрытой панели - базовая механика SS13. Стандартный алгоритм действий: отвёртка кусачки/мультитул на питание, лом - это то, что универсально делается на всех серверах. 
Не считаю эту унификацию от оффбея большой проблемой.
Лично моя позиция - не нужно.

**Comment by SuhEugene** [comment]
> В целом, механика открытия шлюза при вскрытой панели - базовая механика SS13. Стандартный алгоритм действий: отвёртка кусачки/мультитул на питание, лом - это то, что универсально делается на всех серверах. Не считаю эту унификацию от оффбея большой проблемой. Лично моя позиция - не нужно.

Полагаю тут ишью в том, что при нажатии кусачками на шлюз не только панель обрезания проводов высвечивается, но и шлюз открывается

**Comment by LordNest** [comment]
https://github.com/Baystation12/Baystation12/pull/34408
