### ISSUE TITLE
Баг: Исчезают декали по области

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#400]
**Ckey**:
`CuddleAndTea`

**Шаги:**
1. В баре около смежных полов есть декальки (скрин)
2. При снятии 1 тайла пола уничтожаются все декали в радиусе 1 тайла. 

**Реальное поведение:**
Удаляются смежные декали

**Ожидаемое поведение:**
Удаляться должен декаль только одного тайла
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1097201783186653395)

**Comment by cuddleandtea** [comment]
Оказалось, что такой баг ловится только на билдмоде и это вполне себе нормальная тема. А так как это чисто админская фича, то и фиксить это не вижу смысла
