### ISSUE TITLE
Запрос: Сгущенка

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#432]
**Название:**
`сгуха и варенка`

**Дополнительная информация:**
Портировать с Сыра, но переделать в бутылку и сделать банку контейнером, а не отдельным снеком. 
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1100091461904646184)

**Comment by cuddleandtea** [comment]
Я бы не хотел видеть это сейчас в ишью.

**Comment by SuhEugene** [comment]
Ахаха
