### ISSUE TITLE
Запрос: spawn reagents 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#433]
**Название:**
`dispenser cartrige `

**Дополнительная информация:**
В дебаг у админов на сыре есть возможность спавнить все существующие реагенты в три вида ёмкостей.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1100093024370966549)

**Comment by SolatK** [comment]
/client/proc/spawn_chemdisp_cartridge

set name = "Spawn Chemical Dispenser Cartridge"

Уже есть в билде, но в отличие от сиерры не во вкладке дебаг а в админ

**Comment by SuhEugene** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/32931701/73fa3358-7d41-436e-b459-0c58308abd63)
