### ISSUE TITLE
Баг: Кнопка админов REPLY не посылает факс отправителю

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#542]
**Ckey**:
`CuddleAndTea`

**Шаги:**
1. Получить на админе факс
2. Нажать на REPLY 
3. После отправки факса пишет ошибку "Message reply failed."

**Реальное поведение:**
Не отправляется ответное письмо

**Ожидаемое поведение:**
Факс должен отправиться
<hr>

*Репорт сгенерирован автоматически*
*Автор: `CuddleAndTea#4900` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1108080276426465403)

**Comment by LordNest** [comment]
Воспроизводится. В работу.

**Comment by SuhEugene** [comment]
Следить за
- https://github.com/Baystation12/Baystation12/pull/34142
