### ISSUE TITLE
Запрос: Забугорные бумажки

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#608]
**Название:**
`/datum/computer_file`, `/obj/item/paper`

**Дополнительная информация:**
Нужно перевести на русский все формы, бумаги, а также, желательно, и бумажки авеек.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `SuhEugene#4680` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1113417510981742603)

**Comment by ImJustKisik** [comment]
![image](https://github.com/SierraBay/SierraBay12/assets/87862013/8339e1ca-807c-43b1-b22c-40499e8da490)
хм

**Comment by SuhEugene** [comment]
> ![image](https://user-images.githubusercontent.com/87862013/242321790-8339e1ca-807c-43b1-b22c-40499e8da490.png) хм

Ну, значит бюрократия отпавдает, но перевод бумажек на авейках всё так же нужен
