### ISSUE TITLE
Запрос: Загибания края перчаток

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#638]
**Название:**
`Любые перчатки`

**Дополнительная информация:**
На Сьерре можно было через ПКМ загнуть перчатки, чтобы могли отображаться предметы (например часы) поверх перчаток. Теперь такой функции нет.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114954719203434600)

**Comment by LordNest** [comment]
Есть более актуальный дубль
