### ISSUE TITLE
Баг: Кассеты бармена

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#641]
**Ckey**:
`GeroZer0`

**Шаги:**
1. заспавнится барменом 
2. понять, что у тебя баг кассетника

**Реальное поведение:**
У кассетника нет текстуры, он появляется без кассет, но с отверткой

**Ожидаемое поведение:**
Есть кассеты, отвертка, и текстура
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114959543999410259)

**Comment by LordNest** [comment]
![Image](https://github.com/SierraBay/SierraBay12/assets/77477080/7725367a-ffb9-47e2-bc04-e341627cd4de)

Решён Канджи в ПРе, который мне лень искать
