### ISSUE TITLE
Баг: Слетает реди в лобби

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#642]
**Ckey**:
`Zagadka`

**Шаги:**
1. Нажать реди
2. Дождаться начала раунда
3. Реди слетает, Сьерра пуста и тебя там нету

**Реальное поведение:**
Реди слетает, Сьерра пуста и тебя там нету

**Ожидаемое поведение:**
Реди не слетает, ты на Сьерре
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114961108462211154)

**Comment by SuhEugene** [comment]
Последим на ОБТ, не должно такого говна быть по факту

**Comment by YegorKandziuba** [comment]
@SuhEugene этот ишуй не аткуален?

**Comment by SuhEugene** [comment]
Актуальность сомнительна. Возможно акутален, но повторения этого ишью не видел и жалоб тоже, так что можно считать что норм
