### ISSUE TITLE
Баг: Нет выбора контрактной униформы в лодауте

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#644]
**Ckey**:
`gusevduhast`

**Шаги:**
1. Зайти в лодаут
2. Выбрать контрактную униформу
3. Увидеть что нет кнопки выбора типа униформы

**Реальное поведение:**
Нет кнопки выбора униформы

**Ожидаемое поведение:**
Должна быть кнопка выбора контрактной униформы
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Скавен-крыс#1932` / `275692473295044608`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114964583615045752)

**Comment by LordNest** [comment]
Используйте корпоративную, не маленькие, тем более там тот же самый список
