### ISSUE TITLE
Запрос: Лут в техах слишком хорош

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#645]
**Название:**
`Нет`

**Дополнительная информация:**
Я нашел в техах тактический шлем, бронированные перчатки и ящик полный МРЕ, как-то перебор для техов, не так ли?
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114965142254395392)

**Comment by SuhEugene** [comment]
Запрос интересный, на ОБТ надо смотреть и подтвержать

**Comment by LordNest** [comment]
4 рулем ГА лут в техах признан нормальным
