### ISSUE TITLE
Запрос: ОБР в IC

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#646]
**Название:**
`Вкладка IC`

**Дополнительная информация:**
Во вкладке IC у меня есть кнопка join response team
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Загадка#0170` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114966194202611893)

**Comment by LordNest** [comment]
Выглядит как баг, а не запрос
