### ISSUE TITLE
Баг: При потере сознания автоматически отключается подача кислорода в костюме

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#648]
**Ckey**:
`MaekoGreenfield`

**Шаги:**
1. Надеть скафандр
2. Включить баллон
3. Потерять сознание

**Реальное поведение:**
Баллон уходит в выключенное состояние

**Ожидаемое поведение:**
Подача смеси из баллона продолжается
<hr>

*Репорт сгенерирован автоматически*
*Автор: `greenfield#1363` / `258962443441537024`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114968442190168085)

**Comment by SuhEugene** [comment]
Не забыть попробовать повторить на оффах...

**Comment by LordNest** [comment]
Не воспроизводится
