### ISSUE TITLE
Баг: Травмы видны сквозь одежду

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#651]
**Ckey**:
`Wolfor by Kot`

**Шаги:**
1. Получить травму
2. Увидеть её через одежду

**Реальное поведение:**
Слой травм виден поверх одежды

**Ожидаемое поведение:**
Слой травм не должен быть виден поверх одежды
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Exercitatus#1994` / `444155922533842944`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1114972322118508547)

**Comment by SuhEugene** [comment]
В https://github.com/SierraBay/SierraBay12/pull/568 оффы сделали так, что все оверлеи ран, бинтов и шин (`wounds, gauze, and splints`) размещаются поверх одежды.

Не баг, а фича.
