### ISSUE TITLE
Запрос: Set Ghost Alpha

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#654]
**Название:**
`Set Ghost Alpha?`

**Дополнительная информация:**
Перетащить с лайва на сыробей кнопку для гостов, конкретнее Set Ghost Alpha
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Exercitatus#1994` / `444155922533842944`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115006977257517216)

**Comment by SuhEugene** [comment]
1. Перетащить с лайва - Механ, а не запрос.
2. Дубликат https://github.com/SierraBay/SierraBay12/issues/171
