### ISSUE TITLE
Баг: Слишком медленный спавн персонажей

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#655]
**Ckey**:
`LordNest`

**Шаги:**
1. Нажать реди
2. Подождать загрузки раунда

**Реальное поведение:**
Лобби "подвисает" выдавая картинку согласно которой вы не попали в игру (возможно зайти за свободную роль) после чего вы оказываетесь голым на месте спавна (у криокапсул), после чего вас уже спавнит.

**Ожидаемое поведение:**
После окончания загрузки ваш персонаж должен оказаться сразу на рабочем месте без "ожидания" у криокапсул без одежды
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LordNest#5211` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115017319761051658)

**Comment by SuhEugene** [comment]
Пофикшу при переходе на чистый бэй. Скорее с переносом этого всего дела на оффы

**Comment by SuhEugene** [comment]
Пофикшено с переходом на чистый бэй
