### ISSUE TITLE
Баг: Донаты с Оникса перетянуты к нам

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#658]
**Ckey**:
`LordNest`

**Шаги:**
1. Открыть Лодаут
2. Открыть вкладку General
3. Найти Flask

**Реальное поведение:**
Flask находится в донатном лодауте и подписан как Captain Flask

**Ожидаемое поведение:**
Фляга не должна быть в донатном лодауте и должна быть обычной
<hr>

*Репорт сгенерирован автоматически*
*Автор: `LordNest#5211` / `286536768726237185`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115311450207031356)

**Comment by SuhEugene** [comment]
Это всё будет переделано под то как скажет Азиз
