### ISSUE TITLE
Запрос: В термос из лодаута нельзя налить БЕЗ алкогольные напитки 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#659]
**Название:**
`vacuum-flask`

**Дополнительная информация:**

На Сиерре во флягу наливается алкоголь, а в термос соки и тд, тут же видимо сухой закон и в термос наливают алкашку на ровне с флягой
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115331364464635934)

**Comment by SuhEugene** [comment]
Я нихера не понял. Это однозначно надо переоформлять как `/репорт баг`
