### ISSUE TITLE
Баг: При осмотре никто не знает кто я, а я не знаю кто они

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#662]
**Ckey**:
`GeroZer0`

**Шаги:**
1. Взять ксенорасу Таяра(вероятно это есть и на други)
2. осмотреть других людей

**Реальное поведение:**
Пишет АНКНОВН ХУМАН/ АНКОВН ТАДЖАРА

**Ожидаемое поведение:**
Пишет Имя, раса, пол(пол у людей, а не ксеносов)
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Gero_0#1404` / `468677694855446540`*

**Comment by SuhEugene** [comment]
Пробабли дубликат https://github.com/SierraBay/SierraBay12/issues/370
