### ISSUE TITLE
Старый спрайт: Шляпа инженеров

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#663]
**Объект:**
Шляпа инженеров

**Название:**
`corporate engineering beret`

**Дополнительная информация:**
Спрайта нет. Его нет. Ну нет его.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Shap04ka#9929` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115340180124094595)

**Comment by SuhEugene** [comment]
Надел мужик шляпу, а она ему как раз!
Надел другую, а она ему как два!
Примерил третью, а спрайта нет. Его нет. Ну нет его.

**Comment by SuhEugene** [comment]
Дубликат https://github.com/SierraBay/SierraBay12/issues/292
