### ISSUE TITLE
Баг: При переплавке осколков в руке сваркой предмет исчезает

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#664]
**Ckey**:
`2Bro2B`

**Шаги:**
1. Взять в руку сварку и осколок
2. Кликнуть сваркой по осколку
3. Наблюдать пустоту

**Реальное поведение:**
Ну... Ничего. Предмет исчезает

**Ожидаемое поведение:**
На пол должен выпасть предмет соответствующий переплавленному осколку
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Shap04ka#9929` / `405390889268019200`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115340791464857700)

**Comment by LordNest** [comment]
Воспроизводится. Если держать стекло в руке и сваркой заварить, то оно пропадает. Если использовать на харме сварку, то она разбивает стекло.
На полу стекло не пропадает и работает как задумано

**Comment by SuhEugene** [comment]
Следить за
- https://github.com/Baystation12/Baystation12/pull/34135
