### ISSUE TITLE
Баг: Объекты на фото едут 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#666]
**Ckey**:
`Remission`

**Шаги:**
1. Взять камеру.
2. Поставить количество тайлов (фокус) на фото 3/5/7.
3. Увидеть, что на фото всё перемешалосьи  часть объектов черная.

**Реальное поведение:**
Объекты на фото поехали

**Ожидаемое поведение:**
На фото должно быть изображение того, как всё сейчас в игре
<hr>

*Репорт сгенерирован автоматически*
*Автор: `Remission#3553` / `226681284594892800`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115355420622602310)

**Comment by yosoyrebelde** [comment]
Камера использует прок getFlatIcon. А он не всегда рендерит правильный dir (поэтому объекты "едут"). А чёрные объекты — это он пытается рендерить emissive оверлеи, которые рендериться не должны, поскольку используются исключительно в качестве альфа-маски.
На оффах о проблеме знают, там вроде решили подождать 515 и потом фиксить.

**Comment by SuhEugene** [comment]
То что с эмиссивами связано - нужно трекать на оффах, а то, что я сломал перестаёт таким являться после нового переезда на бэй
