### ISSUE TITLE
Баг: Гиб при разгрузке.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#669]
**Ckey**:
`L1rxem`

**Шаги:**
Сесть в ангар на Сьерре.
1. Зайти на Хрон.
2. Прийти в грузовой отсек.
3. Прыгнуть в зону разгрузи.
4. Тело анигилирует.

**Реальное поведение:**
Тело просто пропадает без возможно его восстановить, оно просто удаляется.

**Ожидаемое поведение:**
Тело должно вылететь при разгрузке с травмами.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `L1rxem#5819` / `257561474103377921`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115375220153397439)

**Comment by KamSurvivor** [comment]
Под мусоркой нет трубы мусоросбросной. Тебя выкидывает нахуй в нуллспейс. Это работает и на лайве у нас. Там еще звук характерный, как если бы ты прыгнул в блюспейс жижу.

Это легко воспроизвести с какой угодно мусоркой.  Собственно, просто спиливаем мусоросбросную трубу из под дисплойся и ваш портал в пизду готов.

Продублировал из дискорда сюда. На случай, если конкретно прикол с нуллспейс мусоркой кто-то решится фиксить.

**Comment by LordNest** [comment]
Не воспроизводится. Только один тест из 20 забегов показал гиб конечности.
