### ISSUE TITLE
Запрос: Отсутствие пресетов вещей. 

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#670]
**Название:**
`Админские кнопки.`

**Дополнительная информация:**
Кароче. Если на лайве тыкнуть ПКМ по кукле, будет опция select ecupment. Это опция пресетов одежды и вещей, которые кукла получает автоматически. Обязательно нужно перенести с лайва.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `L1rxem#5819` / `257561474103377921`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1115375779140870145)

**Comment by ImJustKisik** [comment]
Админ скилл иссуе, VV > DressUp

**Comment by SuhEugene** [comment]
Юджин говорит гихаб скилл иссуе. Нот планнед
