### ISSUE TITLE
Запрос: проверить названия навпоинтов для шаттлов по уровням Сьерры

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#712]
**Название:**
`на sdmm имеют спрайт сетки из сетемёта`

**Дополнительная информация:**
На сыре эти названия сделаны ультра криво. Есть четвёртые палубы, "стороны света не совпадают", ориентация по координатам в скобках тоже вроде бы не совсем корректна. Названия надо фиксить через VS
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea#0` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1120637413044265081)

**Comment by YegorKandziuba** [comment]
Вроде как @LordNest это сделал. Нест, закроешь ишуй?

**Comment by LordNest** [comment]
Да, я этим занимался, вроде даже корректно. Нужно будет - переоткроем.
