### ISSUE TITLE
Идея: Новостная колонка с инфой по лору торча с оффбея

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#738]
**Название:**
`Newspaper`

**Дополнительная информация:**
Для синхронизации актуальности лора предлагаю идеально вписать внутрь IC нашей игры всё то развитие политического положения ЦПСС, ГКК и корабля Торч на фронтире через новостную ленту. Необходимо накодить отдельный канал, на котором на постоянной основе будут содержаться переведенные статьи из данного источника https://baystation.xyz/index.php?title=Timeline_of_Canon_Events
<hr>

*Репорт сгенерирован автоматически*
*Автор: `cuddleandtea#0` / `265550737780506625`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1123967013346353213)

**Comment by LordNest** [comment]
Меняю на идею
