### ISSUE TITLE
Пофиксить юниттест для комментариев в list'ах

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#77]
```dm
list(
	"Item A",
	// Комментарий
	"Item B"
)

**Comment by LordNest** [comment]
@SuhEugene это тоже напоминалка?

**Comment by SuhEugene** [comment]
> @SuhEugene это тоже напоминалка?

@LordNest в точку

**Comment by LordNest** [comment]
> > @SuhEugene это тоже напоминалка?
> 
> @LordNest в точку

@SuhEugene напоминалка всё ещё актуальная?

**Comment by SuhEugene** [comment]
Нахер, похер
