### ISSUE TITLE
Маппинг

### ISSUE THREAD

**Issue by SuhEugene** [SierraBay/SierraBay12#89]
- [x] Нужны плазмадоры<br>![image](https://user-images.githubusercontent.com/32931701/222182588-81670ace-7822-4de4-9fbe-2d17bafdb037.png)
- [x] Нужна камера<br>![image](https://user-images.githubusercontent.com/32931701/222185397-57fa220b-5777-4f7c-9bd5-6ad6404e72fe.png)
- [x] Нужно затенение<br>![image](https://user-images.githubusercontent.com/32931701/222186386-3970b1d8-4608-4529-ac54-3ca6205e275b.png)
- [x] Секретные доки АВД с факса в шкаф <br>![image](https://user-images.githubusercontent.com/32931701/222186479-248b7acd-5571-4993-8e3b-f55490ffc1e7.png)

**Comment by LordNest** [comment]
Необходимо удалить стазисные мешки: 
- [x] Шкаф ГУПа
- [x] Шкаф Харона
- [x] Шкаф Medical Equipment в медбее

Необходимо вернуть стазисные мешки:
- [x] Склад карго. 2 шт.
