### ISSUE TITLE
Баг: У тикетов нету русских символов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#926]
**Ckey**:
`Zagadka`

**Шаги:**
1. Написать в ахелп
2. Посмотреть историю тикетов

**Реальное поведение:**
Русский текст превращается в древние руны

**Ожидаемое поведение:**
Русский текст не древние руны
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147918553681494088)

**Comment by SuhEugene** [comment]
Ждём:
- https://github.com/Baystation12/Baystation12/pull/34196

**Comment by LordNest** [comment]
Ну закрыто получается
