### ISSUE TITLE
Запрос: Странная работа настройки персонажа

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#928]
**Название:**
`Иконка куклы в настройке персонажа`

**Дополнительная информация:**
В настройке персонажа ресайз работает очень странно, показывая тебе, возможно, чужих персонажей.
Изменения не сразу отображаются.
Нельзя одновременно посмотреть униформу и вещи из лодаута.
В лодауте не видно изменений, у тебя просто голая кукла.
Всё есть в ветке в видео.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147920112242929725)

**Comment by LordNest** [comment]
Закрываем по причине полной переработки лодаута #1853
