### ISSUE TITLE
Баг: При открытии шлюза появляется странный символ

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#930]
**Ckey**:
`Zagadka`

**Шаги:**
1. Открыть шлюз
2. Увидеть странный символ под ним, после анимации открывания

**Реальное поведение:**
Появляется странный символ

**Ожидаемое поведение:**
Шлюз открывается без странных символов
<hr>

*Репорт сгенерирован автоматически*
*Автор: `zagadkin` / `951463241215791134`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147925828534013962)

**Comment by SuhEugene** [comment]
Больше не появляется dogeSmile

Наверное оффы пофиксили, а я не заметил как принял ПР с фиксом
