### ISSUE TITLE
Баг: Подмена в альт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#933]
**Ckey**:
`GeroZer0`

**Шаги:**
1. нажать Альт клик на кучу предметов
2. лицезреть кучу неразберихе

**Реальное поведение:**
Эконки предметов перетасованы

**Ожидаемое поведение:**
предмет - иконка
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147939690931036161)

**Comment by SuhEugene** [comment]
Проблема бьёнда, увы
