### ISSUE TITLE
Звук: Джукбокс не играет за экран

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#934]
**Название:**
`space jukebox`

**Дополнительная информация:**
На Сиерре джубокс в отличии от радио и тд играет музыку еще в не экрана, старый репорт, но еще не пофикшен
<hr>

*Репорт сгенерирован автоматически*
*Автор: `gero_0` / `468677694855446540`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147942278804021340)

**Comment by cuddleandtea** [comment]
Дубляж ишью
