### ISSUE TITLE
Старый спрайт: Огнемёт

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#937]
**Объект:**
Огнемёт

**Название:**
`flamethrower`

**Дополнительная информация:**
Спрайт поломан
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147953001168896020)

**Comment by LordNest** [comment]
@SuhEugene ты это Раяну репортил?
