### ISSUE TITLE
Запрос: Команда рации не понимает кириллицу

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#938]
**Название:**
`любые рации`

**Дополнительная информация:**
`.р` должно быть == `.h`
`.ь` должно быть == `.m`
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147953907704803338)

**Comment by SuhEugene** [comment]
Ждём
- https://github.com/Baystation12/Baystation12/pull/34195
