### ISSUE TITLE
Запрос: Меню раздевания

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#940]
**Название:**
`---`

**Дополнительная информация:**
Докинуть fake nanoui меню раздевания
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147988355657773077)

**Comment by LordNest** [comment]
https://github.com/SierraBay/SierraBay12/pull/1117
