### ISSUE TITLE
Баг: Кодировка меню тикетов

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#941]
**Ckey**:
`SuhEugene`

**Шаги:**
1. Открыть меню тикетов.
2. Это всё, конец

**Реальное поведение:**
Кодировка не отображается адекватно

**Ожидаемое поведение:**
-----------------
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1147989427302432778)

**Comment by LordNest** [comment]
Южик всё пофиксил
