### ISSUE TITLE
Запрос: Обновление лодаута

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#956]
**Название:**
`loadout`

**Дополнительная информация:**
Иконка персонажа в лодауте должна обновляться и при открытии, и после постоянно
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148317383350567013)

**Comment by LordNest** [comment]
@SuhEugene эту вещь вроде каким-то коммитом на Ониксах фиксили, да?
