### ISSUE TITLE
Баг: Player panel отправляет в нуллспейс

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#958]
**Ckey**:
`ki1leruqueen`

**Шаги:**
1. RMB по госту
2. Открыть Player Panel
3. Any race

**Реальное поведение:**
Игрок попадает в нуллспейс

**Ожидаемое поведение:**
Игрок становится мобом
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148318722361131020)

**Comment by SuhEugene** [comment]
Следить за
- https://github.com/Baystation12/Baystation12/pull/34143
