### ISSUE TITLE
Баг: Не работает прыжок к шаттлу.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#963]
**Ckey**:
`ki1lerqueen`

**Шаги:**
1. Открыть Admin -> Secrets -> Admin Secrets -> Jump a shuttle.

**Реальное поведение:**
Ничего не происходит.

**Ожидаемое поведение:**
Прыжок госта к любому шаттлу указанному в списке.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `internalaffairsagent` / `321970409081667585`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148574143718101153)

**Comment by LordNest** [comment]
Прыгает не гост к шаттлу, а сам шаттл в указанную точку. 
Возможно стоит добавить отдельный пункт по прыжкам админгостов К шаттлам, но потом.
