### ISSUE TITLE
Запрос: Quick equip

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#965]
**Название:**
`Клавиша E`

**Дополнительная информация:**
Вернуть эту фичу как и быстрый эквип вещей в нужные слоты, Тулбелт? Значит туда держа отвёртку на Е она пихается туда (Как и все доступные для этого вещи в слоты тулбелта) и для остальных поясов такой же прикол.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148595630957150218)

**Comment by LordNest** [comment]
Вот пофиксил же
Сколько дублей-то
