### ISSUE TITLE
Баг: Нет  режимов переключения света на выключателях. И проги у командование наверн.

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#967]
**Ckey**:
`Werewolfen`

**Шаги:**
У людей отобрали сокровенное, 3 режима переключения света, автоматика, полу-автоматика и ручной. А ещё предполагаю, что убрали прогу что позволяла включить везде свет у командования в определённое положение по всему судну.
Кликнуть ПКМ по переключателю света и осознать боль бытия. Проверить прогу командования.

**Реальное поведение:**
Осознание всей боли от отсутствия режимов.

**Ожидаемое поведение:**
Прилив эндорфинов от осознания что всё есть.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148599980303597568)

**Comment by SuhEugene** [comment]
Пепепоинт. Вонтфикс
