### ISSUE TITLE
Баг: Расскраска покрытия покрывается на спрайт ковров

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#968]
**Ckey**:
`NyoRRkish`

**Шаги:**
1. Взять любой ковёр
2. Поставить его замест плитки с расскраской

**Реальное поведение:**
Декали оказываются поверх ковра

**Ожидаемое поведение:**
Декали удаляются
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148600920683315210)

**Comment by SuhEugene** [comment]
Повторяется, но почти нереально поймать
