### ISSUE TITLE
Баг: Крафт оружия сломан

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#969]
**Ckey**:
`Teteshnik`

**Шаги:**
Попробовать скрафтить оружие любое оно попросту до конца не собирается

**Реальное поведение:**
Оружие не собирается

**Ожидаемое поведение:**
Оружие крафтится по рецепту
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148601535547330590)

**Comment by SuhEugene** [comment]
Всё крафтится
