### ISSUE TITLE
Баг: Экзокостюмы гуляют по космосу без полётного модуля

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#971]
**Ckey**:
`Werewolfen`

**Шаги:**
Сесть в экзач и выйти в космос. (Я нашёл экзач на авейке Supply station и на нём спокойно гулял по космосу как по поверхности обычной).

**Реальное поведение:**
Экзокостюм может ходить по космосу

**Ожидаемое поведение:**
Экзокостюм улетает вперёд по инерции
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148601891165569024)

**Comment by SuhEugene** [comment]
Следить за:
- https://github.com/Baystation12/Baystation12/pull/34154
