### ISSUE TITLE
Запрос: Перенести вкладку взаимодействий ИПС

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#972]
**Название:**
`Detach limb`

**Дополнительная информация:**
1Вкладка взаймодействий ИПСа находится в ИЦ
<hr>

*Репорт сгенерирован автоматически*
*Автор: `suheugene` / `706124306660458507`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1148608852464500836)

**Comment by Lexanx** [comment]
Неактуально

**Comment by LordNest** [comment]
:clueless: 
Ну хотя бы меня пингуйте, господа.
Раз вам не актуально.
