### ISSUE TITLE
Старый спрайт: Шкаф с огнетушителем и экстренный

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#978]
**Объект:**
Шкаф с огнетушителем и экстренный

**Название:**
`fire-safety closet и emergency closet`

**Дополнительная информация:**
НАПОЛЬНАЯ версия этих обоих шкафов выглядит отстойной и пластиково, вернуть прошлые версии было бы очень каким хорошим решением.

Настенная версия fire-safety closet вполне себе норм.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1149012083959156870)

**Comment by LordNest** [comment]
Пофикшено
