### ISSUE TITLE
Карта: Неправильный спрайт шкафа с огнетушем

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#979]
**Название:**
`fire-safety closet`

**Дополнительная информация:**
В ангаре справа от гуппи, где находится труба CO2 Supply стоит  fire-safety closet Настенного типа, прямиком на трубе, а должен стоять напольный.

Но лучше всего настенный прихуярить на стену просто чтобы он не загораживал трубу ибо бред, что на помпе стоит шкаф целый.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1149012623141126225)

**Comment by YegorKandziuba** [comment]
Исправлен
