### ISSUE TITLE
Старый спрайт: Ёбанные пластилиновые шкафы ч2...

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#981]
**Объект:**
Ёбанные пластилиновые шкафы ч2...

**Название:**
`chef's closet, closet, kitchen cabinet, hydroponics locker, etc.`

**Дополнительная информация:**
Я заебусь писать сюда все шкафы, просто надо старые спрайты старых шкафов, ВСЕХ.
<hr>

*Репорт сгенерирован автоматически*
*Автор: `werewolfen` / `504259797453897729`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1149015743602626570)

**Comment by LordNest** [comment]
Пофикшено
