### ISSUE TITLE
Баг: Можно уронить трейторский arm-blade

### ISSUE THREAD

**Issue by SierraHelper** [SierraBay/SierraBay12#982]
**Ckey**:
`Reishi42`

**Шаги:**
1. Установить arm blade
2. Активировать чтобы он появился в руке
3. Нажать "отпустить" предмет (хоткей Q)
4. Увидеть как arm blade упал

**Реальное поведение:**
arm blade падает на пол

**Ожидаемое поведение:**
arm blade невозможно уронить/выбить из рук дизармом
<hr>

*Репорт сгенерирован автоматически*
*Автор: `reishi.` / `194213487843475457`*

**Comment by SierraHelper** [comment]
### [Обсуждение в Discord](https://discord.com/channels/617003227182792704/1149029560457904242)

**Comment by SuhEugene** [comment]
Следить за:
- https://github.com/Baystation12/Baystation12/pull/34159

**Comment by SuhEugene** [comment]
Фикс не прокатил

**Comment by cuddleandtea** [comment]
Более подробное описание и дубль в #1029
